### ISSUE TITLE
 Failed to add session to poll context 

### ISSUE THREAD

**Issue by frahmanu** [CESNET/libnetconf2#10]
I have a netconf server which listens on port 830, and accept client connection and process RPC.
For first session nc_ps_add_session() is successfull and session is added to the poll context, but nc_ps_add_session() is failing always with timeout error for second session.

SESSION 1 :

New incomming session -->
Received Hello message from client. Adding session to poll context.
Successfully added a new session to poll context.

SESSION 2:
New incomming session
Received Hello message from client. Adding session to poll context.
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
ERROR: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
Failed to add new session to poll context.Retrying..
Failed to add new session to poll context. Clossing SSh session.

EDIT:
If the issue is fixed, please point the commit ID .

**Comment by michalvasko** [comment]
Hi,
it should be fixed by the commit 4f9c1418d71f20569de67f1c6572d7a067412493.

Regards,
Michal

**Comment by frahmanu** [comment]
thanks @michalvasko

**Comment by NickZengXL** [comment]
06-21T06:48:06.068: nc_ps_add_session: failed to wait for a pollsession condition (Operation timed out).
06-21T06:48:36.078: nc_ps_add_session: failed to wait for a pollsession condition (Operation timed out).
06-21T06:49:06.088:nc_ps_add_session: failed to wait for a pollsession condition (Operation timed out).

I still hit this issue, that I already have this fix.
