### ISSUE TITLE
netconf server does not send TCP keep alives in call home scenarios

### ISSUE THREAD

**Issue by frimpler** [CESNET/libnetconf2#102]
Hi Michal,
a while ago, you removed the code where the KEEPALIVE socket option will be set in nc_sock_connect(), session_client.c (see commits ac0356e -> 06c860d). Due to the fact that this functionality was/is used in call home scenarios, too, we lost the TCP keep alive for call home. 
I didn't create a pull request myself to correct it, because I'm not sure, how your plans are with it, since rfc8071 points out how to check the aliveness.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
even though RFC 8071 specifies how the keep-alives should be implemented, it does so badly (in short), so never mind that (a better solution is being worked on, or will be in future). So, until then we decided to use TCP keep-alive messages. The commits you referenced did not try to remove keep-alive functionality but make it work in all the cases (as I wrote in the referenced issue of the commit you referenced).

So, if it is not working I will take a look and fix it. How did you check whether keep-alive works?

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,
we noticed it didn't work anymore, when our call home regression tests didn't succeed anymore - right after integrating your change. You have to know, that our netconf test client does not start to send keepalives, in contrast to the libnetconf2 client implementation. In other words, and it is visisble in wireshark, in "listen" scenarios, the server sends keep-alive (as expected) and everything is fine, but in call home scenarios it doesn't.
But, when you test call home with libnetconf2 server + client (what I tried, too), it becomes visible, that only the client sends keep-alive, which hides the problem.
Also from the source code point of view, it's obvious, I guess:
nc_ch_client_thread() calls nc_connect_ch_client_endpt(), the socket for this connection will then be opened in nc_sock_connect() -> _non_blocking_connect(). In the past, in this function(s) the keepalive had been enabled.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
please try it know, it should work.

On a side note, the RFC 8071 mentions only server-side keep-alive so I originally wanted to tell you to set the keep-alive on your client if you need it but I figured it does not cost us anything and it can be generally useful. It just is not standardized and the client detects broken connections without it unlike server and that was the main reason for enabling it.

Regards,
Michal

**Comment by frimpler** [comment]
Yes. Now both peers start their keep-alive, again (in listen and call-home scenarios). Thanks.

Btw.: 
I didn't fully understand your side node above, because this issue complains lacking of server-side keep-alive (rfc8071, 4.1, S7). Anyway, it doesn't matter anymore :-)
