### ISSUE TITLE
Building a libnetconf2 Server and client

### ISSUE THREAD

**Issue by vprasad** [CESNET/libnetconf2#103]
Hi,
I have successfully compiled the libnetconf2 in QNX platform with only commenting the libssh_threads for now and i am not able to find the libss_threads for QNX platform.

Now i want to test the simply netconf get operation with libnetconf2 .
For this i want to write a server and client code .
Do u have any sample server and and client code which can help me in getting started.
I am going through the libnetconf2 fn given in :- https://netopeer.liberouter.org/doc/libnetconf2/devel/index.html

However if i get the sample server and client code .it would be very helpful to me.

Thanks,
Vivek prasad

**Comment by michalvasko** [comment]
Hi,
I am sorry to disappoint you but we have no simple sample code. Documentation is your best bet and for some complex examples you can look at *netopeer2-server* and *netopeer2-cli*.

Regards,
Michal

**Comment by vprasad** [comment]
> Hi,
> I am sorry to disappoint you but we have no simple sample code. Documentation is your best bet and for some complex examples you can look at _netopeer2-server_ and _netopeer2-cli_.
> 
> Regards,
> Michal

Hi Michal,

ok.
Is there any Documentation link with you have which can help me in writing the server and client code using libnetconf2 ?
 
Thanks,
Vivek prasad

**Comment by vprasad** [comment]
> Hi,
> yeah, the documentation you referenced, the whole [how to](https://netopeer.liberouter.org/doc/libnetconf2/devel/howto.html) section should provide all the information.
> 
> Regards,
> Michal

Hi ,
thanks,
I have written a server in see where i am trying to call a nc_server_init .However this fn prototype is :- 

 int nc_server_init(struct ly_ctx *ctx);

May i know where i ly_ctx structure defined .I searched in libyang,libnetconf but i am not able to find the definition of it.

Thanks,
Vivek prasad

**Comment by vprasad** [comment]
Thanks,
Closing the issue.
