### ISSUE TITLE
Error while launching libnetconf2 server 

### ISSUE THREAD

**Issue by vprasad** [CESNET/libnetconf2#106]
Hi ,

I have written a sample server for libnetconf2 and have compiled it in Qnx ppc to generate an executable .
While launching the server executable ,i am getting the below error:-
unknown relocation type in libnetconf2.so.0.12. Symbol:_Multi_threaded.
unknown relocation type in libnetconf2.so.0.12. Symbol:_Multi_threaded.
unknown relocation type in libnetconf2.so.0.12. Symbol:ferror.
unknown relocation type in libnetconf2.so.0.12. Symbol:ferror.
unknown relocation type in libnetconf2.so.0.12. Symbol:clearerr.
unknown relocation type in libnetconf2.so.0.12. Symbol:fread.
unknown relocation type in libnetconf2.so.0.12. Symbol:fileno.
unknown relocation type in libnetconf2.so.0.12. Symbol:isatty.
unknown relocation type in libnetconf2.so.0.12. Symbol:exit.

Any idea why this error might be coming?

Thanks.

**Comment by michalvasko** [comment]
Hi,
it seems your platform uses some really light-weight *libc* missing these functions. You can check whether there is not some other *libc* implementation available that would support all that is needed. There is not much more you can do.

Regards,
Michal

**Comment by vprasad** [comment]
> Hi,
> it seems your platform uses some really light-weight _libc_ missing these functions. You can check whether there is not some other _libc_ implementation available that would support all that is needed. There is not much more you can do.
> 
> Regards,
> Michal

Hi Michal,
In addition to above error ,there are unknown relocation error fo below libyang fns also.

unknown relocation type in libnetconf2.so.0.12. Symbol:lyd_leaf_type.
unknown relocation type in libnetconf2.so.0.12. Symbol:lyd_leaf_type.
unknown relocation type in libnetconf2.so.0.12. Symbol:lyd_leaf_type.
unknown relocation type in libnetconf2.so.0.12. Symbol:lys_find_path.
unknown relocation type in libnetconf2.so.0.12. Symbol:ly_ctx_internal_modules_count.

Howver libyang is generated as a static library .So it should not ask for these atleast while executing.

Thanks,

**Comment by michalvasko** [comment]
Hi,
these functions are in *libyang*, you can check, so you have some linking problems that I am unable to help with.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Vivek,
if creation of a new context is causing a segmentation fault, I am wondering how exactly have you solved the linking problems. Anyway, you have not done so correctly, otherwise it would not crash.

Also, how is it actually possible that you had linking problems during server execution? You said you are linking *libyang* statically so all such problems should occur during compilation.

Regards,
Michal

**Comment by vprasad** [comment]
> Hi Vivek,
> if creation of a new context is causing a segmentation fault, I am wondering how exactly have you solved the linking problems. Anyway, you have not done so correctly, otherwise it would not crash.
> 
> Also, how is it actually possible that you had linking problems during server execution? You said you are linking _libyang_ statically so all such problems should occur during compilation.
> 
> Regards,
> Michal

Hi Michal ,

Earlier i was using static library of libyang .But  now i changed that to a dynamic library .Also after changing libpcre to dynamic library ,my loading error 's are resolved.
I can try once again compiling the libyang if you suspect libyang compilation to be a issue ..
Please suggest .

Thanks,
Vivek prasad

**Comment by michalvasko** [comment]
Hi Vivek,
in that case I have no idea at all what can be wrong. You will have to debug it yourself.

Regards,
Michal

**Comment by vprasad** [comment]
Hi Michal,

Got the issue .
Libpcre was not compiled with the PCRE_SUPPORT_UNICODE_PROPERTIES As On.
Did that .After that the above issue is resolved.

Vivek Prasad

**Comment by michalvasko** [comment]
Hi,
sorry for not replying sooner and yes, that was the problem.

Regards,
Michal
