### ISSUE TITLE
we use CLOCK_REALTIME for  pthread_cond_timedwait in some functions,if the system time is changed by NTP or GPS,is the wait time may be incorrect?

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [CESNET/libnetconf2#108]
we use CLOCK_REALTIME for  pthread_cond_timedwait in some functions,if the system time is changed by NTP or GPS,is the wait time may be incorrect?

For example, if the time changed to earlier than current，is the wait time may be longer than we expect?

**Comment by michalvasko** [comment]
Hi,
yes, this can happen but there is nothing we can do about that. Wherever `CLOCK_MONOTONIC` in *libnetconf2* can be used, it should be used.

The main problem is with the function `pthread_mutex_timedlock()`, which always uses the `CLOCK_REALTIME` and a mutex is always tied with a condition variable, so the same clock should be used for both.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
I am not sure I understand your question but if you are asking whether there is a similar function to `pthread_condattr_setclock()` to set the clock of a mutex, there unfortunately is not for some reason and like I said, I think mixing the clock types is not a good idea.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
Hi,
I mean ,can we set the condattr to CLOCK_MONOTONIC,and also set the wait time second in CLOCK_MONOTONIC, in this way ,the pthread_mutex_timedlock() is use CLOCK_MONOTONIC time to calculate the wait second.
the code like below:

    pthread_mutex_t mtx;
    pthread_cond_t cond;
    pthread_condattr_t con_attr;
    int ret = pthread_condattr_init(&(con_attr));
    ret = pthread_condattr_setclock(&(con_attr), CLOCK_MONOTONIC);
    ret = pthread_cond_init(&(cond), &(con_attr));
    clock_gettime(CLOCK_MONOTONIC, &timeWait);
    timeWait.tv_sec += 5;//watitime
    ret =pthread_cond_timedwait(&(waitingReq->cond), &(waitingReq->mtx), &timeWait);

**Comment by michalvasko** [comment]
Hi,
that will not fix the underlying issue that simply cannot be fixed. You are missing a mandatory locking of `mtx` before `pthread_cond_timedwait()` which will always use `CLOCK_REALTIME` for checking that the timeout has elapsed and therefore giving it `CLOCK_MONOTONIC` `timespec` as input does not improve anything. Thus you are left with `pthread_mutex_timedlock()` on `CLOCK_REALTIME` and `pthread_cond_timedwait()` on `CLOCK_MONOTONIC`. And I think that state is also undesirable and I would rather we use `CLOCK_REALTIME` for both.

Regards,
Michal
