### ISSUE TITLE
call nc_connect_ssh_channel on call home session

### ISSUE THREAD

**Issue by lg19860105** [CESNET/libnetconf2#109]
I have setup a callhome session, if i can setup another new session with  nc_connect_ssh_channel on this session?

**Comment by michalvasko** [comment]
Hi,
you should be able to except this session will not be considered a *Call Home* session (it will not be monitored and reestablished if it terminates). So, if the original session terminates, this one will also (because it will use the same SSH session).

Regards,
Michal
