### ISSUE TITLE
Missing libssh_threads path in dependency check

### ISSUE THREAD

**Issue by frahmanu** [CESNET/libnetconf2#11]
If the dependent library paths are different than default, SSH_LIBRARY library path should be included before loading -lssh_threads library.

File : CMakeLists.txt

dependencies - libssh
if(ENABLE_SSH)
    find_package(LibSSH 0.6.4 REQUIRED)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DNC_ENABLED_SSH ${LIBSSH_DEFINITIONS}")
    target_link_libraries(netconf2 ${LIBSSH_LIBRARIES}  **-lssh_threads** -lcrypt)
    include_directories(${LIBSSH_INCLUDE_DIRS})
endif()

dependencies - libssh
if(ENABLE_SSH)
    find_package(LibSSH 0.6.4 REQUIRED)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DNC_ENABLED_SSH ${LIBSSH_DEFINITIONS}")
    target_link_libraries(netconf2 ${LIBSSH_LIBRARIES}  **-L${SSH_LIBRARY}** **-lssh_threads** -lcrypt)
    include_directories(${LIBSSH_INCLUDE_DIRS})
endif()

**Comment by michalvasko** [comment]
Hi,
I fixed it the way you proposed, so it should at least work now, but for it to be a proper library detection, it would require more changes. We may get to it later.

Regards,
Michal
