### ISSUE TITLE
should we signal other thread when we remove ps queue id which wait timeout?

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [CESNET/libnetconf2#110]
in function nc_ps_lock,we only remove wait id, if we wait it to our turn time out, and i wonder should we also signal other thread wake up  after we remove it?

Think in one condition:
1. Thread A add an id in the second position ,and then wait.
2. And then, Thread B also add an id behind it in position  third.
3. suppose with some reason ,Thread C broadcast an signal before Thread A timeout ,but Thread A not received it. 
4. After this the id of thread A is at the first, when it wait time out ,it remove the id, but not signal Thread B. 
5. Thread B's  id is at the first place, when it time out ,it also remove the id ,but not signal others 
.....
if the program runs in the same way like 1-5, is the  queue in an error condition?

**Comment by ZhaoGuangYue1986** [comment]
hi
Recently i met an strange issue, when this issue happen, the nc_ps_lock can not work well,it always got into timeout condition and any msg can be deal in this condition. And this is not the first time i meet this issue,It is  an very Serious  issue for our  system. 

paste some logs ,hope you can help me to fix this issue.

additionally, when this issue occur, i found our system time changed from 2018-05-02 04:14:28 to 2018-10-30 10:10:44.

thanks very much.

------------------------------------------------------------------------------
2018-05-02 04:14:28.053542 [DBG]:[140319515100928] (rp_dt_find_changes:235) Get changes: /ManagedElement:* limit:100 offset:0 cache miss
2018-05-02 04:14:28.054763 [INF] send_notification_dealer_impl.cpp[37]:send mo notification inst to cli succ.
2018/10/30 10:10:44.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:44.9 [INF]:loop begin index is:3 val:0,wantId:2,tid:[-1164264448]      
2018/10/30 10:10:44.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:44.9 [INF]:loop begin index is:4 val:1,wantId:1,tid:[-1673603328]      
2018/10/30 10:10:45.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:45.4 [INF]:loop begin index is:5 val:2,wantId:2,tid:[-1164264448]      
2018/10/30 10:10:45.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:45.4 [INF]:loop begin index is:0 val:3,wantId:3,tid:[-1673603328]      
2018/10/30 10:10:45.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:45.5 [INF]:loop begin index is:1 val:4,wantId:5,tid:[-1665210624]      
2018/10/30 10:10:45.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:45.5 [INF]:loop begin index is:1 val:4,wantId:4,tid:[-1681996032]      
2018/10/30 10:10:45.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:45.9 [INF]:loop begin index is:2 val:6,wantId:6,tid:[-1164264448]      
2018/10/30 10:10:45.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:45.9 [INF]:loop begin index is:3 val:7,wantId:7,tid:[-1673603328]      
2018/10/30 10:10:46.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:46.0 [INF]:loop begin index is:4 val:8,wantId:8,tid:[-1665210624]      
2018/10/30 10:10:46.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:46.0 [INF]:loop begin index is:5 val:9,wantId:9,tid:[-1681996032]      
2018/10/30 10:10:46.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:46.4 [INF]:loop begin index is:0 val:10,wantId:11,tid:[-1164264448]      
2018/10/30 10:10:46.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:46.4 [INF]:loop begin index is:0 val:10,wantId:10,tid:[-1673603328]      
2018/10/30 10:10:46.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:46.5 [INF]:loop begin index is:1 val:12,wantId:12,tid:[-1665210624]      
2018/10/30 10:10:46.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:46.5 [INF]:loop begin index is:2 val:13,wantId:13,tid:[-1681996032]      
2018/10/30 10:10:46.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:46.9 [INF]:loop begin index is:3 val:14,wantId:14,tid:[-1164264448]      
2018/10/30 10:10:46.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:47.0 [INF]:loop begin index is:4 val:15,wantId:15,tid:[-1673603328]      
2018/10/30 10:10:47.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:47.0 [INF]:loop begin index is:5 val:16,wantId:16,tid:[-1665210624]      
2018/10/30 10:10:47.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:47.0 [INF]:loop begin index is:0 val:17,wantId:17,tid:[-1681996032]      
2018/10/30 10:10:47.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:47.5 [INF]:loop begin index is:1 val:18,wantId:18,tid:[-1673603328]      
2018/10/30 10:10:47.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:47.5 [INF]:loop begin index is:2 val:19,wantId:19,tid:[-1164264448]      
2018/10/30 10:10:47.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:47.5 [INF]:loop begin index is:3 val:20,wantId:20,tid:[-1665210624]      
2018/10/30 10:10:47.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:47.5 [INF]:loop begin index is:4 val:21,wantId:21,tid:[-1681996032]      
2018/10/30 10:10:48.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:48.0 [INF]:loop begin index is:5 val:22,wantId:22,tid:[-1673603328]      
2018/10/30 10:10:48.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:48.0 [INF]:loop begin index is:0 val:23,wantId:23,tid:[-1164264448]      
2018/10/30 10:10:48.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:48.0 [INF]:loop begin index is:1 val:24,wantId:24,tid:[-1665210624]      
2018/10/30 10:10:48.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:48.0 [INF]:loop begin index is:2 val:25,wantId:25,tid:[-1681996032]      
2018/10/30 10:10:48.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:48.4 [INF]:loop begin index is:3 val:26,wantId:26,tid:[-1690388736]      
2018/10/30 10:10:48.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:48.5 [INF]:loop begin index is:4 val:27,wantId:27,tid:[-1673603328]      
2018/10/30 10:10:48.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:48.5 [INF]:loop begin index is:5 val:28,wantId:28,tid:[-1164264448]      
2018/10/30 10:10:48.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:48.5 [INF]:loop begin index is:0 val:29,wantId:29,tid:[-1665210624]      
2018/10/30 10:10:48.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:48.5 [INF]:loop begin index is:1 val:30,wantId:30,tid:[-1681996032]      
2018/10/30 10:10:48.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:48.9 [INF]:loop begin index is:2 val:31,wantId:31,tid:[-1690388736]      
2018/10/30 10:10:49.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:49.0 [INF]:loop begin index is:3 val:32,wantId:32,tid:[-1673603328]      
2018/10/30 10:10:49.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:49.0 [INF]:loop begin index is:4 val:33,wantId:33,tid:[-1164264448]      
2018/10/30 10:10:49.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:49.0 [INF]:loop begin index is:5 val:34,wantId:34,tid:[-1665210624]      
2018/10/30 10:10:49.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:49.0 [INF]:loop begin index is:0 val:35,wantId:35,tid:[-1681996032]      
2018/10/30 10:10:49.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:49.4 [INF]:loop begin index is:1 val:36,wantId:36,tid:[-1690388736]      
2018/10/30 10:10:49.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:49.5 [INF]:loop begin index is:2 val:37,wantId:37,tid:[-1164264448]      
2018/10/30 10:10:49.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:49.5 [INF]:loop begin index is:3 val:38,wantId:38,tid:[-1673603328]      
2018/10/30 10:10:49.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:49.5 [INF]:loop begin index is:4 val:39,wantId:39,tid:[-1665210624]      
2018/10/30 10:10:49.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:49.5 [INF]:loop begin index is:5 val:40,wantId:40,tid:[-1681996032]      
2018/10/30 10:10:49.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:49.9 [INF]:loop begin index is:0 val:41,wantId:41,tid:[-1690388736]      
2018/10/30 10:10:50.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:50.0 [INF]:loop begin index is:1 val:42,wantId:42,tid:[-1164264448]      
2018/10/30 10:10:50.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:50.0 [INF]:loop begin index is:2 val:43,wantId:43,tid:[-1673603328]      
2018/10/30 10:10:50.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:50.0 [INF]:loop begin index is:3 val:44,wantId:44,tid:[-1665210624]      
2018/10/30 10:10:50.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:50.0 [INF]:loop begin index is:4 val:45,wantId:45,tid:[-1681996032]      
2018/10/30 10:10:50.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:50.4 [INF]:loop begin index is:5 val:46,wantId:46,tid:[-1690388736]      
2018/10/30 10:10:50.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:50.5 [INF]:loop begin index is:0 val:47,wantId:47,tid:[-1164264448]      
2018/10/30 10:10:50.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:50.5 [INF]:loop begin index is:1 val:48,wantId:48,tid:[-1673603328]      
2018/10/30 10:10:50.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:50.5 [INF]:loop begin index is:2 val:49,wantId:49,tid:[-1665210624]      
2018/10/30 10:10:50.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:50.5 [INF]:loop begin index is:3 val:50,wantId:50,tid:[-1681996032]      
2018/10/30 10:10:50.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:50.9 [INF]:loop begin index is:4 val:51,wantId:51,tid:[-1690388736]      
2018/10/30 10:10:51.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:51.0 [INF]:loop begin index is:5 val:52,wantId:52,tid:[-1164264448]      
2018/10/30 10:10:51.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:51.0 [INF]:loop begin index is:0 val:53,wantId:53,tid:[-1673603328]      
2018/10/30 10:10:51.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:51.0 [INF]:loop begin index is:1 val:54,wantId:54,tid:[-1665210624]      
2018/10/30 10:10:51.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:51.0 [INF]:loop begin index is:2 val:55,wantId:55,tid:[-1681996032]      
2018/10/30 10:10:51.4 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:51.4 [INF]:loop begin index is:3 val:56,wantId:56,tid:[-1690388736]      
2018/10/30 10:10:51.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:51.5 [INF]:loop begin index is:4 val:57,wantId:58,tid:[-1673603328]      
2018/10/30 10:10:51.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:51.5 [INF]:loop begin index is:4 val:57,wantId:57,tid:[-1164264448]      
2018/10/30 10:10:51.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:51.5 [INF]:loop begin index is:5 val:59,wantId:59,tid:[-1665210624]      
2018/10/30 10:10:51.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:51.5 [INF]:loop begin index is:0 val:60,wantId:60,tid:[-1681996032]      
2018/10/30 10:10:51.9 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:51.9 [INF]:loop begin index is:1 val:61,wantId:61,tid:[-1690388736]      
2018/10/30 10:10:52.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:52.0 [INF]:loop begin index is:2 val:62,wantId:62,tid:[-1673603328]      
2018/10/30 10:10:52.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:52.0 [INF]:loop begin index is:3 val:63,wantId:63,tid:[-1164264448]      
2018/10/30 10:10:52.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:52.0 [INF]:loop begin index is:4 val:64,wantId:64,tid:[-1665210624]      
2018/10/30 10:10:52.0 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:52.0 [INF]:loop begin index is:5 val:65,wantId:65,tid:[-1681996032]      
2018/10/30 10:10:52.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1690388736].
2018/10/30 10:10:52.5 [INF]:loop begin index is:0 val:66,wantId:66,tid:[-1690388736]      
2018/10/30 10:10:52.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1673603328].
2018/10/30 10:10:52.5 [INF]:loop begin index is:1 val:67,wantId:67,tid:[-1673603328]      
2018/10/30 10:10:52.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1164264448].
2018/10/30 10:10:52.5 [INF]:loop begin index is:2 val:68,wantId:68,tid:[-1164264448]      
2018/10/30 10:10:52.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1665210624].
2018/10/30 10:10:52.5 [INF]:loop begin index is:3 val:69,wantId:69,tid:[-1665210624]      
2018/10/30 10:10:52.5 [ERR]:nc_ps_poll: failed to wait for a pollsession condition (Connection timed out),tid:[-1681996032].
2018/10/30 10:10:52.5 [INF]:loop begin index is:4 val:70,wantId:70,tid:[-1681996032]

**Comment by michalvasko** [comment]
Hi,
that is quite a non-standard system behavior but it should not start to time out indefinitely anyway. You can try to print `ts` seconds and nanoseconds instead (after `nc_gettimespec_real()` and after `nc_addtimespec()`), which may tell us more.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
OK,i will try it .

As it not occur frequently, and i have not found the trigger for this issue happen ,the system time change only one suspects for this issue. And from the logs we can see the after the time point  the time  interval is right. Do you have any other suspects ?

**Comment by ZhaoGuangYue1986** [comment]
as our code  do  not use multi-threads ,the problem do not occur .
just close this issue
