### ISSUE TITLE
Query regarding registering callbacks for netconf operations .

### ISSUE THREAD

**Issue by vprasad** [CESNET/libnetconf2#112]
Hi ,

I want to register separate cb's for individual netconf operations like get,get-config,edit-config,create,delete operations for a particular yang.
I have loaded my yangs to ly_ctx and registered a cb using  "nc_set_rpc_callback".

 i am able to see the capabilities of the my yang while doing the login .however when i do a get operation using the below xml .
```xml
<?xml version="1.0" encoding="UTF-8"?>
  <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
    <get>
      <filter xmlns="com:infinera:security:user">
    <users/>    
      </filter>
    </get>
  </rpc>
]]>]]>
```
I get the below error in the logs:-

```
DEBUG: Session 1: received message:
<?xml version="1.0" encoding="UTF-8"?>
  <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
    <get>
      <filter xmlns="com:infinera:security:user">
    <users/>    
      </filter>
    </get>
  </rpc>

ERROR: Unexpected message received instead of <hello>.

```
May i know the correct procedure for registering cbs for get,get-config,edit-config,create,delete operations.

Thanks,
Vivek Prasad

**Comment by michalvasko** [comment]
Hi Vivek,

I am getting a bit tired of your questions. I always try to help but within certain limit. You are attempting to write your own NETCONF server **without** knowing basic information about NETCONF protocol itself and testing it **without** using a proper NETCONF client despite me strongly recommending it. I will answer you this time but it will be the last unless you fix what I have just criticized.

The problem is actually written in the error and I do not have much more to say. The server expected a `hello` message, you sent it a `get` RPC instead.

Regards,
Michal

**Comment by vprasad** [comment]
Hi Michal,
After passing the hello message ,close-session rpc is working fine and i am getting a reply as OK.

I want to register separate cb's for individual netconf operations like get,get-config,edit-config,create,delete operations for self written yangs.
I have loaded my yangs to ly_ctx and its getting loaded successfully. 

Can you please give some hints on implementing the cbs for get rpc for self written yangs. .

Thanks,

**Comment by vprasad** [comment]
Hi Michal,

I have registered the cbs using nc_set_rpc_callback for my module like this: -
   snode = ly_ctx_get_node(sinfo.ly_context, NULL, "/user:users", 0); 
    nc_set_rpc_callback(snode, op_get);

However while send a get request ,the response is failing with below error :- 

[viprasad@in-mvlb46 etc2.0]$ ssh secadmin@10.220.84.110 -p 830 -s netconf
secadmin@10.220.84.110's password: 
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&amp;revision=2016-08-05</capability><capability>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2017-02-20</capability><capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2018-01-17&amp;module-set-id=13</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2018-02-14</capability><capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability><capability>com:infinera:security:user?module=user&amp;revision=2016-12-21</capability></capabilities><session-id>1</session-id></hello>]]>]]><?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
  <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
    <get>
      <filter xmlns="com:infinera:security:user">
    <users/>    
      </filter>
    </get>
  </rpc>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
   <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
     <close-session/>
  </rpc>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1"><rpc-error><error-type>protocol</error-type><error-tag>unknown-element</error-tag><error-severity>error</error-severity><error-message xml:lang="en">Unknown element "filter".</error-message><error-info><bad-element>/ietf-netconf:get</bad-element></error-info></rpc-error></rpc-reply>]]>]]>


its not able to recognize "filter" in xml i/p.Anything to be done for this ?

Thanks,

**Comment by michalvasko** [comment]
Hi Vivek,
your are setting **RPC** callbacks, not `get` callbacks, it is just one of RPCs. If you want to implement `get`, you must set a callback for `/ietf-netconf:get` and in this callback you must retrieve all the data you want to return and then return them in a reply.

For the `filter` element, you must define it in the namespace of `ietf-netconf` because that is where we are storing the definition. It is not actually there but we need the definition somewhere so it is explicitly placed there by *libyang*. However, you should use *libnetconf2* for the client side as well and you will not have to deal with this, it would be performed automatically.

Michal

**Comment by vprasad** [comment]
Hi Michal,
I have registered a callback for ietf-netconf:get and when i query a get request my cb gets invoked.

My question is i have many self written yangs like a user.yang ,eqpt.yang ,etc which i want to retrieve them individually.
So what's the procedure to implement the cbs for specific yangs so that i can retrieve them individually .
and what would be the sample request xml for it 

Currently we are not using libnetconf2 for client side because our customers uses mgsoft netconf browser to connect to the netconf server and do the required operations. . 
 
Appreciate your help !!
Thanks,

**Comment by vprasad** [comment]
> Hi Vivek,
> I am not exactly sure I understand correctly but I will try to answer. Your `get` callback will get always triggered because it is set for that particular RPC. However, you can process the `filter` node of this `get` RPC and then retrieve only the required data. This is exactly what _neotpeer2-server_ and _sysrepo_ do.
> 
> Sample XML would simply be an RPC `get` request with either [subtree](https://tools.ietf.org/html/rfc6241#section-6) or [XPath](https://tools.ietf.org/html/rfc6241#section-8.9.5.1) filter filtering only the data of the particular module.
> 
> Regards,
> Michal

Hi Michal,
Thanks for info.
I am able to parse the filter node and extract which yang info i need to return as a part of get call.

Now  for returning the corresponding yang data lets say user.yang in my case ,i need to call nc_server_reply_data with data attribute of type lyd_node populated with user yang attributes present.

Question is do u have any sample code which fills this lyd_node data in nc_server_reply_data with particular yangs contents which i can refer or some sample steps to be followed for filling the lyd_node as a part of get request.

I was referring netopeer server code it uses sysrepo to extract the info and fill lyd_node .But i can't use sysrepo because our database in present in our routers . 

Thanks,

**Comment by michalvasko** [comment]
Hi Vivek,
you will use *libyang* functions to create it, there are several ways of doing so. You can create the data tree from an XML or JSON data provided by your routers (`lyd_parse_*()`) or you can create the data nodes one-by-one by either `lyd_new_path()` function or by combining `lyd_new()`, `lyd_new_leaf()`, and possibly `lyd_new_anydata()`. Learn more in the [documentation](https://netopeer.liberouter.org/doc/libyang/master/index.html).

Regards,
Michal

**Comment by vprasad** [comment]
> Hi Vivek,
> you will use _libyang_ functions to create it, there are several ways of doing so. You can create the data tree from an XML or JSON data provided by your routers (`lyd_parse_*()`) or you can create the data nodes one-by-one by either `lyd_new_path()` function or by combining `lyd_new()`, `lyd_new_leaf()`, and possibly `lyd_new_anydata()`. Learn more in the [documentation](https://netopeer.liberouter.org/doc/libyang/master/index.html).
> 
> Regards,
> Michal

Hi Michal,
Thanks.
I am now able to get the o/p of the get command for a sample user.yang which contains container with leafs inside it. .
I used lyd_new to allocate container and lyd_new_leaf to form the leafs with appropriate values .

Question is what is the procedure to form the response for the yangs containing a container ,lists and leafs.
Sample yang:-

container X
{
    list Y
    {
       key "a";
       leaf a 
       {
             type string;
        }
         leaf b
        {
             type string;
        }  
    }
}


Thanks,

**Comment by michalvasko** [comment]
HI Vivek,
you simply chain the calls, you first create the container `X`, then its child `Y` and then its children `a` and `b`. We are creating `ietf-yang-library` data this way, look in *libyang* at `context.c:ly_ctx_info()`.

Regards,
Michal

**Comment by vprasad** [comment]
> HI Vivek,
> you simply chain the calls, you first create the container `X`, then its child `Y` and then its children `a` and `b`. We are creating `ietf-yang-library` data this way, look in _libyang_ at `context.c:ly_ctx_info()`.
> 
> Regards,
> Michal

Hi Michal,

Thanks for info.Now i am able to perform the get  operations successfully.

Now i am working on edit-config operation .
I am providing the following attached edit-config xml as i/p .
However the the libyang throws following error while parsing and my edit-config cb does'nt get invoked.:-
libyang[0]: Unknown element "running". (path: /ietf-netconf:edit-config/target/running)

[edit-config.txt](https://github.com/CESNET/libnetconf2/files/2627765/edit-config.txt)

May i know what wrong i am giving as a xml i/p ?

Thanks,
Vivek Prasad

**Comment by michalvasko** [comment]
Hi Vivek,
this is again a bit too basic query that I believe you could have easily fixed yourself. Anyway, most likely you have not enabled `writable-running` feature in `ietf-netconf`, which `<running>` node is restricted by.

Regards,
Michal

**Comment by vprasad** [comment]
> Hi Vivek,
> this is again a bit too basic query that I believe you could have easily fixed yourself. Anyway, most likely you have not enabled `writable-running` feature in `ietf-netconf`, which `<running>` node is restricted by.
> 
> Regards,
> Michal

Hi Michal,

Thanks for help,Now i am able to support get,get-config,edit-config operation via libnetconf2 on Qnx ppc machine

Thanks,

**Comment by vprasad** [comment]
> > Hi Vivek,
> > this is again a bit too basic query that I believe you could have easily fixed yourself. Anyway, most likely you have not enabled `writable-running` feature in `ietf-netconf`, which `<running>` node is restricted by.
> > Regards,
> > Michal
> 
> Hi Michal,
> 
> Thanks for help,Now i am able to support get,get-config,edit-config operation via libnetconf2 on Qnx ppc machine
> 
> Thanks,

Closing this thread as my queries are resolved related to supporting of different netconf operations .
Thanks for help.
