### ISSUE TITLE
Can I use libnetconf2 in asynchronous way ?

### ISSUE THREAD

**Issue by ErikOne** [CESNET/libnetconf2#115]
Hi,

is there a way to use  nc_ps_poll but without immediately writing data to the client. For instance if the data is not instantly available ? Can a session be margked as bussy processing and when the data becomes available send the reply to the client ?  

Regards
Erik

**Comment by michalvasko** [comment]
Hi Erik,
no, there is no support for such processing, it is expected you finish the callback with your final reply.

Regards,
Michal
