### ISSUE TITLE
include yang problem

### ISSUE THREAD

**Issue by zyboy2000** [CESNET/libnetconf2#119]
one yang include an other yang, ODL can not load include yang? device return capbilities have no include yang
```yang
module openconfig-aaa {
  include openconfig-aaa-tacacs;
  include openconfig-aaa-radius;
}
```
 Unable to build schema context, unsatisfied imports {SourceIdentifier [name=openconfig-aaa@2017-09-18]=[ModuleImportImpl [name=openconfig-aaa-radius, revision=2017-09-18], ModuleImportImpl [name=openconfig-aaa-tacacs, revision=2017-09-18]]}, will reattempt with resolved only

**Comment by michalvasko** [comment]
Hi,
you have provided so little information that I have no idea what is it that you are doing. However, I would firstly need to know the connection to our software. You have only mentioned you are using ODL and the message (I guess that is what it is) is not from our library so I am guessing ODL again. So, why have you psoted this as *libnetconf2* issue and not asked ODL for support?

Regards,
Michal

**Comment by sriranat** [comment]
While importing the openconfig-aaa yang , also try to import the openconfig-sytem.yang .. This could solve the module-import problem. The openconfig-system is the parent to openconfig-aaa. 


module openconfig-system {

  yang-version "1";

  // namespace
  namespace "http://openconfig.net/yang/system";

  prefix "oc-sys";

  // import some basic types
  import openconfig-inet-types { prefix oc-inet; }
  import openconfig-yang-types { prefix oc-yang; }
  import openconfig-types { prefix oc-types; }
  import openconfig-extensions { prefix oc-ext; }
  import openconfig-aaa { prefix oc-aaa; }
  import openconfig-system-logging { prefix oc-log; }
  import openconfig-system-management { prefix oc-sys-mgmt; }
  import openconfig-system-terminal { prefix oc-sys-term; }
  import openconfig-procmon { prefix oc-proc; }
  import openconfig-alarms { prefix oc-alarms; }
