### ISSUE TITLE
 How to implement Get-config(Result should contain only config true attributes) using libnetconf . Is there any API that can be used right away?

### ISSUE THREAD

**Issue by sahnnu** [CESNET/libnetconf2#120]
Request XML
```xml
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
<get-config >
          <source>
              <running/>
      </source>
    <filter type="subtree">
        <users xmlns="com:infinera:security:user"/>                                          
    </filter>
</get-config>
</rpc>
]]>]]>
```
It gives me all attributes(irrespective of config true/false)

**Comment by michalvasko** [comment]
Hi,
I have basically no information about your use-case so I cannot really help you. Are you implementing your own NETCONF server and you want to create a reply for the `get-config` RPC request? In that case it is up to you to only return the configuration nodes and no state nodes.

Regards,
Michal

**Comment by sahnnu** [comment]
Thanks, Yes i am implementing my own Netconf by using libnetconf2 But can you suggest how to figure out config type of attributes to form a get-config reply.

**Comment by michalvasko** [comment]
Hi,
it is stored in `struct lys_node` flags as `LYS_CONFIG_W` or `LYS_CONFIG_R` (all flags described [here](https://netopeer.liberouter.org/doc/libyang/master/group__snodeflags.html)), I do not know what else to tell you.

Regards,
Michal

**Comment by sahnnu** [comment]
Thanks
