### ISSUE TITLE
Query regarding setting session inactivity TimeOut

### ISSUE THREAD

**Issue by vprasad** [CESNET/libnetconf2#124]
Hi Michal,

I am using the API "nc_server_set_idle_timeout" with param as 0  to set the session timeout  to infinite,
However i can see the session gets timeout after few seconds if i don't do any operations on it.
Currently i am calling this API after setting up the capabilities,cbs and  before setting the endPoints.
Is it not the correct place to call this API ?Where this API needs to be called to set the inactivity timeout of the session to infinite.

ERROR: Session 1: inactive read timeout elapsed.
ERROR: Session 2: inactive read timeout elapsed.

Thanks,

**Comment by vprasad** [comment]
Hi Michal ,
I again checked the request message that i am sending and can;t find anything extra lines/chars except the <enter> that i press after the end of mssg.
Below steps was performed:-

i logged in via ssh (ssh secadmin@10.220.84.57 -p 830 -s netconf) and after the pwd validation it displayed the capabilites.
Now i just gave the hello xml request and pressed enter and waited for 15 secs and it timed out.

I am sure that the xml hello msg that i am giving does not contain any extra redundant character except the <enter> that i press after the hello mssg .can this cause the issue ?

Below is the hello message that i am sending :- 

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>]]>]]>

Thanks.

**Comment by vprasad** [comment]
Hi Michal ,
I just tested again with MGsoft Netconf client .And the issue is not seen that is the session does not get timeout automatically within Few seconds.
SO now coming back to original question ,i have the requirement to set the inactivity session timeout to fixed user configured value.
Is there an Api for that can be used to set the timeout in run time ?

THanks,
Vivek prasad

**Comment by michalvasko** [comment]
Hi Vivek,
for your original question, yes, sending a redundant `\n` is causing this problem. If you always used a proper NETCONF client which I am advising you to do now maybe for the 5th time, you would not run into this problem.

No, there is no API to change inactivity timeout during run-time.

Regards,
Michal

**Comment by vprasad** [comment]
Hi ,

Thanks for confirmation .Closing ticket
