### ISSUE TITLE
Libnetconf2 Database.

### ISSUE THREAD

**Issue by vprasad** [CESNET/libnetconf2#128]
Hi Michal ,

Do we have any libnetconf2 database which can be used to store information which would remain persistent on a LibNetconf2 Server restart also.?
For reference other netconf provider like tail-f/confd gives a datastore called CDB(Configuration DataBase) which we use to store our info which remains persistant across server restart..
Just wanted to know if we have such things implemented in Libnetconf2 also .?
Thanks,
Vivek Prasad

**Comment by michalvasko** [comment]
Hi Vivek,
no, there is no such thing. *libnetconf2* does not include any datastore, *sysrepo* serves this purpose.

Regards,
Michal

**Comment by vprasad** [comment]
> Hi Vivek,
> no, there is no such thing. _libnetconf2_ does not include any datastore, _sysrepo_ serves this purpose.
> 
> Regards,
> Michal

Hi Michal,

We also need some Db support for our project of Supporting Netconf .
So we were exploring if we also can use Sysrepo as  our datastore.
So why are you using sysrepo as a datastore ,Is it a lightweight datastore or its just easy to use ?

Thanks,
Vivek prasad

**Comment by michalvasko** [comment]
Hi Vivek,
to be honest, it is neither. We are using it because when we started working on *netopeer2-server* there was another project starting, *sysrepo*. While they needed a remote interface, we needed a reliable datastore so we made the projects depend on each other.

Regards,
Michal
