### ISSUE TITLE
control of advertised capabilities in hello message

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libnetconf2#129]
Hi!

I was wondering if it is possible to control the different capabilities which are available per session. For example, if a particular user is not eligible to use a particular capability maybe it shouldn't even be communicated in the hello message?

Also, if I make custom internal models, can I "hide" it from the outside? Again, something that should be only usable by an internal program. Right now, as far I as can tell the hello message is constructed automatically from the available capabilities.

Thanks for the help!

**Comment by michalvasko** [comment]
Hi,
no, it is not currently possible. But, I guess, we would accept a patch that would nicely implement this functionality.

Regards,
Michal
