### ISSUE TITLE
compilation errors ubuntu

### ISSUE THREAD

**Issue by Muna24** [CESNET/libnetconf2#130]
After I run "make" I receive these errors. 
[ 55%] Built target netconf2
[ 55%] Built target testobj
[ 55%] Linking C executable test_init_destroy_server
CMakeFiles/testobj.dir/__/src/session.c.o: In function `nc_ssh_init':
/home/mouna/libnetconf2/libnetconf2/src/session.c:1361: undefined reference to `ssh_threads_get_pthread'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_init_destroy_server.dir/build.make:124: recipe for target 'tests/test_init_destroy_server' failed
make[2]: *** [tests/test_init_destroy_server] Error 1
CMakeFiles/Makefile2:209: recipe for target 'tests/CMakeFiles/test_init_destroy_server.dir/all' failed
make[1]: *** [tests/CMakeFiles/test_init_destroy_server.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Does anyone know how I can solve them

**Comment by michalvasko** [comment]
Hi,
what Ubuntu version are you on? What is the version of `libssh` you have installed?

Regards,
Michal

**Comment by Muna24** [comment]
I am using ubuntu 18.04

I fixed the problem. I had libssh 0.8.0. I used a newer version and it worked fine
Thank you
