### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by Meziden** [CESNET/libnetconf2#132]
I was trying to use the following makefile to compile a simple program on Ubuntu18.04, but some problems show up when linking the program.
```makefile
CFLAGS  = `pkg-config --cflags libnetconf2`
LIBS    = `pkg-config --libs libnetconf2`

main : main.o
	g++ main.o -o main ${LIBS}
main.o : main.cpp
	g++ -c main.cpp -o main.o ${CFLAGS}
```
Hers's the output from make:
```
main.o：In function ‘main’:
/home/tinker/NETCONF/testserver/main.cpp:23：undefined symbol ‘nc_server_init(ly_ctx*)’
/home/tinker/NETCONF/testserver/main.cpp:26：undefined symbol ‘nc_server_set_capab_withdefaults(NC_WITHDEFAULTS_MODE, int)’
/home/tinker/NETCONF/testserver/main.cpp:31：undefined symbol ‘nc_server_destroy()’
collect2: error: ld returned 1 exit status
```
The pkg-config output:
```
tinker@ELAR-Systems:~$ pkg-config --cflags --libs libnetconf2 libyang
-I/usr/local/include -L/usr/local/lib -lnetconf2 -lyang
```
The cmake installation of netopeer2 works well without such problem.
Is there any additional flags need to be set to link the program properly?

**Comment by michalvasko** [comment]
Hi,
there were several missing C++ macros in the public headers, it should work now.

Regards,
Michal

**Comment by Meziden** [comment]
Everything works now.

Thanks buddy.
