### ISSUE TITLE
error: 'SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES' undeclared (first use in this function)

### ISSUE THREAD

**Issue by mislavn** [CESNET/libnetconf2#133]
Hi,

on the latest ubuntu image I'm getting the error:
```
/opt/dev/libnetconf2/src/session_client_ssh.c:1677:49: error: 'SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES' undeclared (first use in this function); did you mean 'SSH_OPTIONS_KEY_EXCHANGE'?
     ssh_options_set(session->ti.libssh.session, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, "ssh-ed25519,ecdsa-sha2-nistp256,"
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                 SSH_OPTIONS_KEY_EXCHANGE
/opt/dev/libnetconf2/src/session_client_ssh.c:1677:49: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/netconf2.dir/src/session_client_ssh.c.o] Error 1
```

If I replace `SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES` with `SSH_OPTIONS_KEY_EXCHANGE` libnetconf2 compiles.

Is this correct, should I make pull request?

**Comment by michalvasko** [comment]
Hi,
it was most likely added in some recent `libssh` version, what version have you installed on that image?

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

`libssh-dev` in Ubuntu is currently at `0.8.0`.

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi Mislav,
it should compile now with older `libssh` versions, I hope.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

it worked. Thanks.

Regards,
Mislav
