### ISSUE TITLE
nc_server_get_cpblts_version() skips Yang 1.1 schemas

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libnetconf2#135]
Hi!

Is there a particular reason that the nc_server_get_cpblts_version() function skips Yang
1.1 schemas?

I added my modules to the ly context, and some of them appeared, some of them didn't in the hello message. Apparently the reason was that some of them were Yang 1.1 schemas.

Maybe there is another way to add 1.1 schemas to the hello message?

Thanks!

**Comment by michalvasko** [comment]
Hi,
YANG 1.1 uses a [different mechanism](https://tools.ietf.org/html/rfc7950#section-5.6.4) for advertising the schemas it supports.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the quick response!
