### ISSUE TITLE
When physical link is down(for example:the network cable is pull out by people) ,how to detect broken timely?

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [CESNET/libnetconf2#136]
When physical link is down(for example:the network cable is pull out by people) ,how to detect broken timely?

**Comment by michalvasko** [comment]
Hi,
there should be keep-alive enabled so it should be detected reasonably fast, is your experience different?

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
that is a lot, what exactly is your use-case (normal session, Call Home, ...)? What platform are you on? The exact values are set in `session.c:nc_sock_enable_keepalive()`.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
We use normal ssh session.
I have looked up my  used  libnetconf2 code ,it does not have this function. May be this is because the code  we used is too old.
thanks
