### ISSUE TITLE
Query : Support of different yang version of ietf-netconf-acm yang

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/libnetconf2#138]
Hi,

 I have implemented netconf client using  libnetconf2-0.11-r1 library that uses ietf-netconf-acm@2012-02-22.yang and using netconf server of different party who is supporting ietf-netconf-acm@2018-02-14.yang.

We are observing a problem that when netconf server creates a netconf session with netconf client , netconf-client give errors:
"Module "ietf-netconf-acm@2018-02-14.yang" is supposed to be imported, but no other module imports it.".

Query: 
if I upgrade  libnetconf2-0.11-r1  supporting  ietf-netconf-acm@2018-02-14.yang  in netconf-client .
Will it be compatible with netconf-server who is supporting old  ietf-netconf-acm@2012-02-22.yang ?

**Comment by michalvasko** [comment]
Hi,
as this is an internal module and is always implemented, you must always use one specific revision of the module in applications communicating with each other using NETCONF.

Regards,
Michal
