### ISSUE TITLE
Using libyang::Data_Node as data in nc_rpc_edit

### ISSUE THREAD

**Issue by syyyr** [CESNET/libnetconf2#141]
Hello,
I'm creating a function that creates edit-config RPCs to set values of arbitrary leaves. 
```
void setLeaf(const char* pathToLeaf, const char* value)
```
The function works like this: firstly, I use the ```path``` argument and ```value``` argument to create a ```libyang::Data_Node``` instance using this constructor:
```
Data_Node (S_Context context, const char *path, const char *value, LYD_ANYDATA_VALUETYPE value_type, int options)
```
Next, I use the ```print_mem``` member function to print the data tree and finally I supply the return value to the ```nc_rpc_edit``` function.
The whole code looks like this (```m_context``` is a ```libyang::Context``` variable with all the needed YANG modules loaded):
```
auto node = std::make_shared<libyang::Data_Node>(m_context, path, value, LYD_ANYDATA_CONSTSTRING, 0);
nc_rpc_edit(NC_DATASTORE_RUNNING, NC_RPC_EDIT_DFLTOP_MERGE, NC_RPC_EDIT_TESTOPT_TESTSET, NC_RPC_EDIT_ERROPT_STOP, node->print_mem(LYD_XML, 0), NC_PARAMTYPE_CONST);
```
Is this a good way to create edit-config RPCs or should I use a different method? Are there any edge cases I should know about?

cc @jktjkt

**Comment by michalvasko** [comment]
Hi,
it seems fine to me and should do what you want it to. I would just be careful about the `pathToLeaf` argument. If the target leaf is nested in a list, the parent list instance must include keys. Also, if any parents of the leaf do not exist, they will be created as well.

Regards,
Michal

**Comment by syyyr** [comment]
Thanks for the answer.
