### ISSUE TITLE
Query : Namespace in Create-subscription RPC of type=XPATH

### ISSUE THREAD

**Issue by Arkintos** [CESNET/libnetconf2#142]
Hi,

I am trying to include name space in type=XPATH of create-subscription RPC and am expecting an output as shown in the below image. 

![create_subscription](https://user-images.githubusercontent.com/5982894/54588468-19f40000-4a49-11e9-841f-ef8c338f773e.png)

However, I am not able to add the namespace in create-subscription rpc of type=XPATH and am getting the following output (I have developed netconf client using libnetconf2-0.11-r1 library).

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <filter type="xpath" select="/hardware-state-oper-enabled|/hardware-state-oper-disabled|/alarm-notif[fault-id=1orfault-id=2orfault-id=3orfault-id=4orfault-id=9orfault-id=19]"/>
  </create-subscription>
</rpc>
```

Could you please suggest

Thanks,
Akhilesh

**Comment by michalvasko** [comment]
Hi Akhilesh,
as written in the documentation, when you are creating the RPC using `nc_rpc_subscribe()`, you should use JSON prefixes in the filter (meaning module names). Or are you creating the RPC some other way?

Regards,
Michal

**Comment by Arkintos** [comment]
thanks michal,
I added prefixes in the filter and it worked.
