### ISSUE TITLE
Query: Detecting socket errror/closed in netconf session

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/libnetconf2#143]
Hi,
I am using libnetconf2 to implement netconf client .
my requirement is:
1) detecting socket error/closed in netconf session 
2) try to create new netconf session 
is there any API to check socket error/closed in netconf session?

**Comment by michalvasko** [comment]
Hi,
1. There is no API but these situation should be detected using keep-alive packets that are enabled by default.
2. There a few functions for that but you probably want `nc_connect_ssh()`.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
keep-alive options has been opened by default?

**Comment by michalvasko** [comment]
Hi,
yeah, it should be if you use a fairly recent version of *libnetconf2*.

Regards,
Michal
