### ISSUE TITLE
Is it better to add err_path in nc_err_libyang when case is LYVE_NOCONSTR,LYVE_NOWHEN and default

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [CESNET/libnetconf2#144]
Is it better to add err_path in nc_err_libyang when case is LYVE_NOMUST, LYVE_NOCONSTR,LYVE_NOWHEN and default

**Comment by michalvasko** [comment]
Hi,
no reason not to, thanks.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
@michalvasko 
Hi, i think it is reasonable,as an api in messages_server.h ,the function should construct complete error msg it knows not partly .

Consider the err msg as below, when user config-data is not fit the pattern,it does not contains the error path. So ,the user do not know which leaf is error, it can not fix the  errors.
-------------------------------------------------------------------------
	type:     protocol
	tag:      invalid-value
	severity: error
	message:  Value "ad10" does not satisfy the constraint "[A-Z_0-9]*" (range, length, or pattern).

**Comment by michalvasko** [comment]
Hi,
I am now a bit confused, have you tried it with the most recent *libnetconf2* `devel`? Because I have made the change you suggested and it should even be seen in the *netopeer2-cli* output even though you only mentioned it just now.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
> Hi,
> I am now a bit confused, have you tried it with the most recent _libnetconf2_ `devel`? Because I have made the change you suggested and it should even be seen in the _netopeer2-cli_ output even though you only mentioned it just now.
> 
> Regards,
> Michal

Thanks 
It is my problem.
Sorry for my poor English ,i just think we do not need do this for understanding  the first reply , .

**Comment by michalvasko** [comment]
Hi,
I have added the `path` for *libyang* errors `LYVE_NOMUST`, `LYVE_NOCONSTR`, and `LYVE_NOWHEN` to be stored in *libnetconf2* error structure because I thought that is what you wanted. Did you want something else?

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
No
Thanks
