### ISSUE TITLE
bug in  API nc_server_ssh_del_authkey 

### ISSUE THREAD

**Issue by LeviZ2z** [CESNET/libnetconf2#145]
In file session_server_ssh.c
![image](https://user-images.githubusercontent.com/49012690/55128460-9a53e880-514e-11e9-8e71-f4fe0c452491.png) here should be    !strcmp(server_opts.authkeys[i].base64, pubkey_base64)  only this can delete the key successfully. Looking forward for your reply.

**Comment by michalvasko** [comment]
Hi,
obviously, thanks. Fixed now except I referenced the issue number from before and I have noticed you created the issue in *libnetconf* instead of *libnetconf2* just now.

Regards,
Michal

**Comment by LeviZ2z** [comment]
sry，I create the isuue in the wrong place. Thanks for your prompt attention.

**Comment by LeviZ2z** [comment]
> Hi,
> obviously, thanks. Fixed now except I referenced the issue number from before and I have noticed you created the issue in _libnetconf_ instead of _libnetconf2_ just now.
> 
> Regards,
> Michal

sry， I creat the issue in the wrong place. Thanks for your prompt attention.
