### ISSUE TITLE
The rpc-reply element tag is not always in the correct namespace

### ISSUE THREAD

**Issue by p-jean** [CESNET/libnetconf2#15]
**Summary:**
If the client uses a prefix for the NETCONF namespace then the rpc-reply element tag is not in the NETCONF namespace

**Details:**
The Python library ncclient sends an rpc beginning as follows. Note that there is an 'nc' prefix on the rpc tag:
`<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b9e28b4b-6bf2-4606-9e5a-9bc08074d609"><nc:edit-config>`

The reply from libnetconf2 is as follows:
`<rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b9e28b4b-6bf2-4606-9e5a-9bc08074d609"><ok/></rpc-reply>`

Note that there is no 'nc' prefix on the rpc-reply tag. The response is not recognized and ncclient times out. I believe that it is because the rpc-reply element tag is not in the NETCONF namespace.

I think that the correct response would need to have a prefix on the rpc-reply tag:
`<nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"`

NETCONF seems to require that the rpc attributes are echoed back verbatim.

I made an attempt to fix it, however I don't suppose my change is very clean. I have done limited testing so far, but I was able to get further with ncclient.

Thanks
[fix_reply_namespace .patch.txt](https://github.com/CESNET/libnetconf2/files/579122/fix_reply_namespace.patch.txt)

**Comment by michalvasko** [comment]
Hi,
it should be fixed, thanks for the patch.

Regards,
Michal

**Comment by p-jean** [comment]
Hi Michal,

Thanks for the great libraries.

BTW - is there any sort of forum or place online to discuss libyang,
libnetconf2, or Netopeer2?

..PJ

On Tue, Nov 15, 2016, at 02:06 AM, michalvasko wrote:
> Hi,
>  it should be fixed, thanks for the patch.
> Regards,
>  Michal
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/CESNET/libnetconf2/issues/15#issuecomment-260599717

**Comment by rkrejci** [comment]
Hi PJ,
we use mainly the github issue trackers for the projects, but there are also [mailing lists](http://lists.sysrepo.org/listinfo) of [sysrepo](http://www.sysrepo.org/) which is closely connected with the Netopeer2, so you can discuss the general things there.

Regards,
Radek
