### ISSUE TITLE
Issue in cleanup for a session authenticated but not established

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libnetconf2#151]
Hi Michal,

I am working with libnetconf2 version 0.12.44. Came across a scenario where the client tries to connect with Netconf server but didn't exchange the hello messages after successful ssh authentication resulting in non-establishment of the session. The np2srv.nc_ps structure also shows the current session count to be 0.
Instead of using netconf client, made the below ssh call to connect:
`ssh user@127.0.0.1 -p 830 -s netconf`

My issue is that I have registered my callback function with nc_server_ssh_set_passwd_auth_clb API to authenticate the password and allocated some resources to store the username, password, host. etc. details of the client creating the connection. But due to hello message timeout (timeout set to 10 mins) and unsuccessful session establishment, these resources are not freed up, hence the memory is blocked.

Tried registering for free_user_data callback in the aforementioned API but doesn't seem to get invoked if there in any failure in password authentication or if cleanup is performed. Can you tell me it's usage and scenarios where the free_user_data callback registered gets invoked. Also, is there any library API supporting callback that could be helpful in the above mentioned scenario of leaking resources. Or, is there any support in later versions of the library for handling such leaking scenarios. If yes, I might consider upgrading to that version. If incase no then will there be any support in near future.

**Comment by michalvasko** [comment]
Hi,
the `free_user_data` callback should be called during `nc_server_destroy()` so it is independent of sessions that were created or failed during any stage of session creation. But you must be careful when setting the user data, you may be overwriting some old data and thus causing the leaks yourself.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Hi Michal,

Thanks for the response.

As told you earlier, in my case the free_user_data callback didn't get hit. Again tried executing the same scenario and applied gdb on the same callback function and ran through the above mentioned steps.

At the client end, received the capabilities sent by the server and connection got closed as the enter key was hit. Here are the last line traces captured at client end:

```
</capability></capabilities><session-id>1</session-id></hello>]]>]]>
Connection to 127.0.0.1 closed by remote host.
hostname~]$
```
This is the way I have registered my callback, hope this is fine.
`nc_server_ssh_set_passwd_auth_clb(default_passwd_auth_clb, NULL, default_free_user_data_clb);`

While session timeout is specified like this:
```
nc_server_set_idle_timeout(180);
nc_server_set_hello_timeout(180);
```
Note: I am using the Netopeer2 server code for my Netconf server application.

**Comment by michalvasko** [comment]
Hi,
I am a bit confused now, you are calling `nc_server_ssh_set_passwd_auth_clb(default_passwd_auth_clb, NULL, default_free_user_data_clb);` somewhere in the original *netopeer2-server* code?

Regards,
Michal

**Comment by amandeepsethi** [comment]
Hi,
I showed the way as to how I am registering the two callbacks in my code. Was verifying if is correct?

The `default_passwd_auth_clb` gets called up successfully when there is authentication of credentials of user connecting to Netconf server. But the later callback function i.e. `default_free_user_data_clb` doesn't get called up even when the connection has not established due to timeout of hello message. So there is no cleanup of resources leading to leak. Ideally as per your inputs, should have been called.

**Comment by michalvasko** [comment]
Hi,
so I take it as a **yes** being the answer to my question. In that case, *netopeer2-server* calls `nc_server_destroy()` (that calls your freeing function) just before terminating, not during normal operation. These user data were not meant to be used the way you are using them (e.g. storing some session-specific context) but it can work fine provided you expect the data you set there before to be there as long as *netopeer2-server* is running (I mentioned this 2 replies before).

Regards,
Michal

**Comment by amandeepsethi** [comment]
Hi,
I tried the scenario again with gdb on the exe and applied breakpoint on nc_server_destroy function and my free_user_data callback function. Waited for 3 mins as per above mentioned session and hello timeout value, but none of the both got hit.

**Comment by amandeepsethi** [comment]
Hi,
Agreed as per current code, nc_server_destroy() gets called when server terminates but this doesn't seem apt for a real field scenario where to save leaking resources, the server is killed.

Is there any alternate solution to free resources allocated in `default_passwd_auth_clb` API, incase the session is not established?

**Comment by mohitarora24** [comment]
I suppose the problem statement is something like:

```
my_passwd_auth_clb(nc_session, ....)
{
  // get password & authenticate user.
  add_internal_session_data(nc_session, username, pass, hostinfo, etc);
}

main()
{
  nc_server_ssh_set_passwd_auth_clb(my_passwd_auth_clb, NULL, NULL);
  server_loop();
}

server_loop()
{
  while(TRUE)
  {
    msgtype = nc_accept(0, &ncs);
    if (msgtype == NC_MSG_HELLO) {
      nc_ps_add_session(nc_ps, ncs);
    }
    rc = nc_ps_poll(nc_ps, 0, &ncs);
    if (rc & NC_PSPOLL_SESSION_TERM)
    {
      delete_internal_session_data(ncs);
      nc_ps_del_session(nc_ps, ncs);
      nc_session_free(ncs);
    }
  }
}
```

Whenever SSH authentication completes, some internal application data is stored via `my_passwd_auth_clb()`.
Now on a successful Netconf HELLO handshake, the session is added to `pollsession`.
And when session terminates, it is cleaned up as well as authentication information is cleaned up by calling `delete_internal_session_data()`. But in the case of bad HELLO message or HELLO timeout, there is no way to clean up the extra information which was stored during successful SSH auth.

It is not desired that the stale information be cleared only when Netconf server is destroyed. There should be some interface for callback API which should be triggered in such cases or everytime inside nc_session_free(). Something like that...

**Comment by michalvasko** [comment]
Hi,
I am saying this for the 3rd time, the user data are not freed when the session is terminated/freed because these data are not connected to specific sessions, they are simply one global structure for the whole server. I anticipated their purpose to be storing some context that allows for authentication of all the sessions, again, nothing session-specific. That is why it is freed only once the server terminates.

What if someone used it the way I described and the context would get freed after a session terminates, for example? It would have to be constantly created. The current approach is the safer one and as you can see, the way you have used it has a problem of resource leaks when sessions are not successfully established. That is a problem of your solution, not the user data mechanism.

Lastly, I am not sure why would you even need to store some session-specific information, everything relevant is already stored in the NETCONF session and can be read from it (username, host, port, ...).

Regards,
Michal

**Comment by mohitarora24** [comment]
1) The user data you're referring to (which gets cleaned up on server end) is not applicable to us. I don't mind that added functionality for any person who needs it but it's not useful to us.

2) We need to store session-specific information as:
  a) We use PAM based authentication and when `server_opts.passwd_auth_clb` is called, PAM database is updated with a new session information. And it only gets cleaned up when the session returns error after `nc_ps_poll`. Could you tell us a way to clear the PAM DB of that entry when HELLO exchange fails?
 b) Our application does not only use NETCONF. We've other interfaces like CLI, RESTConf, etc and we need centralized session management. So information stored with NETCONF session is okay but we really need more control via a centralized database for which libnetconf2 is not enough.

**Comment by michalvasko** [comment]
Hi Mohit,

2. It is difficult for me to suggest specific solution since I do not know the details of your implementation but I can try. You are already modifying *netopeer2-server* code (setting your password callback) so why not just set the callback and not store any user data. Then, only once the session is successfully established, store whatever information you want wherever you want. In concrete terms, store information in `np2srv_new_session_clb()` and free it in `np2srv_del_session_clb()` (if one is called, the other one should also always be called).

Regards,
Michal

**Comment by amandeepsethi** [comment]
Thanks Michal for the response.

As specified earlier, we have certain PAM related resources that gets allocated at time of authentication callback only. So, was looking for a solution (maybe a callback function) that can free-up these resources if session establishment was a failure when processed later. Otherwise, we are already freeing up these resources in `np2srv_del_session_clb` if session establishment was a success.

From your response, it seems, we don't have a feasible solution in current library code, according to our scenario. Will do more digging in the library code to see, if we can find one.

Thanks again for your active looking into the issue and providing timely responses.

Regards,
Amandeep Singh Sethi

**Comment by michalvasko** [comment]
Hi,
I see, then what you can also do is tie the data explicitly with a NETCONF session (set it using `nc_session_set_data()`). However, *netopeer2-server* already uses this mechanism for some data, so you could add your data into the existing structure. If you then add freeing it to the existing function (`free_ds()`), it should get freed in every case.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Thanks Michal for the providing the solution.

We have achieved the same by making a new callback function and registering in the `server_init` API. This customised function free-up the allocated resources and gets invoked from `nc_session_free` API which even gets called when the handshake process has not completed. The solution is working for us.

Regards
Amandeep Singh Sethi
