### ISSUE TITLE
Cannot ignore wrong message ids after rpc recv

### ISSUE THREAD

**Issue by olivier-matz-6wind** [CESNET/libnetconf2#156]
Hi,

Here is my use-case:

- create a rpc with `nc_rpc_act_generic()`
- send it with `nc_send_rpc()`
- wait the answer with `nc_recv_reply()` -> timeout, the message is not dequeued

- create another rpc, from another yang module, with `nc_rpc_act_generic()`
- send it with `nc_send_rpc()`
- wait the answer with `nc_recv_reply()`: return `NC_MSG_ERROR` instead of `NC_MSG_REPLY_ERR_MSGID`

In `get_msg()`, the following log is issued, which is expected:
`Session 5: received a <rpc-reply> with an unexpected message-id "140"`

Despite the `msgtype` returned by `get_msg()` is `NC_MSG_REPLY_ERR_MSGID`, the `parse_reply()` function is called (it looks it was done on purpose in commit 71ba2daba1b1). Then, in `parse_reply()`, we fall in the following code:

```
    data_rpl->data = lyd_parse_xml(ctx, &xml->child, LYD_OPT_RPCREPLY | LYD_OPT_DESTRUCT | parseroptions,
                                rpc_act, NULL);
    if (!ly_errno && !data_rpl->data->child) {
	ERR("An empty data <rpc-reply>.");
	lyd_free_withsiblings(rpc_act);
        lyd_free(data_rpl->data);
        free(data_rpl);
        return NULL;
    }

```

The `rpc_act` does not match the `xml` answer, so `data_rpl->data->child == NULL`. Therefore, the log is issued and `nc_recv_reply()` returns `NC_MSG_ERROR` instead of `NC_MSG_REPLY_ERR_MSGID`.

In my code, I would like to ignore messages with a bad id, as it's done in Netopeer cli. But in that case it does not work. Do you have any suggestion? Side question: should the log `"received a <rpc-reply> with an unexpected message-id X"` really be an error-level one?

Thanks in advance
Olivier

**Comment by olivier-matz-6wind** [comment]
After thinking more about it, I think I have a workaround in my application. I can maintain a list of unanswered rpc requests, and before sending a new request, flush the message queue with `nc_recv_reply()`, using the proper `rpc` and `msgid`. Any better solution is still welcome ;)

**Comment by michalvasko** [comment]
Hi,
> The rpc_act does not match the xml answer, so data_rpl->data->child == NULL.

I think the reply was parsed just to check for some other errors, but you have a good point, it is most often completely redundant so it will no longer be parsed.

But for your actual issue, I think it should be kept the way it is. Unexpected `message-id` is simply an error, the RPC replies [must be serialized](https://tools.ietf.org/html/rfc6241#section-4.5).

Regards,
Michal

**Comment by olivier-matz-6wind** [comment]
Thanks @michalvasko.
I'm closing the issue.
