### ISSUE TITLE
poll return pollin, but read return EAGIN，then  report the error: "Session %u: inactive read timeout elapsed."

### ISSUE THREAD

**Issue by lumanyu180** [CESNET/libnetconf2#163]
Hi, 
     I have a netconf server with libnetconf2, and a netconf client（it does not using libnetconf2). They communicate over tcp。I enter a error. The client send hello packet and send nothing after that。20s later, The server report the error:  "Session %u: inactive read timeout elapsed."  The session is termanited by the server。I do not understand ,why the client does not send any packets. But the server still need to read ？。 I try to print the POLL's return value. The pfd.revents is 1 (POLLIN)。Thank you very much.

**Comment by lumanyu180** [comment]
Hi,
     I am more anxious， Expect to get your answer. Thanks very much.

**Comment by michalvasko** [comment]
Hi,
sorry, I was on a vacation. Anyway, this will be a problem of the client, it does not terminate the messages correctly. If you are using `ssh(1)` as the client, for example, I think you cannot avoid this, so do not use it.

Regards,
Michal

**Comment by lumanyu180** [comment]
Hi,
   thanks for your reply。The client does not use ssh, it is over tcp。And  I'm sure it send hello packet with endtag。So i don't know why。

**Comment by michalvasko** [comment]
Hi,
try to use another client, this one probably sends an extra `\n` or something similar at the end of a NETCONF message so *libnetconf2* thinks it is a start of another message. When no following data is received for too long, the "inactive read timeout" elapses.

Regards,
Michal

**Comment by lumanyu180** [comment]
Hi,

thanks for your reply. I understand your reply. I think i should capture the client's packet to see if he send something at the end of a NETCONF message。
