### ISSUE TITLE
How to implement callhome feature using libnetconf2.

### ISSUE THREAD

**Issue by vishalearnz** [CESNET/libnetconf2#166]
Hi,

I want to implement callhome feature from my server (NOT NETOPEER) . Can you please tell me how can I implement it . I mean algorithm to be used . 
I have see the confd(provided by cisco) way of working , where we just need to add socket, port and ip with an api . But while going through the libnetconf2 api's I could not get , what to use as it needs the client name. Can you pl enlighten me on the procedure to be followed to implement callhome.

Thanks

**Comment by michalvasko** [comment]
Hi,
just look at [netopeer2 implementation](https://github.com/CESNET/Netopeer2/blob/master/server/ietf_netconf_server.c#L853), it just applies values modeled in [ietf-netconf-server](https://github.com/CESNET/Netopeer2/blob/master/modules/ietf-netconf-server.yang#L227). I think the API is quite simple to use, actually. The clients and endpoints just need to be organized so you need to set some arbitrary names for them (required by the YANG model).

Regards,
Michal

**Comment by vishalearnz** [comment]
Hi michal,

I went through the implementation of netopeer2 , I implemented that on my application  using following steps:
1. Add client
2. Add end point
3. Set endpoint address as host address
4. Set port as port where application is running
5. Set the connection type as persistent.
6 connect callhome client.

Through the callhome is able to ping the client ip (used netconf console to verify it) , but its unable is actually connect and do a handshake . 

I tried opendaylight server to check the callhome feature where in odl server was running. Then first used a PUT request via postman 
{
  "device": {
    "unique-id": "NodeCallHome2",
    "credentials": {
      "username": "xyz",
      "passwords": [ "123" ]
    },
    "ssh-host-key": "ABCCDB3NzaC1yc2EAAAABIwAAAQEAv4Wv+6+vbnd3OGb0bjfdODCDNeFMaP4oqY1NftDP8jCWNI0KNWuaVuSuNL/weyyEdQ0851YrkiE9/jQ+vDtFLxcY//wY97cHyYkM6gBos7tTwCBiRfTlmFHL8G+9pneUJPZVwRyiCi6XANt1xRMNfrFTYpfJWLl3GrFcUEnGz7JhKSSIaxbYuaRweSUQS0rY/t4rE7r3cUSxNBZ+KxLMhS9Dsoycw+S4ZrtKaGmczXsecZbiTOTfqogtZKxntSDGdJYl9qtpT9PbeYBTn6/8EF7Awfi46x7u+Pek1UvEgPZSop8SEV9x2z1eZfu/rHrgPPlP3PugkEsXabjrWv4y76=="
  }
} 
and then used a get for call home . If the callhome is active the status should say CONNECTED , but its showing everytime DISCONNECTED , meaning its unable to connect to callhome.

I added the following to my code  
nc_server_ssh_ch_client_set_auth_methods(client_name,NC_SSH_AUTH_PUBLICKEY);
nc_server_ssh_ch_client_add_hostkey( client_name, "ssh_host_dsa_key", -1);


Can you please help me on this , if there is anything I might be missing , or anything I may be doing wrong. 

Thanks & Regards,
Vishal

**Comment by michalvasko** [comment]
Hi Vishal,
have you tried to print some *libnetconf2* messages? Just based on you wrote I would say you are missing a callback that would actually retrieve the `ssh_host_dsa_key`. You can set it using [nc_server_ssh_set_hostkey_clb](https://github.com/CESNET/libnetconf2/blob/master/src/session_server.h#L571). Then, to actually use `publickey` SSH authentication you need to set some authorized keys (*libnetconf2* should definitely inform about this) by either [this](https://github.com/CESNET/libnetconf2/blob/master/src/session_server.h#L487) or [this](https://github.com/CESNET/libnetconf2/blob/master/src/session_server.h#L497) function.

Regards,
Michal

**Comment by vishalearnz** [comment]
Thanks for the explanation michal . But the nc_server_ssh_set_hostkey_clb  I had already set as a part of server initialization , with the private key path provided to the callback. So the direct login to the server works. 
Apart from this , I tried to use to use the function to set the public key as suggested by you, but still the callhome did not work.
As my libnetconf2 was older (12.27) , so a file nc_server_ch.h was not present . I am presently updating it and will try to use api of setting endpoint host key, previously I was using the api of hostkey setting with client name (nc_server_ssh_ch_client_add_hostkey).

Can you pl tell me if this can work?

**Comment by michalvasko** [comment]
Hi,
the function [nc_server_ssh_ch_client_add_hostkey](https://github.com/CESNET/libnetconf2/blob/master/src/session_server_ch.h#L206) is present in the latest version and you have to call that, as well, so it should work. Like I said before, set some *libnetconf2* verbosity and look at the messages, they should tell you what is wrong.

Regards,
Michal

**Comment by vishalearnz** [comment]
Hi Michal,

The function nc_server_ssh_ch_client_add_hostkey  , I was already using to set the host_key . 
Following is the code added:

nc_server_ssh_ch_client_add_hostkey(client_name, "ssh_key", -1);
nc_server_ssh_ch_client_set_auth_methods(client_name, NC_SSH_AUTH_PUBLICKEY);
nc_server_ssh_add_authkey_path("xyz/key.pub", "admin");

And as you suggested I set the verbosity to full and checked the logs .
Following is the message received:
SSH key exchange error (Received SSH_MSG_DISCONNECT: 9:Server key did not validate).

Then I thought its the issue of public private key pair , so I generated it again using ssh-keygen , and tried with both rsa and dsa using sshkeygen -t rsa and sshkeygen -t dsa.
Following is the error coming up repeatedly:
LIBNETCONF : Received an SSH message "request-service" of subtype "ssh-userauth".
LIBNETCONF : Received an SSH message "request-auth" of subtype "none".
LIBNETCONF : Received an SSH message "request-auth" of subtype "publickey"
LIBNETCONF : User "dmin" tried to use an unknown (unauthorized) public key.
LIBNETCONF : Failed user "admin" authentication attempt (#1)
LIBNETCONF : Received an SSH message "request-auth" of subtype "publickey".
LIBNETCONF : User "secadmin" tried to use an unknown (unauthorized) public key.
LIBNETCONF : Failed user "secadmin" authentication attempt (#2).

Can you pl check if above one can tell what is going wrong

Regards,
Vishal

**Comment by michalvasko** [comment]
Hi Vishal,
okay, the output is helpful but did you modify it prior to putting here? Because I can see some inconsistent user names printed (`dmin`, `admin`, `secadmin`). You added the authorized SSH key only for `admin` so that is the only user that can authenticate with it.

Regards,
Michal

**Comment by vishalearnz** [comment]
yeah michal , I had edited the user name prior to posting , its secadmin throughout. I edited for some reasons, but only the user name

**Comment by michalvasko** [comment]
Okay, so you must set key for `secadmin` using `nc_server_ssh_add_authkey_path()` and then login as `secadmin` user, if you have not already. It should work then.

Regards,
Michal

**Comment by vishalearnz** [comment]
I am using the nc_server_ssh_add_authkey_path for user secadmin only 
as mentioned below
 nc_server_ssh_add_authkey_path("...xyzpath/key.pub", "secadmin");

But still I am unable to do a callhome.

**Comment by michalvasko** [comment]
Fine, then please post **unaltered** *libnetconf2* output.

Regards,
Michal

**Comment by vishalearnz** [comment]
When I don't send any request following are the logs which comes up repeatedly :
**LIBNETCONF : SSH key exchange error (Received SSH_MSG_DISCONNECT: 9:Server key did not validate).
Inside hostkey_clb
LIBNETCONF : nc_sock_connect(10.220.82.13, 6666, 5, -1)
LIBNETCONF : Trying to connect via IPv4.
LIBNETCONF : Successfully connected to 10.220.82.13:6666 over IPv4.
Inside hostkey_clb 
LIBNETCONF : SSH key exchange error (Received SSH_MSG_DISCONNECT: 9:Server key did not validate).**


"Inside hostkey_clb" - Added logs by me . Which shows that the callback which is registered for the hosthey  set by "nc_server_ssh_set_hostkey_clb" gets called repeatedly .

Here the port(6666) refers to opendaylight server . Open daylight server is already running .

When a request PUT request is sent with body

**{
  "device": {
    "unique-id": "NodeCallHome3",
    "credentials": {
      "username": "secadmin",
      "passwords": [ "x123" ]
    },
    "ssh-host-key": "AAACB3NzaC1kc3MBAACBALzWhRQsEIjGJDhJw8uD5WfO/Xn5CjCIXqJhj8l3aq7ZDE+jxVOHfMTM4nOOPPKEJQm8YI36mcKy/Gp6DxvLVAHsXhNGRxEcW+cXFqI6vedLmTC0xZ8YQvECqbMkOTTrCTJiCDj1PObvALQUxfx6aFEdqQVzExACw4sgkdjgPTmJAAAAFQC3EMdM6xYaLsBLMT/jBTdVD9ByrwAAAIEAt4sS8Ggz2y6JqCFT/mi+tPXj0HZfgDMkBlQlC2JOxKUsS9D/olq5VrS0jYdipXIKkIaZkoDGfIJ0FVSR4pxSjL7rquVB/1s7zlcFGG9M5O3TGQ3AEv3Tb2JzOvtihpRLPKag5hxZn3XE9AxwQRnqmwgNg85U6zD30g/706STZOsAAACBAIR9vONXONFlmkh9ENhp2Q+prOLavhnZDnWVbPR6PWKT/tx47KpB6kZqDgAeBaawI7B7ZmufcWNZWccRDNSLuXXpKyN0wpALcFjeoNVCNLYIZGcKT+hnqo0sBYWqcDecaP6d14F94e6nmpIysK44QwV9xHGp5z3lNRyYO1rD43pI"
  }
}**
Following error gets displayed:

**LIBNETCONF : Received an SSH message "request-service" of subtype "ssh-userauth".
LIBNETCONF : Received an SSH message "request-auth" of subtype "none".
LIBNETCONF : Received an SSH message "request-auth" of subtype "publickey".
LIBNETCONF : User "secadmin" tried to use an unknown (unauthorized) public key.
LIBNETCONF : Failed user "secadmin" authentication attempt (#1).
LIBNETCONF : Received an SSH message "request-auth" of subtype "publickey".
LIBNETCONF : User "secadmin" tried to use an unknown (unauthorized) public key.
LIBNETCONF : Failed user "secadmin" authentication attempt (#2).
LIBNETCONF : Communication SSH socket unexpectedly closed.**

**Comment by michalvasko** [comment]
Hi,
so I got sidetracked, the current problem seems to be in the server host key. Based you your JSON output, it is possible your callback is not providing a correct key. I have encountered this problem before and it is mostly an annoyance but the key must include the newline character after every 64 key characters, just like in the file that is generated. It will not work is the key is on a single line.

Regards,
Michal

**Comment by vishalearnz** [comment]
Hi Michal,

Based on your suggestion . I tried to create request with changing public keys to have newline character after every 64 characters .

following are the request I tried with no luck

1. Inserted \n after every 64 characters

**{
  "device": {
    "unique-id": "NodeCallHome3",
    "credentials": {
      "username": "secadmin",
      "passwords": [ "x123" ]
    },
    "ssh-host-key": "AAAAB3NzaC1kc3MAAACBALzWhRQsEIjGJDhJw8uD5WfO/Xn5CjCIXqJhj8l3aq7Z\nDE+jxVOHfMTM4nOOPPKEJQm8YI36mcKy/Gp6DxvLVAHsXhNGRxEcW+cXFqI6vedLnmTC0xZ8YQvECqbMkOTTrCTJiCDj1PObvALQUxfx6aFEdqQVzExACw4sgkdjgPTmJ\nAAAAFQC3EMdM6xYaLsBLMT/jBTdVD9ByrwAAAIEAt4sS8Ggz2y6JqCFT/mi+tPXj\n0HZfgDMkBlQlC2JOxKUsS9D/olq5VrS0jYdipXIKkIaZkoDGfIJ0FVSR4pxSjL7r\nquVB/1s7zlcFGG9M5O3TGQ3AEv3Tb2JzOvtihpRLPKag5hxZn3XE9AxwQRnqmwgN\ng85U6zD30g/706STZOsAAACBAIR9vONXONFlmkh9ENhp2Q+prOLavhnZDnWVbPR6\nPWKT/tx47KpB6kZqDgAeBaawI7B7ZmufcWNZWccRDNSLuXXrKyN0wpALcFjeoNVC\nNLYIZGcKT+hnqo0sBYWqcDecaP6d14F94e6nmpIysK44QwV9xHGp5z3lNRyYO1rD\n43pIA"
  }
}**


error:
Inside hostkey_clb
LIBNETCONF : SSH key exchange error (Received SSH_MSG_DISCONNECT: 9:Server key did not validate).
LIBNETCONF : nc_sock_connect(10.220.82.13, 6666, 5, -1)
LIBNETCONF : Trying to connect via IPv4.
LIBNETCONF : Successfully connected to 10.220.82.13:6666 over IPv4.
Inside hostkey_clb 
LIBNETCONF : SSH key exchange error (Received SSH_MSG_DISCONNECT: 9:Server key did not validate)

response of get request from postman to the odl - DISCONNECTED

2. Hit enter after every 64 characters 

**{
  "device": {
    "unique-id": "NodeCallHome4",
    "credentials": {
      "username": "secadmin",
      "passwords": [ "x123" ]
    },
    "ssh-host-key": "AAAAB3NzaC1kc3MAAACBALzWhRQsEIjGJDhJw8uD5WfO/Xn5CjCIXqJhj8l3aq7Z
DE+jxVOHfMTM4nOOPPKEJQm8YI36mcKy/Gp6DxvLVAHsXhNGRxEcW+cXFqI6vedL
mTC0xZ8YQvECqbMkOTTrCTJiCDj1PObvALQUxfx6aFEdqQVzExACw4sgkdjgPTmJ
AAAAFQC3EMdM6xYaLsBLMT/jBTdVD9ByrwAAAIEAt4sS8Ggz2y6JqCFT/mi+tPXj
0HZfgDMkBlQlC2JOxKUsS9D/olq5VrS0jYdipXIKkIaZkoDGfIJ0FVSR4pxSjL7r
quVB/1s7zlcFGG9M5O3TGQ3AEv3Tb2JzOvtihpRLPKag5hxZn3XE9AxwQRnqmwgN
g85U6zD30g/706STZOsAAACBAIR9vONXONFlmkh9ENhp2Q+prOLavhnZDnWVbPR6
PWKT/tx47KpB6kZqDgAeBaawI7B7ZmufcWNZWccRDNSLuXXrKyN0wpALcFjeoNVC
NLYIZGcKT+hnqo0sBYWqcDecaP6d14F94e6nmpIysK44QwV9xHGp5z3lNRyYO1rD
43pI"
  }
}**

error:
Inside hostkey_clb
LIBNETCONF : SSH key exchange error (Received SSH_MSG_DISCONNECT: 9:Server key did not validate).
LIBNETCONF : nc_sock_connect(10.220.82.13, 6666, 5, -1)
LIBNETCONF : Trying to connect via IPv4.
LIBNETCONF : Successfully connected to 10.220.82.13:6666 over IPv4.
Inside hostkey_clb 
LIBNETCONF : SSH key exchange error (Received SSH_MSG_DISCONNECT: 9:Server key did not validate)

response of get request from postman to the odl - DISCONNECTED


So as per the response above . I think that using \n after 64 characters doesnot get recognized even by the server . If I directly give the public key(copy paste) to the request
AUTH FAILURE comes I.e at least server is able to recognize it. Even though it throws error which was mentioned in the above chat.


Can you pl see the request and tell me if I am doing the addition of \n 64 char correctly or as per what you stated?

Note that this time I again recreated public/private key pair and used the new one. Just to make sure I am not having an error related to public/private key
 
Thanks & Regards,
Vishal

**Comment by michalvasko** [comment]
Hi Vishal,
if I understand it correctly, your client did manage to authenticate the server so you know where the problem is, nothing more I can help with.

As for the failing public key authentication, I do not know what else to tell you except that it must be a problem of configuration, the authentication itself works. You can try to add some messages or use a debugger to look at what is happening in `session_server_ssh.c:nc_sshcb_auth_pubkey()`, it is the function that verifies client public keys. But there are quite a lot of messages already so I keep thinking the problem is what the library says, you are trying to use a private key, whose public key was not added as authorized (meaning you have non-matching private/public key pair).

Regards,
Michal

**Comment by vishalearnz** [comment]
Hi Michal,

Thanks for the help. 
I am now able to do the handshaking of callhome . The problem I found was the following:
instead of NC_SSH_AUTH_PUBLICKEY I gave NC_SSH_AUTH_PASSWORD as the auth type
nc_server_ssh_ch_client_set_auth_methods(client_name,NC_SSH_AUTH_PASSWORD)

Also I redirected the hostkey to take the private keys from the server which gets created at start i.e /etc/ssh path . And taken the public key of that one . So now from the postman If I send the PUT request , its able to recognize it and hits the callback which was set for "nc_connect_ch_client_dispatch". So the auth type "NC_SSH_AUTH_PUBLICKEY" doesnot work for me.

But I have moved into a next issue where once I send the callhome request from postman using PUT . For the Get request it still says DISCONNECTED. I have made the callback (nc_connect_ch_client_dispatch) to work just like login. i.e session id gets generated and set the session data using nc_session_set_data() and then use nc_ps_add_session(). 

Although in my console logs where I have set the verbosity of libnetconf logs to full shows no error but
In the opendaylight I can see the following error:

5:05:41.347 INFO [nioEventLoopGroup-4-91] Activating NETCONF channel for ip /10.220.82.74:49139 device context org.opendaylight.netconf.callhome.mount.CallHomeMountSessionContext@35555864
15:05:41.347 INFO [opendaylight-cluster-data-notification-dispatcher-637] Setting failed status for callhome device id:Uri{_value=NodeCallHome7}.
15:05:41.347 INFO [opendaylight-cluster-data-notification-dispatcher-646] Setting failed status for callhome device id:Uri{_value=NodeCallHome7}.
15:05:41.348 INFO [nioEventLoopGroup-4-91] Activating Netconf channel for /10.220.82.74:49139 with org.opendaylight.netconf.callhome.mount.CallHomeMountSessionContext$1@2d88165c
15:15:41.673 INFO [nioEventLoopGroup-4-92] Removing Uri{_value=NodeCallHome7} from Netconf Topology.
15:15:41.674 WARN [nioEventLoopGroup-4-92] RemoteDevice{NodeCallHome7}: Session terminated Session closed
15:15:41.676 INFO [nioEventLoopGroup-4-92] Removing Uri{_value=NodeCallHome7} from Netconf Topology.
 
Can you check and tell me why the callhome is not getting recognized?

I suspect that there should be a medium to tell the (opendaylight/external) means that callhome is successfull. If you think I may be correct , can you tell me which libnetconf function call I should use to make it work

**Comment by michalvasko** [comment]
Hi,
there is no special way "of telling that Call Home is successful", a NETCONF session is simply created. I have no idea what this Opendaylight client expects from the server. I would suggest you use `netopeer2-cli` to test your Call Home. I can help you with problems there and if that works but your scenario does not, most likely there is a problem in your client, not *libnetconf2*.

Regards,
Michal
