### ISSUE TITLE
nc_ssh_init() not called when both NC_ENABLED_SSH and NC_ENABLED_TLS defined

### ISSUE THREAD

**Issue by brchiu** [CESNET/libnetconf2#168]
My installed openssl is of version 1.1.1

c.f. excerpt from `/usr/include/openssl/opensslv.h`
```
# define OPENSSL_VERSION_NUMBER  0x1010100fL
# define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1  11 Sep 2018"
```
Then I got the following warning when compiling libnetconf2 :
```
/home/brchiu/Projects/libnetconf2/src/session.c:1368:1: warning: ‘nc_ssh_destroy’ defined but not used [-Wunused-function]
 nc_ssh_destroy(void)
 ^~~~~~~~~~~~~~
/home/brchiu/Projects/libnetconf2/src/session.c:1361:1: warning: ‘nc_ssh_init’ defined but not used [-Wunused-function]
 nc_ssh_init(void)
 ^~~~~~~~~~~
/home/brchiu/Projects/libnetconf2/src/session.c:1368:1: warning: ‘nc_ssh_destroy’ defined but not used [-Wunused-function]
 nc_ssh_destroy(void)
 ^~~~~~~~~~~~~~
/home/brchiu/Projects/libnetconf2/src/session.c:1361:1: warning: ‘nc_ssh_init’ defined but not used [-Wunused-function]
 nc_ssh_init(void)
 ^~~~~~~~~~~
```
So when `NC_ENABLED_SSH` and `NC_ENABLED_TLS` both defined, function `nc_ssh_tls_init` does not initialize `nc_ssh_init()`.

**Comment by michalvasko** [comment]
Hi,
yes, we know about this problem but it is fixed in `devel` and, more importantly, is harmless. It is no longer required to initialize anything since OpenSSL 1.1.0.

Regards,
Michal

**Comment by brchiu** [comment]
Hi , @michael , not only the initialization of openssl, but also the initialization of libssh be bypassed if both NC_ENABLED_SSH and NC_ENABLED_TLS defined, is it still OK ?

**Comment by michalvasko** [comment]
Hi,
you are right, not exactly ([doc](http://api.libssh.org/stable/group__libssh.html#ga3ebf8d6920e563f3b032e3cd5277598e)), now it should be fine.

Regards,
Michal
