### ISSUE TITLE
Libnetconf2 make fails

### ISSUE THREAD

**Issue by Genricname** [CESNET/libnetconf2#172]
make fails with multiple errors: 
/libnc2/src/session_server.h:226:63: error: unknown type name ‘LYS_VERSION’; did you mean ‘NC_VERSION’?
 const char **nc_server_get_cpblts_version(struct ly_ctx *ctx, LYS_VERSION version);
                                                               ^~~~~~~~~~~
                                                               NC_VERSION
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/home/suser/libnc2/src/messages_server.c: In function ‘nc_err_libyang’:
/home/suser/libnc2/src/messages_server.c:377:17: error: called object is not a function or function pointer
         switch (ly_vecode(ctx)) {
                 ^
/home/suser/libnc2/src/messages_server.c:382:32: error: too many arguments to function ‘ly_errpath’
             nc_err_set_path(e, ly_errpath(ctx));
                                ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:385:19: error: too many arguments to function ‘ly_errmsg’
             str = ly_errmsg(ctx);
                   ^~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1877:13: note: declared here
 const char *ly_errmsg(void);
             ^~~~~~~~~
/home/suser/libnc2/src/messages_server.c:435:32: error: too many arguments to function ‘ly_errpath’
             nc_err_set_path(e, ly_errpath(ctx));
                                ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:440:32: error: too many arguments to function ‘ly_errpath’
             nc_err_set_path(e, ly_errpath(ctx));
                                ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:444:17: error: too many arguments to function ‘ly_errapptag’
             if (ly_errapptag(ctx)) {
                 ^~~~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1902:13: note: declared here
 const char *ly_errapptag(void);
             ^~~~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:445:39: error: too many arguments to function ‘ly_errapptag’
                 nc_err_set_app_tag(e, ly_errapptag(ctx));
                                       ^~~~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1902:13: note: declared here
 const char *ly_errapptag(void);
             ^~~~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:449:32: error: too many arguments to function ‘ly_errpath’
             nc_err_set_path(e, ly_errpath(ctx));
                                ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:455:32: error: too many arguments to function ‘ly_errpath’
             nc_err_set_path(e, ly_errpath(ctx));
                                ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:460:32: error: too many arguments to function ‘ly_errpath’
             nc_err_set_path(e, ly_errpath(ctx));
                                ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:462:19: error: too many arguments to function ‘ly_errmsg’
             str = ly_errmsg(ctx);
                   ^~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1877:13: note: declared here
 const char *ly_errmsg(void);
             ^~~~~~~~~
/home/suser/libnc2/src/messages_server.c:472:19: error: too many arguments to function ‘ly_errpath’
             str = ly_errpath(ctx);
                   ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:478:67: error: too many arguments to function ‘ly_errpath’
                 e = nc_err(NC_ERR_UNKNOWN_ELEM, NC_ERR_TYPE_PROT, ly_errpath(ctx));
                                                                   ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:483:63: error: too many arguments to function ‘ly_errpath’
             e = nc_err(NC_ERR_MISSING_ELEM, NC_ERR_TYPE_PROT, ly_errpath(ctx));
                                                               ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:486:59: error: too many arguments to function ‘ly_errpath’
             e = nc_err(NC_ERR_BAD_ELEM, NC_ERR_TYPE_PROT, ly_errpath(ctx));
                                                           ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:491:19: error: too many arguments to function ‘ly_errmsg’
             str = ly_errmsg(ctx);
                   ^~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1877:13: note: declared here
 const char *ly_errmsg(void);
             ^~~~~~~~~
/home/suser/libnc2/src/messages_server.c:500:17: error: called object is not a function or function pointer
             if (ly_vecode(ctx) == LYVE_INATTR) {
                 ^
/home/suser/libnc2/src/messages_server.c:501:73: error: too many arguments to function ‘ly_errpath’
                 e = nc_err(NC_ERR_UNKNOWN_ATTR, NC_ERR_TYPE_PROT, attr, ly_errpath(ctx));
                                                                         ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:502:24: error: called object is not a function or function pointer
             } else if (ly_vecode(ctx) == LYVE_MISSATTR) {
                        ^
/home/suser/libnc2/src/messages_server.c:503:73: error: too many arguments to function ‘ly_errpath’
                 e = nc_err(NC_ERR_MISSING_ATTR, NC_ERR_TYPE_PROT, attr, ly_errpath(ctx));
                                                                         ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:505:69: error: too many arguments to function ‘ly_errpath’
                 e = nc_err(NC_ERR_BAD_ATTR, NC_ERR_TYPE_PROT, attr, ly_errpath(ctx));
                                                                     ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:513:17: error: too many arguments to function ‘ly_errapptag’
             if (ly_errapptag(ctx)) {
                 ^~~~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1902:13: note: declared here
 const char *ly_errapptag(void);
             ^~~~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:514:39: error: too many arguments to function ‘ly_errapptag’
                 nc_err_set_app_tag(e, ly_errapptag(ctx));
                                       ^~~~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1902:13: note: declared here
 const char *ly_errapptag(void);
             ^~~~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:516:32: error: too many arguments to function ‘ly_errpath’
             nc_err_set_path(e, ly_errpath(ctx));
                                ^~~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1891:13: note: declared here
 const char *ly_errpath(void);
             ^~~~~~~~~~
/home/suser/libnc2/src/messages_server.c:526:23: error: too many arguments to function ‘ly_errmsg’
     nc_err_set_msg(e, ly_errmsg(ctx), "en");
                       ^~~~~~~~~
In file included from /home/suser/libnc2/src/messages_server.c:21:0:
/usr/include/libyang/libyang.h:1877:13: note: declared here
 const char *ly_errmsg(void);

**Comment by michalvasko** [comment]
Hi,
you have some ancient *libyang* installed, update it and it will compile just fine.

Regards,
Michal

**Comment by Genricname** [comment]
> Hi,
> you have some ancient _libyang_ installed, update it and it will compile just fine.
> 
> Regards,
> Michal

Indeed. Thanks.
