### ISSUE TITLE
SSh server in Libnetconf2.

### ISSUE THREAD

**Issue by vprasad** [CESNET/libnetconf2#173]
Hi ,
Wanted a info wrt to the SSH server that Libnetconf2 internally uses.
So i can see there are some libssh,libsshthread dependency while compiling Libentconf2 .
So question is does Libnetconf2 using its own inbuilt SSH server .?
Is there any option via which we can integrate Libnetconf2 with OpenSSH server.This we require because our Network element has OpenSSH server already running.So we don;t to use this OpenSSH server also for Libnetconf2 stuffs.

Thanks,

**Comment by michalvasko** [comment]
Hi,
you can establish the transport layer connection yourself and then pass the resulting file descriptors to *libnetconf2* using [nc_accept_inout()](https://github.com/CESNET/libnetconf2/blob/master/src/session_server.h#L245). That is probably what you want to do.

Regards,
Michal
