### ISSUE TITLE
Issue parsing module

### ISSUE THREAD

**Issue by makramalla** [CESNET/libnetconf2#18]
Hello,

I am facing a couple of issues in parsing a module to connect to a NETCONF server using netopeergui.

The capability is  "urn:yumaworks:params:xml:ns:netconf:config-id?id=401", which according to my understanding  is allowed per RFC 6020.

However whenever I try to connect I receive  the following error: "lib ERROR: Unknown capability "urn:yumaworks:params:xml:ns:netconf:config-id?id=401" could not be parsed.

After some basic tracing methods I found out the this error occurs in the session_client.c script, which dictates that the capability has to have "module= " in its body, which is not the case. This consequently interrupts the whole connection process.

Is there a way that I can edit/overwrite that without causing other issues that might occur accordingly?

Thanks,

Maged

**Comment by makramalla** [comment]
Hello again,

Thank you so much for resolving this issue. I tried to re-run it using the new commit, but I still got an error in parsing "ietf-netconf".

First I receive this error when I run the "make" command:

Scanning dependencies of target netconf2
[  5%] Building C object CMakeFiles/netconf2.dir/src/io.c.o
/libnetconf2/src/io.c: In function \u2018nc_write_msg\u2019:
/libnetconf2/src/io.c:1003:91: error: \u2018LYP_NETCONF\u2019 undeclared (first use in this function)
         lyd_print_clb(nc_write_xmlclb, (void *)&arg, content, LYD_XML, LYP_WITHSIBLINGS | LYP_NETCONF);
                                                                                           ^
/libnetconf2/src/io.c:1003:91: note: each undeclared identifier is reported only once for each function it appears in


After a couple of troubleshooting approaches, I was able to successfully "make install", however I was not able to parse ietf-netconf as shown in the below log files.

Can you help me out?

Thank you,

Maged

Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Reading module "yang".
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Module "yang" successfully parsed.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Reading module "ietf-inet-types".
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Resolving derived type "union" failed, it will be attempted later.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Resolving derived type "union" failed, it will be attempted later.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Resolving derived type "union" failed, it will be attempted later.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Resolving derived type "union" failed, it will be attempted later.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: All "ietf-inet-types" schema nodes and constraints resolved.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Module "ietf-inet-types" successfully parsed.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Reading module "ietf-yang-types".
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Module "ietf-yang-types" successfully parsed.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Reading module "ietf-yang-library".
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Module "ietf-yang-library" successfully parsed.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Reading module "ietf-netconf-monitoring".
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Module "ietf-netconf-monitoring" successfully parsed.
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Resolving unresolved data nodes and their constraints...
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: All data nodes and constraints resolved.
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: lyd_parse_xml: invalid variable parameter (const struct lys_node *rpc_act).
Nov 21 15:54:56 netopeergui netopeerguid: error calback: empty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: Failed to parse <rpc-reply>.
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: Session 23: failed to receive a reply to <get-schema>.
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: User module retrieval callback failed!
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib VERBOSE: Reading module "ietf-netconf".
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: Failed to parse <rpc-reply>.
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: Session 23: failed to receive a reply to <get-schema>.
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: User module retrieval callback failed!
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: Importing "ietf-netconf-acm" module into "ietf-netconf" failed.
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: Module "ietf-netconf" parsing failed.
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib ERROR: Loading base NETCONF schema failed.
Nov 21 15:54:56 netopeergui netopeerguid: error calback: nonempty error list
Nov 21 15:54:56 netopeergui netopeerguid: lib WARNING: Session 23: missing ietf-netconf schema in context, unable to send <close-session>.
Nov 21 15:54:56 netopeergui netopeerguid: Connection could not be established
Nov 21 15:54:56 netopeergui netopeerguid: Connect - error from libnetconf's callback.

**Comment by michalvasko** [comment]
Hi,
you need to update your libyang version, both the problems are caused by this.

Regards,
Michal
