### ISSUE TITLE
Does libnetconf2 support building as static library?

### ISSUE THREAD

**Issue by gli-spirent** [CESNET/libnetconf2#181]
Did not find any option related to static in CMakeList.txt.

**Comment by michalvasko** [comment]
Hi,
it is not officially supported and I do not know if anyone build it this way. Should not be too difficult I assume, though. But you will have to make all the changes in `CMakeLists.txt` yourself.

Regards,
Michal

**Comment by brchiu** [comment]
@gli-spirent 

```
- add_library(netconf2 SHARED ${libsrc})
+ add_library(netconf2 STATIC ${libsrc})
```

**Comment by gli-spirent** [comment]
Thanks, @brchiu

**Comment by gli-spirent** [comment]
> Hi,
> it is not officially supported and I do not know if anyone build it this way. Should not be too difficult I assume, though. But you will have to make all the changes in `CMakeLists.txt` yourself.
> 
> Regards,
> Michal

Thanks, @michalvasko
