### ISSUE TITLE
Help on build libssh_threads

### ISSUE THREAD

**Issue by LiMinggang** [CESNET/libnetconf2#183]
I met an issue to build the test examples of libnetconf2.
/usr/bin/ld: cannot find -lssh_threads
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_init_destroy_server.dir/build.make:114: tests/test_init_destroy_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:274: tests/CMakeFiles/test_init_destroy_server.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

I tried to figure out if libssh was built correctly. However, could not get the ssh_threads. The libssh I used is the latest version from git.libssh.org.

Is it possible libssh removed the lib while libnetconf2 was still using the old ones?

**Comment by michalvasko** [comment]
Hi,
`libssh_threads` should be linked only for *libssh* version lower than 0.8.0. It seems in your case this was not properly detected. I have tried it with the release version 0.9.2 and it was detected fine, so please use that version.

Regards,
Michal

**Comment by LiMinggang** [comment]
Thanks @michalvasko
