### ISSUE TITLE
Does libnetconf2 plan to support rfc8256?

### ISSUE THREAD

**Issue by tonyguo-spirent** [CESNET/libnetconf2#184]
it's not an issue, but want to know the answer.

**Comment by michalvasko** [comment]
Hi,
are you really asking about [RFC 8256](https://tools.ietf.org/html/rfc8256)?

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
Hi, Michal
Yes, I want to know it.

**Comment by michalvasko** [comment]
Hi,
I do not think it is relevant. *libnetconf2* offers SSH, TLS and a user-handled (`nc_connect_inout()`) transport protocols. I do not know much about MPLS, but you can definitely use whatever Layer 2 and Layer 3 protocol you want with the last mentioned connection kind. What kind of support do you exactly expect from *libnetconf2*?

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
I just begin the research on netconf.

**Comment by michalvasko** [comment]
Okay, then the relevant RFCs are [this](https://tools.ietf.org/html/rfc6242) and [this](https://tools.ietf.org/html/rfc7589), *libnetconf2* support both of them natively. Otherwise you should be free to use whatever lower layer protocols you want, neither NETCONF nor *libnetconf2* should be affected.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
Hi, Michalvasko 
I am sorry that I made a mistake, I meant to https://tools.ietf.org/html/rfc8526, not 8256, will libnetconf2 plan to support it?

**Comment by michalvasko** [comment]
Hi,
that is why I have asked, it did not make much sense to me. Anyway, RFC 8526 (NMDA) is supported, but it does not have much to do with *libnetconf2* (RPCs can be [created natively](https://github.com/CESNET/libnetconf2/blob/devel/src/messages_client.h#L470
)).

It is supported if you use the latest [sysrepo](github.com/sysrepo/sysrepo) from `devel` branch with [netopeer2-server](github.com/cesnet/netopeer2) from `devel-server` branch. You will get a NETCONF server that supports both `<get-data>` and `<edit-data>`.

Regards,
Michal
