### ISSUE TITLE
install libnetconf2-devel rpm failed

### ISSUE THREAD

**Issue by sun5** [CESNET/libnetconf2#185]
Hi,
[root@localhost x86_64]# rpm -ivh libnetconf2-experimental-1.1.1-0.x86_64.rpm 
error: Failed dependencies:
        libssh.so.4(LIBSSH_4_5_0)(64bit) is needed by libnetconf2-experimental-1.1.1-0.x86_64

`[root@localhost x86_64]# ll /usr/lib64/libssh.so*
lrwxrwxrwx 1 root root     11 Nov 20 08:37 /usr/lib64/libssh.so -> libssh.so.4
lrwxrwxrwx 1 root root     15 Nov 20 09:23 /usr/lib64/libssh.so.4 -> libssh.so.4.4.0
-rwxr-xr-x 1 root root 471632 Nov 30  2018 /usr/lib64/libssh.so.4.4.0`
And the lisssh rpm version as follow:
`[root@localhost x86_64]# cat /etc/system-release
CentOS Linux release 7.5.1804 (Core) 
[root@localhost x86_64]# rpm -qi libssh
Name        : libssh
Version     : 0.7.1
Release     : 7.el7
Architecture: x86_64
Install Date: Wed 20 Nov 2019 09:23:48 AM CST
Group       : System Environment/Libraries
Size        : 529013
License     : LGPLv2+
Signature   : RSA/SHA256, Sat 01 Dec 2018 05:04:46 AM CST, Key ID 24c6a8a7f4a80eb5
Source RPM  : libssh-0.7.1-7.el7.src.rpm
Build Date  : Fri 30 Nov 2018 02:02:34 AM CST`

How can I  get the 'LIBSSH_4_5_0' ?
Thanks.

**Comment by michalvasko** [comment]
Hi,
have you installed `libnetconf2-experimental` for CentOS 7.5? Anyway, even if you did, it is easily an outdated version so it is better to compile and install from the source. Then you should have no problems with dependencies.

Regards,
Michal

**Comment by sun5** [comment]
Hi Michal,
   Oh~, I installed  libnetconf2-experimental by rpm failed. And compile and install from the source is 
   running Ok.
   I will install it on the other target machine,it need the rpm, how can I solve this  dependencies better.
Thanks a lot

**Comment by michalvasko** [comment]
Hi,
unfortunately, there is no maintained *libnetconf2* package. So I am not sure what to tell you, making your own package is possible but I do not think it is a good idea. But it is possible there will be packages available later.

Regards,
Michal
