### ISSUE TITLE
Could not set TCP_NODELAY socket option

### ISSUE THREAD

**Issue by peter-summer** [CESNET/libnetconf2#187]
Sometimes libnetconf2 maybe enter following circle.

Dec  9 20:03:57 localhost netopeer2-server[16830]: Call Home client "controller3" connecting...
Dec  9 20:03:57 localhost netopeer2-server[16830]: Trying to connect via IPv4.
Dec  9 20:04:02 localhost netopeer2-server[16830]: timed out after 5s (Operation now in progress).
Dec  9 20:04:02 localhost netopeer2-server[16830]: Successfully connected to 192.168.204.150:6666 over IPv4.
Dec  9 20:04:02 localhost netopeer2-server[16830]: Could not set TCP_NODELAY socket option (Bad file descriptor).
Dec  9 20:04:03 localhost netopeer2-server[16830]: Trying to connect the pending socket=31.
Dec  9 20:04:08 localhost netopeer2-server[16830]: timed out after 5s (Bad file descriptor).
Dec  9 20:04:09 localhost netopeer2-server[16830]: Trying to connect the pending socket=31.
Dec  9 20:04:14 localhost netopeer2-server[16830]: timed out after 5s (Bad file descriptor).
Dec  9 20:04:15 localhost netopeer2-server[16830]: Trying to connect the pending socket=31.

I find there is a bug in function 'nc_sock_connect' in session_client.c.
```C
if (setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, &opt, sizeof opt) == -1) {
                ERR("Could not set TCP_NODELAY socket option (%s).", strerror(errno));
                close(sock);
                return -1;
 }
```
 "*sock_pending" is not set to -1 before return -1 here. So "trying to connect the pending socket" will be called repeatedly.

**Comment by michalvasko** [comment]
Hi,
I am not sure when this error can occur but now even if it does, the pending socket should be cleared.

Regards,
Michal
