### ISSUE TITLE
libnetconf2 failed by executing "ctest --output-on-failure"

### ISSUE THREAD

**Issue by sun5** [CESNET/libnetconf2#189]
Hi,
 When make libnetconf2-devel packages，test the "test_server_thread" failed。
 7/11 Test  #7: test_server_thread ...............***Failed    0.09 sec
libyang[2]: Plugin "/usr/lib64/libyang/extensions/metadata.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/extensions/nacm.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/extensions/yangdata.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/user_types/user_inet_types.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/user_types/user_yang_types.so" successfully loaded.
libyang[2]: Reading module "ietf-yang-metadata".
libyang[2]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
libyang[2]: Reading module "yang".
libyang[2]: Resolving "yang" unresolved schema nodes and their constraints...
libyang[2]: All "yang" schema nodes and constraints resolved.
libyang[2]: Module "yang@2017-02-20" successfully parsed as implemented.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
libyang[2]: Reading module "ietf-datastores".
libyang[2]: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
libyang[2]: Reading module "ietf-yang-library".
libyang[2]: Searching for "ietf-yang-types" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "ietf-yang-types" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Searching for "ietf-inet-types" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "ietf-inet-types" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Searching for "ietf-datastores" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "ietf-datastores" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
libyang[2]: Searching for "ietf-netconf" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "ietf-netconf" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Loading schema from "/root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas/ietf-netconf.yin" file.
libyang[2]: Reading module "ietf-netconf".
libyang[2]: Searching for "ietf-netconf-acm" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "ietf-netconf-acm" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Loading schema from "/root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas/ietf-netconf-acm.yin" file.
libyang[2]: Reading module "ietf-netconf-acm".
libyang[2]: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
libyang[2]: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
libyang[2]: Searching for "module-a" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "module-a" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Loading schema from "/root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas/module-a.yang" file.
libyang[2]: Module "module-a" successfully parsed as implemented.
libyang[2]: Searching for "module-a-dv" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "module-a-dv" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Loading schema from "/root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas/module-a-dv.yang" file.
libyang[2]: Module "module-a-dv" successfully parsed as implemented.
libyang[2]: Searching for "module-a-dv2" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas.
libyang[2]: Searching for "module-a-dv2" in /root/libnetconf2/build/rpms/BUILD/libnetconf2-master/tests.
libyang[2]: Loading schema from "/root/libnetconf2/build/rpms/BUILD/libnetconf2-master/schemas/module-a-dv2.yang" file.
libyang[2]: Resolving "module-a-dv2" unresolved schema nodes and their constraints...
libyang[2]: All "module-a-dv2" schema nodes and constraints resolved.
libyang[2]: Module "module-a-dv2" successfully parsed as implemented.
libyang[0]: Module not found or not implemented. (path: /ietf-netconf-monitoring)
[INF]: Listening on 0.0.0.0:6001 for SSH connections.
[INF]: Listening on 0.0.0.0:6501 for TLS connections.
[INF]: Trying to connect via IPv4 to 127.0.0.1:6001.
[INF]: Successfully connected to 127.0.0.1:6001 over IPv4.
[INF]: Trying to connect via IPv4 to 127.0.0.1:6501.
[INF]: Successfully connected to 127.0.0.1:6501 over IPv4.
[ERR]: Certificate list "trusted_cert_list1" not found.
[INF]: Listening on 0.0.0.0:6003 for TLS connections.
[INF]: Accepted a connection on 0.0.0.0:6501.
[INF]: Cert verify: fail (self signed certificate in certificate chain), but the client certificate is trusted, continuing.
[INF]: Cert verify: depth 1.
[INF]: Cert verify: subject: /C=CZ/ST=Some-State/L=Brno/O=CESNET/OU=TMC/CN=serverca.
[INF]: Cert verify: issuer:  /C=CZ/ST=Some-State/L=Brno/O=CESNET/OU=TMC/CN=serverca.
[INF]: Cert verify CTN: cert fail, cert-to-name will continue on the next cert in chain.
[INF]: Cert verify: depth 0.
[INF]: Cert verify: subject: /C=CZ/ST=Some-State/L=Brno/O=CESNET/OU=TMC/CN=client.
[INF]: Cert verify: issuer:  /C=CZ/ST=Some-State/L=Brno/O=CESNET/OU=TMC/CN=serverca.
[INF]: Cert verify CTN: entry with a matching fingerprint found.
[INF]: Cert verify CTN: new client username recognized as "test".
[INF]: Server certificate successfully verified.
libyang[2]: Plugin "/usr/lib64/libyang/extensions/metadata.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/extensions/nacm.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/extensions/yangdata.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/user_types/user_inet_types.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/user_types/user_yang_types.so" successfully loaded.
libyang[2]: Reading module "ietf-yang-metadata".
libyang[2]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
libyang[2]: Reading module "yang".
libyang[2]: Resolving "yang" unresolved schema nodes and their constraints...
libyang[2]: All "yang" schema nodes and constraints resolved.
libyang[2]: Module "yang@2017-02-20" successfully parsed as implemented.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: Session 1: retreiving data for schema "ietf-netconf", revision "2011-06-01".
[INF]: Session 1: reading schema from localfile "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/schemas/ietf-netconf.yin".
[INF]: Session 1: retreiving data for schema "ietf-inet-types", revision "2013-07-15".
[INF]: Session 1: retreiving data for schema "ietf-netconf-acm", revision "2018-02-14".
[INF]: Session 1: reading schema from localfile "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/schemas/ietf-netconf-acm.yin".
[INF]: Session 1: retreiving data for schema "ietf-yang-types", revision "2013-07-15".
[INF]: Session 1: retreiving data for schema "ietf-yang-library", revision "2019-01-04".
[WRN]: Session 1: loading NETCONF ietf-yang-library schema failed, unable to automatically use <get-schema>.
libyang[2]: Module "ietf-yang-metadata@2016-08-05" now implemented.
libyang[2]: Module "ietf-inet-types@2013-07-15" now implemented.
libyang[2]: Module "ietf-yang-types@2013-07-15" now implemented.
libyang[2]: Module "ietf-netconf-acm@2018-02-14" now implemented.
[INF]: Session 1: retreiving data for schema "module-a", revision "(null)".
[INF]: Session 1: reading schema from localfile "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/schemas/module-a.yang".
[INF]: Session 1: retreiving data for schema "module-a-dv", revision "(null)".
[INF]: Session 1: reading schema from localfile "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/schemas/module-a-dv.yang".
[INF]: Session 1: retreiving data for schema "module-a", revision "(null)".
[INF]: Session 1: reading schema from localfile "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/schemas/module-a.yang".
[INF]: Session 1: retreiving data for schema "module-a-dv2", revision "(null)".
[INF]: Session 1: reading schema from localfile "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/schemas/module-a-dv2.yang".
[INF]: Accepted a connection on 0.0.0.0:6001.
TLS client finished.
[INF]: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: Received an SSH message "request-auth" of subtype "none".
[INF]: Interactive SSH authentication method was disabled.
[INF]: Password SSH authentication method was disabled.
[INF]: Publickey athentication.
[INF]: Trying to authenticate using pair "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/tests//data/key_dsa" "/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/tests//data/key_dsa.pub".
[INF]: Received an SSH message "request-auth" of subtype "publickey".
[INF]: Received an SSH message "request-auth" of subtype "publickey".
[INF]: User "test" authenticated.
[INF]: Authentication successful.
[INF]: Received an SSH message "request-channel-open" of subtype "session".
[INF]: Received an SSH message "request-channel" of subtype "subsystem".
libyang[2]: Plugin "/usr/lib64/libyang/extensions/metadata.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/extensions/nacm.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/extensions/yangdata.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/user_types/user_inet_types.so" successfully loaded.
libyang[2]: Plugin "/usr/lib64/libyang/user_types/user_yang_types.so" successfully loaded.
libyang[2]: Reading module "ietf-yang-metadata".
libyang[2]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
libyang[2]: Reading module "yang".
libyang[2]: Resolving "yang" unresolved schema nodes and their constraints...
libyang[2]: All "yang" schema nodes and constraints resolved.
libyang[2]: Module "yang@2017-02-20" successfully parsed as implemented.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[ERR]: Server's <hello> timeout elapsed.
assert failed (/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/tests/test_server_thread.c:246)
[ERR]: Client's <hello> timeout elapsed.
assert failed (/root/libnetconf2/build/rpms/BUILD/libnetconf2-devel/tests/test_server_thread.c:68)

By the way, when pass the ctest check ,and install into other device
The netopeer2-cli will occur  the same ERR when input "connect "command

[root@localhost libnetconf2]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 

How can I solve the problem?
Thanks a lot.
Best Regard.

**Comment by michalvasko** [comment]
Replied in #192
