### ISSUE TITLE
In what condition, queue in nc_pollsession may have multi members with same value?

### ISSUE THREAD

**Issue by lumanyu180** [CESNET/libnetconf2#190]
Hi,

   I have a problem, nc_ps_queue_remove_id: internal error. It has many such error. I want to know, in what condition, it can occur. Thanks very much.

**Comment by michalvasko** [comment]
Hi,
it should never occur, hence the error. What *libnetconf2* version are you using?

Regards,
Michal

**Comment by lumanyu180** [comment]
Hi, 

   Thanks for your reply , i use libnetconf2 with 2-0.12-r2。It occurs  suddenly， and i don't know why . When it occurs, I found queue_len is queue_len, but in fact only 5 threads in queue。So it seems one thread enter the queue, but it does not leave。

**Comment by michalvasko** [comment]
Hi,
it would be great if you could update to the current *libnetconf2* (`master`, `devel` or the latest release). You can then turn on debugging and you should see all the PS queue changes which should make the problem obvious. Or you can at least use patch 9129095f3351ce89f58bf4e81686f71f95274f50 that adds these debug messages.

Regards,
Michal

**Comment by lumanyu180** [comment]
Hi,
   I try to use patch 9129095, but the debug messages are too many. And i don't know the condition it occurs , may be it occurs after 5 days or more. So i don't know how to resolve the problem.

**Comment by michalvasko** [comment]
Hi,
I do not think there is any other way how to debug this. Just log it all into a file and when the problem occurs, attach the full log file here.

Regards,
Michal
