### ISSUE TITLE
Callhome using Libnetconf2

### ISSUE THREAD

**Issue by vprasad** [CESNET/libnetconf2#191]
Hi ,
We want to implement the netconf callhome feature using Libnetconf2 .
For implementing callhome we have our own yang and we have our own retry algorithm  based on exponential backoff on all registered callhome configured destination.
So i was going through the libnetconf2 callhome Api "nc_connect_ch_client_dispatch" which basically does the callhome and implements the retry algorithm ,etc internally based on the ietf-netconf-server.yang .
However all the retry ,etc we need to implement ourself.Only we need some APi from libnetconf 2 which can do a callhome on a given IP and Port and return success/failures in case the netconf server was able to successfully connect to the client .Is there any similar API available currently in libnetconf2?If no how can i achieve this using Libnetconf2 .

Thanks,

**Comment by michalvasko** [comment]
Hi,
such a usage was not anticipated because we were hoping the models cover all the reasonable use-cases. So, if you want to use *libnetconf2*, you will have to use your own fork and expose whatever functions you need in API.

Regards,
Michal

**Comment by Snailfl** [comment]
Libnetconf2 has similar interfaces, focusing on those associated with nc_accept_callhome and those associated with nc_server_ch_add_client
