### ISSUE TITLE
libnetconf2 (v1.1.3) doesn't work with libssh-0.9.3

### ISSUE THREAD

**Issue by psch-k** [CESNET/libnetconf2#192]
Hi,
I have libyang / libnetconf2 / sysrepo / Netopeer2 running in a virtual machine, based on a daily updated Fedora 31.
Until December 18th, libssh-0.9.2-1 was the actual version in Fedora 31, and (mostly) everything was fine. Since December 19th, libssh-0.9.3-1 is the actual version in Fedora 31, and now I cannot setup an SSH connection from netopeer2-cli to netopeer2-server (both on the same VM).
The netopeer2-server logs "Client's <hello> timeout elapsed.", and v.v., the netopeer2-client logs "Server's <hello> timeout elapsed." (which isn't true, for both peers). Apparently, the function nc_read_msg_poll_io(),called in the functions nc_recv_client_hello_io() and nc_recv_server_hello_io() within the file src/session.c, return with NC_MSG_WOULDBLOCK.
When I revert to libssh-0.9.0-6.fc31.x86_64 in Fedora 31 (libssh-0.9.2-1 is no longer available),
everything is fine again, I can SSH-connect to netopeer2-server with netopeer2-client.
Used versions:
libyang: git tag v1.0.109
libnetconf2: git tag v1.1.3
sysrepo: git branch devel
Netopeer2: git tag v1.1.1

**Comment by sun5** [comment]
Hi 
I met the same problem in Centos.
The netopeer2-server logs "Client's timeout elapsed.", 
The netopeer2-client logs "Server's timeout elapsed.
And do making test  after compiling libnetconf2 sucessful,The testing fail with the same error. 
Used versions:
libssh-0.9.3
libyang-1.0.104
libnetconf2-1.1.2
sysrepo: git branch devel
Netopeer2 git branch devel

**Comment by psch-k** [comment]
Hi Michal,
thanks a lot for your investigation into this issue. I think, refusing to compile is the most acceptable solution in this case, because the "bad boy" is obviously outside of libnetconf2.
Kind Regards,
Peter

**Comment by jktjkt** [comment]
@psch-k , @sun5 : have you reported this bug upstream to libssh developers?

**Comment by jktjkt** [comment]
I've bisected this in libssh and opened a ticket upstream: https://bugs.libssh.org/T211

@michalvasko , I would appreciate if you could take a look as well.

**Comment by michalvasko** [comment]
@jktjkt Thanks for reporting it. As mentioned there, we have discussed it in the mailing list but it seemed to me like it was forgotten so I wanted to report it like you did. But I was swamped (still am) with other work so I did not get to do that. Having said that, do you think you can handle the communication further? It should not be too difficult to reproduce and you can point them to [this](https://github.com/CESNET/libnetconf2/blob/legacy/src/io.c#L530) code where the function is actually called. Otherwise, I will try to handle it but will have to manage my priorities somehow.

Regards,
Michal

**Comment by jktjkt** [comment]
Fixed upstream via https://bugs.libssh.org/rLIBSSH022409e99c9f6d6f1e540da5c2fa925b72998974 .

**Comment by michalvasko** [comment]
Great, thanks for letting us know.

Regards,
Michal

**Comment by psch-k** [comment]
Hi,
I just installed the latest stable release of libssh (tag 'stable-0.9', commit ID '9a10cef92086d3b22fa4acd9999cf908b7fa7e48'), which contains the bugfix for this issue, into my Fedora-31 VM. I confirm, that this libssh version solves my problems.
Thanks very much, jktjkt and Michal!
Kind Regards,
Peter
