### ISSUE TITLE
How can a netconf server get a netconf client's private capbility?

### ISSUE THREAD

**Issue by lumanyu180** [CESNET/libnetconf2#194]
Hi, 

    I  have a server with libnetconf2. And the client does not use libnetconf2. Now the client send its private capbilities in hello packet. I want to get its privite capbilities, how can i get them.  Is there API which can get client's private capbility ?

**Comment by michalvasko** [comment]
Hi,
no, this is currently not possible. Although not specified anywhere, the capabilities are sent mainly so that client knows what to expect from the server, not the other way around. Client sends its capabilities just so that the NETCONF version can be negotiated. Why then do you need the client capabilities?

Regards,
Michal

**Comment by lumanyu180** [comment]
Hi,
Thanks for your reply very much. My application is a netconf server,and there are different netconf clients. And there are some private behaviors  between the server and the client which are not supported by RFC. So the server want to distinguish the clients by their capabilities。

**Comment by michalvasko** [comment]
Hi,
I see. Like I said, I do not think such a feature is supported by NETCONF and *libnetconf2* does not even store client capabilities, only server ones. But I guess there is no real issue in doing so and I will add once I am finished with my current work. It should not be too difficult so you can also provide a patch yourself.

Regards,
Michal

**Comment by lumanyu180** [comment]
Hi,

Thanks for your reply very much. I understand what you mean. Like you said. it should not be too difficult，i will try it. And If you will add it , it will be perfect。Wait for your work。Thanks very much.
