### ISSUE TITLE
Compilation error on MAC OSX

### ISSUE THREAD

**Issue by sunlinh** [CESNET/libnetconf2#2]
I encountered errors when compiling libnetconf2 on my MAC, it seems that the MAC OSX does not support pthread_rwlock_t and CLOCK_REALTIME. The error log is :

sunlinhuideAir:build sunlinhui$ make
Scanning dependencies of target netconf2
[  4%] Building C object CMakeFiles/netconf2.dir/src/io.c.o
In file included from /Users/sunlinhui/Documents/workspace/libnetconf2/src/io.c:29:
In file included from /Users/sunlinhui/Documents/workspace/libnetconf2/src/libnetconf.h:22:
/Users/sunlinhui/Documents/workspace/libnetconf2/src/session_p.h:195:5: error: 
      unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
    pthread_spinlock_t sid_lock;
    ^~~~~~~~~~~~~~~~~~
    pthread_rwlock_t
/usr/include/sys/_pthread/_pthread_rwlock_t.h:30:35: note: 'pthread_rwlock_t'
      declared here
typedef __darwin_pthread_rwlock_t pthread_rwlock_t;
                                  ^
/Users/sunlinhui/Documents/workspace/libnetconf2/src/io.c:459:19: warning: 
      implicit declaration of function 'ppoll' is invalid in C99
      [-Wimplicit-function-declaration]
            ret = ppoll(&fds, 1, (timeout == -1 ? NULL : &ts_timeout), &...
                  ^
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/netconf2.dir/src/io.c.o] Error 1
make[1]: *** [CMakeFiles/netconf2.dir/all] Error 2
make: *** [all] Error 2

Any idea?

**Comment by rkrejci** [comment]
Please try to compile `macosx` branch if it works now. I'm going to try to use building on Os X in Travis CI, but it is not working yet.

**Comment by sunlinh** [comment]
Hi Radek,

Thanks for doing that, I tried the new branch and pthread_rwlock_t issue is resolved but the CLOCK_REALTIME I mentioned is still not resolved in macosx branch, the error log is:
sunlinhuideAir:build sunlinhui$ make
Scanning dependencies of target netconf2
[  4%] Building C object CMakeFiles/netconf2.dir/src/io.c.o
[  8%] Building C object CMakeFiles/netconf2.dir/src/log.c.o
[ 12%] Building C object CMakeFiles/netconf2.dir/src/messages_client.c.o
[ 16%] Building C object CMakeFiles/netconf2.dir/src/messages_server.c.o
[ 20%] Building C object CMakeFiles/netconf2.dir/src/session.c.o
/Users/sunlinhui/Documents/workspace/libnetconf2-macosx/src/session.c:60:9: warning: 
      implicit declaration of function 'clock_gettime' is invalid in C99
      [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, &ts_timeout);
        ^
/Users/sunlinhui/Documents/workspace/libnetconf2-macosx/src/session.c:60:23: error: 
      use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &ts_timeout);
                      ^
/Users/sunlinhui/Documents/workspace/libnetconf2-macosx/src/session.c:65:15: warning: 
      implicit declaration of function 'pthread_mutex_timedlock' is invalid in
      C99 [-Wimplicit-function-declaration]
        ret = pthread_mutex_timedlock(lock, &ts_timeout);

**Comment by rkrejci** [comment]
I was able to set up automatic OS X builds in Travis CI and I'm continuing with fixing other compat issues.

**Comment by rkrejci** [comment]
The code should works in the current master branch. In Travis we have still some issues with opnessl, but if you are able to correctly use libssl and llibcrypto in OS X, it should works for you.
