### ISSUE TITLE
Will there be Windows support for libnetconf2?

### ISSUE THREAD

**Issue by IamPatrik** [CESNET/libnetconf2#202]
Hi,
I was looking at this project, as it is supposed to be a great NETCONF library. This is probably true, but when looking at it I realized it is not multi-platform. From CMakeLists.txt

if(NOT UNIX)
    message(FATAL_ERROR "Only *nix like systems are supported.")
endif()

Multi-platform is very important for the project I work with. Is this planned to be implemented any time soon or are there no plans to do this at the moment?

BR
Patrik

**Comment by michalvasko** [comment]
Hi Patrik,
unfortunately, *libnetconf2* is meant only for *nix systems exactly as the error says and there are no plans to port it. It would not be trivial and I am afraid major parts of the code would not be usable/would have to be completely rewritten.

Regards,
Michal

**Comment by schaveyt** [comment]
@IamPatrik did you find an alternative? I know of many other on the hunt for at least a client library for windows

**Comment by schaveyt** [comment]
This is a .NET library that .NET developer can use as a NETCONF client and issue NETCONF rpc commands
https://github.com/sshnet/SSH.NET
