### ISSUE TITLE
Hosted doxygen is missing

### ISSUE THREAD

**Issue by kroeschl** [CESNET/libnetconf2#205]
The doxygen documentation hosted at https://netopeer.liberouter.org/doc/libnetconf2/ is missing as of sometime around 2/3/20. I'm not sure if this is a build/deploy issue on the part of libnetconf2 or an issue with netopeer.liberouter.org--if it's the latter feel free to close and I'll email the host.

Interestingly, [libyang's documentation](https://netopeer.liberouter.org/doc/libyang/) is still up.

**Comment by michalvasko** [comment]
Hi,
right, sorry about that. It was again generated successfully. Also, we are the hosts.

Regards,
Michal

**Comment by kroeschl** [comment]
No problem, and thanks for the quick response!
