### ISSUE TITLE
Setting a nc_set_print_clb() leads to segfaults due to lack of libyang path generation

### ISSUE THREAD

**Issue by bstreiff** [CESNET/libnetconf2#207]
Since fea54dc3, `nc_set_print_clb()` has configured `ly_set_log_clb()` with `path` set to `0`, which
results in libyang setting `path_flag` to 0 (from its default of 1) if a client ever calls `nc_set_print_clb()` to set a custom print callback (for example, for printing to syslog).

This then results in any call to `ly_errpath()` returning `NULL`, because libyang no longer bothers with resolving paths and thus never creates path strings to be assigned into the error item list.

This then creates a problem in the subsequent case of calling `nc_err_libyang()` after a validation error
involving an invalid element (`LYVE_INELEM`), in that `nc_err_libyang()` will try to query the errpath and operate on it without any NULL-checking. From [messages_server.c:471](https://github.com/CESNET/libnetconf2/blob/v1.1.7/src/messages_server.c#L471), we have:
```c
    case LYVE_INELEM:
        str = ly_errpath(ctx);        // str now NULL
        if (!strcmp(str, "/")) {      // strcmp SIGSEGVs due to null pointer dereference
```

As per the documentation:
```
 * This callback is set for libnetconf2 and also libyang that is used internally. libyang
 * callback can be set explicitly, but must be done so after calling this function.
```

That would seem to imply that the client is not expected to be required to call libyang's `ly_set_log_clb()`, but they may do so after calling `nc_set_print_clb()`.

That suggests that one or both of the following probably needs to happen:
- libnetconf2 could certainly call `ly_set_log_clb()` with `path` set to `1`, especially if it expects to be able to use `ly_errpath()`
- `nc_err_libyang()` could be more tolerant of a NULL pointer return from `ly_errpath()`, as clients can also call `ly_set_log_clb()` (perhaps with `path` set to 0) in addition to libnetconf2's use of it.

### Workaround

After calling `nc_set_print_clb`, immediately call `ly_set_log_clb` with `path` set to 1, e.g.:

```c
static void my_nc_print_clb(NC_VERB_LEVEL lvl, const char *msg)
{
    /* ... do something with the log message here, send to syslog, whatever ... */
}

static void my_nc_ly_print_clb(LY_LOG_LEVEL lvl, const char *msg, const char *)
{
    /* just turn around and call the same callback we use for libnetconf2 */
    my_nc_print_clb((NC_VERB_LEVEL)lvl, msg);
}

void configure_logging()
{
    nc_set_print_clb(my_nc_print_clb);
    ly_set_log_clb(my_nc_ly_print_clb, 1);  // force libyang to resolve paths
}
```

**Comment by michalvasko** [comment]
Hi,
you are right, should be fixed now. I have implemented both of your suggested fixes because it still can happen that the user will turn off path generation.

Regards,
Michal
