### ISSUE TITLE
Openssh integration with Libnetconf2 possible for callhome?

### ISSUE THREAD

**Issue by vishalearnz** [CESNET/libnetconf2#208]
Hi Michal,

I need to integrate libnetconf2 with openssh instead of libssh library , because inside our system we can't be using both and since openssh is default we need to go by that . 
Although already I can see one person has asked this question 

https://www.gitmemory.com/issue/CESNET/libnetconf2/173/540422525

Will your answer provided above hold true for the latest version of libnetconf2 ?
Also if dial in is possible via openssh , How can we manage that for callhome feature with openssh?

Thanks & Regards,
Vishal

**Comment by michalvasko** [comment]
Hi Vishal,
yes, what I wrote there is true, the function has not been removed. As for Call Home, it is a bit more complicated. You can accept an established session but you will have to manage it yourself. Meaning, if you want to support it, of course, handle reconnecting and other stuff based on [connection type](https://tools.ietf.org/html/draft-ietf-netconf-netconf-client-server-17#page-22).

Regards,
Michal

**Comment by vishalearnz** [comment]
ok thanks, Michal
