### ISSUE TITLE
OpenSSL 1.1 build issues

### ISSUE THREAD

**Issue by janhampl** [CESNET/libnetconf2#21]
While trying to compile libnetconf2 using OpenSSL 1.1:

> Downloads/libnetconf2-master/src/session.c: In function ‘nc_thread_destroy’:
Downloads/libnetconf2-master/src/session.c:1210:5: warning: ‘ERR_remove_thread_state’ is deprecated (declared at /usr/local/include/openssl/err.h:246) [-Wdeprecated-declarations]
Downloads/libnetconf2-master/src/session.c: At top level:
Downloads/libnetconf2-master/src/session.c:1049:1: warning: ‘tls_dyn_create_func’ defined but not used [-Wunused-function]
Downloads/libnetconf2-master/src/session.c:1064:1: warning: ‘tls_dyn_lock_func’ defined but not used [-Wunused-function]
Downloads/libnetconf2-master/src/session.c:1076:1: warning: ‘tls_dyn_destroy_func’ defined but not used [-Wunused-function]
[ 33%] Building C object CMakeFiles/netconf2.dir/src/session_client.c.o
[ 38%] Building C object CMakeFiles/netconf2.dir/src/session_server.c.o
[ 44%] Building C object CMakeFiles/netconf2.dir/src/time.c.o
[ 50%] Building C object CMakeFiles/netconf2.dir/src/session_client_ssh.c.o
[ 55%] Building C object CMakeFiles/netconf2.dir/src/session_server_ssh.c.o
[ 61%] Building C object CMakeFiles/netconf2.dir/src/session_client_tls.c.o
Downloads/libnetconf2-master/src/session_client_tls.c: In function ‘tlsauth_verify_callback’:
Downloads/libnetconf2-master/src/session_client_tls.c:40:20: error: storage size of ‘store_ctx’ isn’t known
Downloads/libnetconf2-master/src/session_client_tls.c:41:17: error: storage size of ‘obj’ isn’t known
Downloads/libnetconf2-master/src/session_client_tls.c:74:9: warning: ‘X509_CRL_get_nextUpdate’ is deprecated (declared at /usr/local/include/openssl/x509.h:709) [-Wdeprecated-declarations]
Downloads/libnetconf2-master/src/session_client_tls.c:80:13: warning: implicit declaration of function ‘X509_OBJECT_free_contents’ [-Wimplicit-function-declaration]
Downloads/libnetconf2-master/src/session_client_tls.c:116:41: error: dereferencing pointer to incomplete type
Downloads/libnetconf2-master/src/session_client_tls.c:41:17: warning: unused variable ‘obj’ [-Wunused-variable]
Downloads/libnetconf2-master/src/session_client_tls.c:40:20: warning: unused variable ‘store_ctx’ [-Wunused-variable]
Downloads/libnetconf2-master/src/session_client_tls.c: In function ‘nc_client_tls_update_opts’:
Downloads/libnetconf2-master/src/session_client_tls.c:396:9: warning: ‘TLSv1_2_client_method’ is deprecated (declared at /usr/local/include/openssl/ssl.h:1610) [-Wdeprecated-declarations]
Downloads/libnetconf2-master/src/session_client_tls.c:434:24: error: dereferencing pointer to incomplete type
make[2]: *** [CMakeFiles/netconf2.dir/src/session_client_tls.c.o] Error 1
make[1]: *** [CMakeFiles/netconf2.dir/all] Error 2
make: *** [all] Error 2
[  5%] Building C object CMakeFiles/netconf2.dir/src/session_client_tls.c.o
Downloads/libnetconf2-master/src/session_client_tls.c: In function ‘tlsauth_verify_callback’:
Downloads/libnetconf2-master/src/session_client_tls.c:40:20: error: storage size of ‘store_ctx’ isn’t known
Downloads/libnetconf2-master/src/session_client_tls.c:41:17: error: storage size of ‘obj’ isn’t known
Downloads/libnetconf2-master/src/session_client_tls.c:74:9: warning: ‘X509_CRL_get_nextUpdate’ is deprecated (declared at /usr/local/include/openssl/x509.h:709) [-Wdeprecated-declarations]
Downloads/libnetconf2-master/src/session_client_tls.c:80:13: warning: implicit declaration of function ‘X509_OBJECT_free_contents’ [-Wimplicit-function-declaration]
Downloads/libnetconf2-master/src/session_client_tls.c:116:41: error: dereferencing pointer to incomplete type
Downloads/libnetconf2-master/src/session_client_tls.c:41:17: warning: unused variable ‘obj’ [-Wunused-variable]
Downloads/libnetconf2-master/src/session_client_tls.c:40:20: warning: unused variable ‘store_ctx’ [-Wunused-variable]
Downloads/libnetconf2-master/src/session_client_tls.c: In function ‘nc_client_tls_update_opts’:
Downloads/libnetconf2-master/src/session_client_tls.c:396:9: warning: ‘TLSv1_2_client_method’ is deprecated (declared at /usr/local/include/openssl/ssl.h:1610) [-Wdeprecated-declarations]
Downloads/libnetconf2-master/src/session_client_tls.c:434:24: error: dereferencing pointer to incomplete type
make[2]: *** [CMakeFiles/netconf2.dir/src/session_client_tls.c.o] Error 1
make[1]: *** [CMakeFiles/netconf2.dir/all] Error 2
make: *** [all] Error 2

**Comment by michalvasko** [comment]
Hi,
it should now compile without errors and warnings.

Regards,
Michal
