### ISSUE TITLE
To differentiate between hello time out and ssh key exchange timeout

### ISSUE THREAD

**Issue by vishalearnz** [CESNET/libnetconf2#211]
Hi Michal,

I have a libnetconf2 server running . Now for testing with command line I am using ssh mechanism.

Scenario 1:

I logged in to the server using the  command ssh -v np@10.220.32.57 -p 830 -s netconf .
Server created a session . And waits for Hello message exchange. After certain interval Hello message timeout happens and session disconnects.

Scenario 2.
I am trying to login to the server using ssh -v np@10.220.32.57 -p 830 -s netconf , but donot give password and waits , after certain time the key exchange timeout happens and session disconnects (here the session id is not created)

So my question is that how we can differentiate between the two . 
As it waits on nc_accept() function and in both the scenarios the return value of nc_accept is 1( i.e NC_MSG_WOULDBLOCK) , so how can we differentiate between the two.

Its needed because in first scenario session has to be killed and removed , whereas in the next it just need to go idle.

Thanks & Regards,
Vishal

**Comment by michalvasko** [comment]
Hi,
could you please be more exact about what the problem is? Always say what session you mean because looking at the code, if `nc_accept()` returns `NC_MSG_WOULDBLOCK`, no NETCONF session is created.

Regards,
Michal

**Comment by vishalearnz** [comment]
Hi Michal,

This was a mistake in my part only , as at our end two sessions gets created one at server and one at netconf side , so the former session had to be removed . 

Closing this issue.

Thanks & Regards,
Vishal
