### ISSUE TITLE
Libnetconf2 reports error "Failed to write reply"

### ISSUE THREAD

**Issue by igortern** [CESNET/libnetconf2#212]
Hi,

Versions: devel snapshots taken on Friday Feb 14.

Sometimes netopeer2-error prints error [ERR]: [LN] Session 123 failed to write reply.".
The error is printed in line session_server.c:1317.
At this point "r" returned by nc_write_msg_io() is NC_MSG_WOULDBLOCK. io_timeout is 0.
There might be legitimate reasons for session->io_lock being taken at this point. 
I think it makes sense to set io_timeout to some short value >0.

What do you think?

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
yeah, you are right, nothing better to fix this I suppose.

Regards,
Michal
