### ISSUE TITLE
yang 1.1 modules not returned in server capabilities

### ISSUE THREAD

**Issue by rjarry** [CESNET/libnetconf2#219]
After looking at the code:

https://github.com/CESNET/libnetconf2/blob/devel/src/session.c#L1109

YANG modules with `yang-version 1.1;` are not returned in the server advertised capabilities. Is there a way to return all implemented modules in the libyang context?

**Comment by michalvasko** [comment]
Hi,
YANG 1.1 modules are not included in the capabilities but in `ietf-yang-library` data instead ([ref](https://tools.ietf.org/html/rfc7950#section-5.6.4)).

Regards,
Michal

**Comment by rjarry** [comment]
It seems like these 1.1 modules are not in the libyang context returned by `nc_session_get_ctx()`.

**Comment by michalvasko** [comment]
Oh, in the NETCONF client session? Then the reason will most likely be simply that the client could not get the modules. Neither using `get-schema` nor loading the locally. But there should be messages displayed informing about this and also the reason. Are there not?

Regards,
Michal

**Comment by rjarry** [comment]
With the latest version on the devel branch, it seems fixed. I may have had a broken environment for a while. Sorry about the disturbance :)
