### ISSUE TITLE
nc_send_rpc(), required element "action" in "configuration".

### ISSUE THREAD

**Issue by DubHokku** [CESNET/libnetconf2#226]
Hello, i'm  trying to execute NETCONF queries using 'juniper yang-models'. By functionality, 'juniper yang-models' is divided into 'configuration' and 'rpc'. Making a call using the 'rpc' models is successful:

```
char path[] = "/junos-rpc-traceroute:traceroute/host";
char value[] = "192.168.33.3";
struct lyd_node* path_rpc = lyd_new_path( NULL, junos_ctx, path, value, ( LYD_ANYDATA_VALUETYPE )0, 0 );
rp_request = nc_rpc_act_generic(( const struct lyd_node* )path_rpc, NC_PARAMTYPE_CONST );
msgtype = nc_send_rpc( rp_session, rp_request, timeout, &msgid );
```
converted to xml:
```
<rpc xmlns = "urn:ietf:params: xml:ns:netconf:base:1.0" message-id = "3">
  <traceroute xmlns = "http://yang.juniper.net/junos/rpc/traceroute">
    <host>192.168.33.3</host>
  </traceroute>
</rpc>

```
But making calls using 'configuration' models
```
char path[] = "/junos-conf-root:configuration/version";
char value[] = "127";
struct lyd_node* path_conf = lyd_new_path( NULL, junos_ctx, path, value, ( LYD_ANYDATA_VALUETYPE ) 0, 0 );
rp_request = nc_rpc_act_generic(( const struct lyd_node* )path_conf, NC_PARAMTYPE_CONST );
msgtype = nc_send_rpc( rp_session, rp_request, timeout, &msgid );
```
returns:
```
rpc_act_generic
nc_rpc_act_generic () ret. RPC
libyang [0]: Missing required element "action" in "configuration". ( path: /junos-conf-root:configuration )
wait reply
msgtype == NC_MSG_ERROR
connection done
```

Although there is no certainty about the correctness of the call ( the variables path[] and value[]), questions arise:
 
Can nc_rpc_act_generic() return RPC objects with the tag `<edit-config>`?
And how can nc_rpc_edit() work with 'juniper yang-models'?

--
Regards,
Hokku

**Comment by michalvasko** [comment]
Hi Hokku,
I do not see the module so I cannot tell you the exact reason for this error but I do not think you are using the API correctly. All `nc_rpc_*()` calls simply create a *libnetconf2* RPC object that can then be sent. It always corresponds to a YANG `rpc` or `action` statement in a loaded YANG module. While you can always use `nc_rpc_act_generic()` for this purpose, there are all the other functions to allow simpler creation of specific (`ietf-netconf` YANG module) standard RPCs. So, if you want to create an `edit-config` RPC, you should use `nc_rpc_edit()` instead.

Regards,
Michal

**Comment by DubHokku** [comment]
Hello Michal,
There are many modules, but they are similar and, as far as I understand, the 'entry point' is junos-conf-root.

www.github.com/Juniper/yang/tree/master/18.4/18.4R2/junos

**Comment by DubHokku** [comment]
I figured I could use nc_rpc_act_generic() to execute any NETCONF requests, but later realized that 'edit-config' must be generated to edit the configuration

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  <edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
      <candidate/>
    </target>
    <default-operation>merge</default-operation>
    <config>
      <configuration>
      ..
    </config>
  </edit-config>
</rpc>
```

while nc_rpc_act_generic() only converts
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  ..
</rpc>
```

and using 'lyd_new_path()' with configuration 'junos yang models' allows you to get only the essence of the request:
```
<configuration>
  <interfaces>
    <interface>
      <name>ge-0/0/1</name>
      <mtu>1417</mtu>
    </interface>
  </interfaces>
</configuration>
```

I probably could have missed something, but in connection with this got the idea of ​​using 'struct lyd_node*' as an argument to 'nc_rpc_edit()'.

**Comment by michalvasko** [comment]
Hi,
if you have the data as a *libyang* data tree (`struct lyd_node *`) you may be better off using `nc_rpc_act_generic()` after all. But note that all these other functions such as `nc_rpc_edit()` do is provide a customized interface how to fill their input values. Just compare the [function prototype](https://github.com/CESNET/libnetconf2/blob/devel/src/messages_client.h#L253) with the [RPC definition](https://github.com/CESNET/libnetconf2/blob/devel/schemas/ietf-netconf.yin#L483) (or better seen in [YANG format](https://github.com/CESNET/Netopeer2/blob/master/modules/ietf-netconf%402013-09-29.yang#L433)).

Regards,
Michal

**Comment by DubHokku** [comment]
Hello Michal,
You say that all calls to `nc_rpc_*()` create an RPC libnetconf2 object that always matches the YANG rpc or action instruction in the loaded YANG module. But the 'configuration' 'yang models' do not contain action or rpc instructions.

Nevertheless, the use of 'configuration yang models' in `lyd_new_path()` allows to get the `lyd_node` object, from which, theoretically, can get the correct XML for composing libnetconf2 RPC objects ( and, probably, for parsing server reply.. ).

I looked howto and the description of libyang functions( 1.0.130 ), there are methods ( such as `lyd_path()`, `lys_path()`, `lys_data_path()`) that allow to get XPath ( `char*` ) from the `lyd_node` object, but did not find a method that allows to get XML ( `char*` ).

I looked howto and the libnetconf2 function description( 1.1.7 ), but did not find a way to pass `lyd_node*` as an argument to `nc_rpc_edit()`.

Could you suggest a variant of converting the `lyd_node` object to XML for use in `nc_rpc_edit()`?


Regards,
Hokku

**Comment by michalvasko** [comment]
Hi,
I fully stand by what I said before but obviously some more details about `edit-config` RPC are needed for you to understand it. `nc_rpc_edit()` must be mapped to a YANG RPC just like all the others so you ask, how do you then change configuration with it? Well, it defines a [config](https://github.com/CESNET/Netopeer2/blob/master/modules/ietf-netconf%402013-09-29.yang#L528) `anyxml` node that is meant precisely for this purpose, to hold the configuration to be changed. So, `nc_rpc_edit()` expects an XML string as its input for this parameter. Like I tried to hint before, you are right that you cannot use `struct lyd_node *` directly even though you should be able to in an ideal case. That is why I said you may be better of using `nc_rpc_act_generic()`, which effectively can use the data tree directly.

But you can still use `nc_rpc_edit()`, you convert `struct lyd_node *` to `char *` simply by calling `lyd_print_mem()`. Finally, I know there may be some steps missing (such as how exactly to use `nc_rpc_act_generic()` for this use-case` but I simply do not have the time to explain it all, sorry. It is kind-of expected that when you decide to use *libnetconf2* directly (and not just take *netopeer2*) you do know all you need about YANG, NETCONF, and *libyang*. With all that information you should have no problems understanding the API.

Regards,
Michal

**Comment by DubHokku** [comment]
Hi Michal,
Thanks for the fine-manual about query generation, please forgive me for the attentiveness and, possibly, inaccuracies the translation. Your advices helps, thank you very much!

--
Regards,
Hokku
