### ISSUE TITLE
with libssh0.9.3

### ISSUE THREAD

**Issue by foxge** [CESNET/libnetconf2#228]
Hi
I try to build libnetconf2-1.1.7 with libssh-0.9.3, and patched the T211, but found out,
the connection from client will be disconnected after 20 seconds.
```
ERR("Session %u: receive rpc error, status is not running (%d)", cur_session->id, cur_session->status);
```

what happened ?

**Comment by michalvasko** [comment]
Hi,
you then got the 0.9.4 version behavior that is still buggy. Look into the FAQ, I have added links to both bugs so if you want to just apply another patch, you should be able to.

Regards,
Michal
