### ISSUE TITLE
notification capability is not sent by server even if module 'nc-notifications' and 'notifications' are loaded

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libnetconf2#23]
Hi,
Netconf server does not send capability  'urn:ietf:params:netconf:capability:notification:1.0' even if module 'nc-notifications' and 'notifications' are loaded.

**Comment by michalvasko** [comment]
Hi,
are using your own server or `netopeer2-server`? In netopeer notifications are not ready yet and even though this particular problem is fixed in the `notifications` branch, they still won't properly work.

Regards,
Michal

**Comment by fanchanghu** [comment]
yes, I am using netopeer2-server of devel-server branch. I'll try it again if you finish it. Thanks
