### ISSUE TITLE
how to parse NETCONF server reply?

### ISSUE THREAD

**Issue by DubHokku** [CESNET/libnetconf2#230]
Hello Michal,

i'am trying to receive rpc-reply with `nc_recv_reply()`

    `msgtype = nc_recv_reply( rp_session, rp_request, msg_id, timeout * 1000, LYD_OPT_TRUSTED | LYD_OPT_NOEXTDEPS, &rp_reply );`

with NC_VERB_LEVEL `NC_VERB_DEBUG` i can see NETCONF server reply

```
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/18.4R2/junos" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
...
</rpc-reply>
```

but libnetconf return error
```
    [ERR]: An empty data <rpc-reply>.
    Failed to receive a reply 
```
rpc request generated with junos yang model and `nc_rpc_act_generic()` on client side. the model has a description of both input and output request parameters ( [link-to-model](https://github.com/Juniper/yang/blob/master/18.4/18.4R2/junos/rpc/junos-rpc-interfaces%402019-01-01.yang) ).

for less strict verification, when calling nc_recv_reply(), i tried to control the behavior of the parser using LYD_OPT, applied LYD_OPT_TRUSTED | LYD_OPT_NOEXTDEPS and other flags, but could not get a positive result. libnetconf returns either

    `[ERR]: An empty data <rpc-reply>`
or
    
    `[ERR]: nc_recv_reply: invalid argument (parseroptions)`

the response data is `<rpc-reply>`, it’s dificult to say whether the response data is filtered switch configuration store data, status data, or some arbitrary data.

the manual says that
> parser expects that the provided data provides complete datastore content (both the configuration and state data) and performs data validation according to all YANG rules. This can be a problem in case of representing NETCONF's subtree filter data, edit-config's data or other type of data set - such data do not represent a complete data set and some of the validation rules can fail. Therefore there are other options (within lower 8 bits) to make parser to accept such a data.

but the use of flags from the lower bits of the parser options did not help to fix the error in processing the response.

can you advise how to prevent the `An empty data <rpc-reply>` error from occurring, maybe i should generate an additional lyd_node data node and substitute it into the 'rpc' or 'reply' parameter in the nc_recv_reply() call?

the manual also says, if the type of struct nc_reply_data is `NC_RPL_DATA`

> libyang RPC reply data tree (output of an RPC), <get> and <get-config> replies are special, in those cases there is the configuration itself, it should be validated as such (using LYD_OPT_GET or LYD_OPT_GETCONFIG), and it can be NULL in a valid reply. 

how then to get response data, for example, with using `lyd_print_mem()` in xml?

--
Regards,
Hokku

**Comment by michalvasko** [comment]
Hi,
do you have the required YANG module in the client *libyang* context? You can try using `LYD_OPT_STRICT` flag for parsing the reply and it should tell you when you are trying to parse data for which you do not have a module.

Regards,
Michal

**Comment by DubHokku** [comment]
Hi,
yes, these lines add a module to the context

```
junos_ctx = ly_ctx_new( ly_mod_path, LY_CTX_ALLIMPLEMENTED );

char path_rpc_lldp[] = "/home/fdmp/client_nc/yang/junos/rpc/junos-rpc-lldp@2019-01-01.yang";
const struct lys_module* parse_rpc_lldp = lys_parse_path( junos_ctx, path_rpc_lldp, LYS_IN_YANG );
```

`libyang[2]: Module "junos-rpc-lldp@2019-01-01" successfully parsed as implemented.`

 LYD_OPT `LYD_OPT_STRICT` in `nc_recv_reply()`

`nc_recv_reply( rp_session, rp_request, msg_id, timeout, LYD_OPT_STRICT, &rp_reply );`

with NC_VERB_LEVEL `NC_VERB_DEBUG` i can see log
```
[DBG]: Session 53459: received message:

<rpc-reply xmlns:junos="http://xml.juniper.net/junos/18.4R2/junos" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <lldp-neighbors-information junos:style="detail">
  </lldp-neighbors-information>
</rpc-reply>


libyang[0]: Unknown element "lldp-neighbors-information". (path: /junos-rpc-lldp:get-lldp-interface-neighbors)
[ERR]: Failed to parse <rpc-reply>.
Failed to receive a reply

```

**Comment by michalvasko** [comment]
Hi,
right, the problem is in the reply, the element `lldp-neighbors-information` has no explicit namespace so it inherits `urn:ietf:params:xml:ns:netconf:base:1.0`, which is wrong, obviously. It should probably use the prefix `junos`.

Regards,
Michal

**Comment by DubHokku** [comment]
yes, that's it. can this form of the NETCONF server response be associated with the client compatibility list? since in the hello message only

```
<hello xmlns = "urn: ietf: params: xml: ns: netconf: base: 1.0"> 
  <capabilities> 
    <capability> urn: ietf: params: netconf: base: 1.0 </capability> 
    <capability> urn: ietf: params: netconf: base: 1.1 </capability> 
  </capabilities> 
</hello>
```

**Comment by michalvasko** [comment]
Hi,
the server should not really expect any capabilities from the client other than the base NETCONF ones. Because then the client would have to know what modules it should support before connecting to the server, which completely defeats the purpose of `get-schema`, for instance. I believe this problem is quite simple, it is a bug in the server because it is sending an invalid reply, nothing to fix in the client.

Regards,
Michal

**Comment by DubHokku** [comment]
ok, but can i somehow get an reply without creating an additional socket?

**Comment by michalvasko** [comment]
HI,
what are you talking about, I am completely lost? What socket, no sockets were mentioned.

Regards,
Michal

**Comment by DubHokku** [comment]
i mean, recvfrom() or recvmsg(), what defined in <sys/socket.h> or some another library like libtins, etc, because i have to accept the server response in any form, but i forgot that the data is transmitted in encrypted form.

**Comment by michalvasko** [comment]
But you are using *libnetconf2*, right? It will handle all this for you so I still do not understand.

Regards,
Michal

**Comment by DubHokku** [comment]
Yes, it's true. the thing is, when the server response arrives, I have to accept it using nc_recv_reply(), this call tries to parse the answer, but returns an error, because namespace is not specified in the response. will be enough, for example, if the call returns xml (char *), and I could parse the answer with xml parser.

**Comment by michalvasko** [comment]
Oh, so you are trying to hack *libnetconf2* into parsing an invalid XML, you should have specified that explicitly. Well, I do not think it will be that simple because the API in this case is straightforward, you can only receive a correct reply. So you would have to basically code the whole `nc_recv_reply()` yourself. Also, you are, of course, free to change *libnetconf2* however you like but official API stays the way it is, no (valid) reason to change it.

Regards,
Michal

**Comment by DubHokku** [comment]
and this is true. but not quite like that, it’s not in my interests to hack anything, and as you can see the namespace "xmlns: junos" is indicated in `<rpc-reply>`

```
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/18.4R2/junos" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <lldp-neighbors-information junos:style="detail">
  </lldp-neighbors-information>
</rpc-reply>
```

maybe calling `nc_recv_reply()` might take that into account?

**Comment by michalvasko** [comment]
I am sorry but there is nothing to take into account. The reply __must__ be parsed according to XML rules and there is nothing vague there. In this XML the namespace of `lldp-neighbors-information` is `urn:ietf:params:xml:ns:netconf:base:1.0` and it would be incorrect to parse it in any other way. You can only report the problem to the server developers and there is nothing we can do on the client-side to fix it.

Regards,
Michal

**Comment by DubHokku** [comment]
Thanks

--
Regards,
Hokku
