### ISSUE TITLE
Linker error: cannot find -lssh_threads

### ISSUE THREAD

**Issue by DocDriven** [CESNET/libnetconf2#232]
I am following the install guide and installed libssh without errors from the master branch. When trying to build libnetconf2, it is unable to find -lssh_threads.

The output of cmake ..
```
-- OPENSSL found, required for TLS
-- LIBSSH_VERSION_MAJOR not found in /usr/local/include/libssh/libssh.h, assuming libssh is too old
-- LibSSH version  found
-- Missing tools (devscripts, debhelper package) for building DEB package.
-- Missing tools (rpm package) for building RPM package.
-- valgrind executable not found! Disabling memory leaks tests
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/libnetconf2/build

```
The error message during make (I only use the defaults):
```
[  2%] Built target compat
[  4%] Linking C shared library libnetconf2.so
/usr/bin/ld: cannot find -lssh_threads
collect2: error: ld returned 1 exit status
CMakeFiles/netconf2.dir/build.make:385: recipe for target 'libnetconf2.so.1.3.5' failed
make[2]: *** [libnetconf2.so.1.3.5] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/netconf2.dir/all' failed
make[1]: *** [CMakeFiles/netconf2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
Is this a known issue and is related to libnetconf2 or libssh?

**Comment by michalvasko** [comment]
Hi,
please try the attached patch and please paste the `cmake` output with it. Thanks.

Regards,
Michal

[libssh_fix.patch.txt](https://github.com/CESNET/libnetconf2/files/4650960/libssh_fix.patch.txt)

**Comment by brchiu** [comment]
hi @DocDriven , if you use the latest libssh git repository, I found that a recent commit of libssh [bee8ed82abb](https://git.libssh.org/projects/libssh.git/commit/?id=bee8ed82abbc1ee8c631691a131c3d6ec6ba0836) which moves LIBSSH_VERSION_MAJOR ... etc from `libssh.h` to a separate `libssh_version.h`. So `FindLibSSH.cmake` might need to be revised for future libssh version. Perhaps you can use libssh 0.9.2 tag instead.

**Comment by michalvasko** [comment]
@brchiu That is what I also learned and it should accounted for if you apply the patch I provided. I just have not tested it because I would have to install the latest *libssh* version and mess up my environment, which I would prefer to avoid.

**Comment by brchiu** [comment]
@michalvasko , your patch works, thanks.

**Comment by brchiu** [comment]
@michalvasko , netopeer2 might also need similar patch. FYI.

**Comment by michalvasko** [comment]
Okay, thanks for testing and it and yes, I know, I just wanted to make sure it works first.

Regards,
Michal

**Comment by DocDriven** [comment]
It might be a bit of a dumb question, but I think I am doing something wrong. Please bear with me, but I am not experienced with patching stuff.

I applied the patch like this:
```
root@localhost:/workspace/libnetconf2# patch -b < libssh_fix.patch 
patching file CMakeLists.txt
Reversed (or previously applied) patch detected!  Assume -R? [n] y
can't find file to patch at input line 37
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/CMakeModules/FindLibSSH.cmake b/CMakeModules/FindLibSSH.cmake
|index 4fde899..cdaae38 100644
|--- a/CMakeModules/FindLibSSH.cmake
|+++ b/CMakeModules/FindLibSSH.cmake
--------------------------
File to patch: ./CMakeModules/FindLibSSH.cmake
patching file ./CMakeModules/FindLibSSH.cmake
The next patch would delete the file FindPackageVersionCheck.cmake,
which does not exist!  Assume -R? [n] y
patching file FindPackageVersionCheck.cmake
```
This seems to be okay, as the output of cmake .. shows it found a libssh version:
```
root@localhost:/workspace/libnetconf2/build# cmake ..
-- OPENSSL found, required for TLS
-- Found LibSSH: /usr/local/include (found suitable version "0.8.90", minimum required is "0.7.0") 
-- LibSSH version  found
-- Missing tools (devscripts, debhelper package) for building DEB package.
-- Missing tools (rpm package) for building RPM package.
-- valgrind executable not found! Disabling memory leaks tests
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/libnetconf2/build
```
Executing make still throws an error:
```
root@localhost:/workspace/libnetconf2/build# make
[  2%] Built target compat
[  4%] Linking C shared library libnetconf2.so
/usr/bin/ld: cannot find -lssh_threads
collect2: error: ld returned 1 exit status
CMakeFiles/netconf2.dir/build.make:385: recipe for target 'libnetconf2.so.1.3.5' failed
make[2]: *** [libnetconf2.so.1.3.5] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/netconf2.dir/all' failed
make[1]: *** [CMakeFiles/netconf2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
Your help is appreciated! Thanks

**Comment by michalvasko** [comment]
Hi,
in the meantime I have committed the patch so please do not patch anything, just take a clean current `devel` and it should work.

Regards,
Michal

**Comment by DocDriven** [comment]
Hi Michal,
that worked. Thanks for the help!

Closing this issue.
