### ISSUE TITLE
How to port libnetconf 2 to embedded platform through arm-linux-gcc?

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [CESNET/libnetconf2#238]
As the title。

**Comment by michalvasko** [comment]
Hi,
I am not sure what exactly are you asking. The platform itself should not matter as long as it is running Linux, just compile it normally.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> 嗨，
> 我不确定您到底在问什么。只要平台运行Linux，平台本身就不重要，只需正常编译即可。
> 
> 问候，
> 米哈尔

![image](https://user-images.githubusercontent.com/60098441/84865977-ae656c00-b0ab-11ea-83be-2953339ec394.png)

**Comment by kuailedeluojie-sudo** [comment]
> Hi,
> I am not sure what exactly are you asking. The platform itself should not matter as long as it is running Linux, just compile it normally.
> 
> Regards,
> Michal

![image](https://user-images.githubusercontent.com/60098441/84866040-c0470f00-b0ab-11ea-8c3e-2a85199c6394.png)


For example, I want to compile programs on the arm platform on the X86 platform. Through cross compilation, now when compiling libssh, there are problems as shown in the above figure.

**Comment by michalvasko** [comment]
Oh, you want to cross-compile. Then it is best to use some tools for that (such as [buildroot](https://buildroot.org/)). But you are on your own when cross-compiling *libssh* (obviously, it is not our project) and I cannot really help you even with our projects as I have no experience with cross-compiling.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> Oh, you want to cross-compile. Then it is best to use some tools for that (such as [buildroot](https://buildroot.org/)). But you are on your own when cross-compiling _libssh_ (obviously, it is not our project) and I cannot really help you even with our projects as I have no experience with cross-compiling.
> 
> Regards,
> Michal

hi,
The purpose of compiling libssh is to compile this project.
