### ISSUE TITLE
ODL restart, Netopeer2-server  sometimes can't reconnect to ODL again with Callhome mode .

### ISSUE THREAD

**Issue by qjwu888** [CESNET/libnetconf2#241]
Hi Michal,
libnetconf-1.1.13
libssh-0.7.6

1. Callhome mode ,my device connect to ODL  with LTE network .
2. Stop ODL process，and start it again. 
3. My device should reconnect to ODL.
4. The right log as following.   **loglevel is 2**
root@gpn-000FE9AABB03:~# [2020/07/13 20:24:16.356086, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (131)
[2020/07/13 20:24:16.356552, 1] ssh_socket_exception_callback:  Socket error: Connection reset by peer
[ERR]: LN: Session 10: SSH channel poll error (Socket error: Connection reset by peer).
[INF]: NP: Session 10: thread 1 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: LN: Call Home client "default-client" session terminated, reconnecting...
[INF]: LN: Trying to connect via IPv4 to 192.168.10.123:6666.
[INF]: LN: Successfully connected to 192.168.10.123:6666 over IPv4.
[INF]: SR: Session 1161 (user "root") created.
[ERR]: LN: SSH key exchange timeout.
[INF]: LN: Trying to connect via IPv4 to 192.168.10.123:6666.

**5. But sometimes .my device can't reconnect again.
Higher probability when the network environment is poor。
The error log as following:  loglevel is 0
only as
netopeer2-server[6598]: Session 6: SSH channel poll error (Socket error: disconnected).
Or
netopeer2-server[8348]: Session 1: SSH channel poll error (Socket error: Connection reset by peer).**

**Comment by michalvasko** [comment]
Hi,
I see, so you are saying it fails to reconnect only sometimes? In that case all would point to a small timeout somewhere. Could you please increase it and let us know whether it helped? [This](https://github.com/CESNET/libnetconf2/blob/master/src/session_p.h#L306) should be the one although it is currently on 10 seconds, which seems plenty to me.

It is also possible that the connection is terminated while you are trying to connect again, in which case there is nothing to do. But even on error, the server tries to connect again, right?

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
1. it fails to reconnect only sometimes?
Yes.
2. It is also possible that the connection is terminated while you are trying to connect again, in which case there is nothing to do. But even on error, the server tries to connect again, right?
Yes, the server should try to reconnect. 
3. NC_TRANSPORT_TIMEOUT     10000--->20000, I am testing.
