### ISSUE TITLE
Cleanup of allocated password

### ISSUE THREAD

**Issue by rakichinni** [CESNET/libnetconf2#243]
Hi,

```
char* newPassword(const char *username, const char *hostname, void *priv))
{
   char* ch = malloc(100);
   strcpy(ch, "temp123");
   return ch;
}
```
```
nc_client_ssh_ch_set_auth_password_clb(newPassword, "temp");
```
[Documentation](https://netopeer.liberouter.org/doc/libnetconf2/devel/group__client__ch__ssh.html#ga5f412690a74246c8accbdf4a9fabda38) says **Caller is responsible for freeing the private data when necessary**.
- Does this mean allocated memory to hold a password ('ch') has to be cleaned by the caller?

In large deployments, we may be accepting and closing sessions so many.

Thanks,
Chinni

**Comment by rakichinni** [comment]
Please clarify if anyone has any idea on this. I couldn't exactly find this in libnetconf or libssh.

Even though the allocated memory is less if a huge number of sessions are established then we may land into issues. Just wanted to clarify whether the caller is responsible to destroy or libnetconf will take care of the returned memory.

Thanks in advance.

-Chinni

**Comment by michalvasko** [comment]
Hi,
of course you do not need to free the returned string, there is no natural way of doing so. *libnetconf2* will handle that for you (if not, it is a bug).

Regards,
Michal

**Comment by rakichinni** [comment]
The cleanup of the password is taken care of by the ssh-client. SO there is no bug in ssh sources.

Thanks,
Chinni
