### ISSUE TITLE
Got 'too many open files' error when callhome to a non-accessed address.

### ISSUE THREAD

**Issue by ryanking8215** [CESNET/libnetconf2#244]
I hava found a problem that if the callhome address is configured as a non-accessed address. After a while, netopeer2-server will report "Could not set TCP_NODELAY socket option (Bad file descriptor).", and in a some minutes, it will report "too many open files", it seems to open too many sockets. 

I read the client connecting code in libnetconf2 file  src/session_client.c:_non_blocking_connect(), I found I got error(ETIMEDOUT), but the source code just handle error == ECONNREFUSED only. 

Should error ETIMEDOUT be handled too?

**Comment by michalvasko** [comment]
Hi,
makes sense to handle all the errors so you can try now but I am not sure it will really help. But it might.

Regards,
Michal

**Comment by ryanking8215** [comment]
Sorry, it is not the error check issue, it is about fd leaking.
I am using libnetconf2-1.1.26.

I think I found the problem:

in nc_sock_connect, if we pass *sock_pending=-1, and timeout=5, and host and port are set to a non-accessed address. (these arguments are got when netopeer2-server running, I debug libnetconf2 only). 
__non_blocking_connect() will return -1 to sock, and *sock_pending will be got the real socket(fd).  
but (sock == -1 && (!sock_pending || *sock_pending==-1) will not be matched, it  goes to next, next is set TCP_NODELAY, because sock is -1, so it go to error label.
In error label, it doesn't close the real socket, instead it set *sock_pending=-1, and leak the fd.

**Comment by michalvasko** [comment]
Hi,
could you please try this patch? We got this functionality as a pull request so I am not completely sure this is correct but based on the comments I think it may be. Thanks.

```patch
diff --git a/src/session_client.c b/src/session_client.c
index 6a07473..d349c75 100644
--- a/src/session_client.c
+++ b/src/session_client.c
@@ -1380,9 +1380,14 @@ nc_sock_connect(const char *host, uint16_t port, int timeout, struct nc_keepaliv
 
         for (res = res_list; res != NULL; res = res->ai_next) {
             sock = _non_blocking_connect(timeout, sock_pending, res, ka);
-            if (sock == -1 && (!sock_pending || *sock_pending == -1)) {
-                /* try the next resource */
-                continue;
+            if (sock == -1) {
+                if (!sock_pending || *sock_pending == -1) {
+                    /* try the next resource */
+                    continue;
+                } else {
+                    /* timeout, keep pending socket */
+                    return -1;
+                }
             }
             VRB("Successfully connected to %s:%s over %s.", host, port_s, (res->ai_family == AF_INET6) ? "IPv6" : "IPv4");
```

Regards,
Michal

**Comment by ryanking8215** [comment]
Yes, I tried this patch, it didn't leak fd anymore.

**Comment by michalvasko** [comment]
Okay then, I have committed it.

Regards,
Michal
