### ISSUE TITLE
Support for connecting via Unix sockets

### ISSUE THREAD

**Issue by syyyr** [CESNET/libnetconf2#245]
Hello,

I'm currently migrating our NETCONF stack to the non-legacy versions of sysrepo/libnetconf2/Netopeer2, but found out that the new libnetconf2 (and Netopeer2) no longer support connecting via Unix sockets. In the old versions I was using this type of connection to test my NETCONF interface, because I don't have an SSH interface yet.

Will the next-gen versions of the NETCONF stack support Unix socket connections?

Thanks

**Comment by michalvasko** [comment]
Hi,
what makes you think Unix sockets are no longer supported?

Regards,
Michal

**Comment by syyyr** [comment]
For some reason I couldn't find the nc_connect_unix function in the docs, but now it's there. Weird. I must have made some mistake, sorry.
