### ISSUE TITLE
libnetconf 1.1.26 depend on libyang v??

### ISSUE THREAD

**Issue by zyboy2000** [CESNET/libnetconf2#246]
i read release note
 libnetonf2 v1.1.26 depends on  libyang v1.0.167
 netopeer2 v1.1.39 depends on libyang v1.0.184 libnetconf2 v1.1.26 sysrepo v1.4.70

**Comment by michalvasko** [comment]
Hi,
and why exactly do you find that weird? It simply means that if you use only *libnetconf2*, you are fine with *libyang* 1.0.167 but if you are also using *netopeer2*, you need an updated *libyang* 1.0.184. Generally, you should always use the latest *libyang* to avoid any possible problems.

Regards,
Michal

**Comment by zyboy2000** [comment]
Ok,thanks!

in sysrepo0.7.8 I can set FILE_FORMAT_EXT=lyb，or xml or jason in cmakelist.txt, in sysrepo 1.4.66.how to set?

**Comment by michalvasko** [comment]
Hi,
you cannot change the file format in *sysrepo* 1.x as there is no reason to. You can always use `yanglint` to read LYB files and print them in XML/JSON.

Regards,
Michal

**Comment by zyboy2000** [comment]
in sysrepo 0.x , i set FILE_FORMAT_EXT=lyb as default format ;   when i update sysrepo 1.x , how to set "lyb" as default format ,so program smooth upgrade.

**Comment by michalvasko** [comment]
Oh, it is now `lyb` by default and cannot be changed. Nevertheless, it will not help you much for a "smooth upgrade", there are way too many changes. You are best starting with a fresh installation and using `sysrepocfg` to import the old data manually.

Regards,
Michal
