### ISSUE TITLE
libnetconf2 usage

### ISSUE THREAD

**Issue by Rohit2387** [CESNET/libnetconf2#247]
Hi,

is there any example code available to start with simple Server implementation with get-config without need of storing in DB instead it will be in memory?

Br
Rohit

**Comment by michalvasko** [comment]
Hi,
this is not possible, *libnetconf2* includes only NETCONF RPC processing but no datastore. *sysrepo* is (the only to my knowledge) an implementation of a YANG datastore and *netopeer2* simply connects these 2 libraries into a working application.

**Comment by Rohit2387** [comment]
Hi,

yes i dont want data store just parsing and listening for incoming netconf rpc. Is there any example API usage ? for example :
netconf_api_start_server
netconf_api_install_certificate
netconf_parse_rpc...
netconf_send_rpc_repsonse?

Br
Rohit

**Comment by michalvasko** [comment]
Hi,
no, unfortunately there are no examples, but all the API functions should be well-documented. Also, you can look into *netopeer2* code for a complex example.
