### ISSUE TITLE
macos can't find 'shadow.h'

### ISSUE THREAD

**Issue by qin-nz** [CESNET/libnetconf2#25]
Hi, I want to compile libnetconf2 on macos using following command.
```
cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ..
make
```

CMake can be done with waring CMP0042.
But when I try to make it, shadow.h can't be find.

```
[  4%] Building C object CMakeFiles/netconf2.dir/src/session_server_ssh.c.o
/Users/dy/Source/CESNET/libnetconf2/src/session_server_ssh.c:23:10: fatal error: 'shadow.h' file not found
#include <shadow.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/netconf2.dir/src/session_server_ssh.c.o] Error 1
make[1]: *** [CMakeFiles/netconf2.dir/all] Error 2
```

**Comment by michalvasko** [comment]
Hi,
I am sorry, but OSX is not officially supported, so there are some issues. In this case we would have to rewrite the code that handles system user information, which is obviously performed differently. You are welcome to send a patch, but we will not be implementing this.

Regards,
Michal

**Comment by rkrejci** [comment]
I'm reopening this to keep it in mind, maybe there will be someone who will fix this for macos.
