### ISSUE TITLE
leaf-list - complains if the values are not unique

### ISSUE THREAD

**Issue by som-1981** [CESNET/libnetconf2#251]
We are using :
sysrepod ver : 0.7.4
Netopeer2 ver : v0.5-r1(0.5.31)
The table mentioned is of type leaf-list in yang. 
Netopeer server rejects this with reason code(Validation of the changes failed). The table as duplicate values. This should be allowed as per RFC 7950
```xml
<table>0</table>         <table>1</table>           <table>2<table>           <table>3</table>         <table>4</table>           <table>5</table>           <table>6</table>         <table>4</table>           <table>8</table>           <table>9</table>
```
--

**Comment by som-1981** [comment]
<table>0</table>
      <table>1</table>
      <table>2</table>
      <table>3</table>
      <table>4</table>
      <table>5</table>
      <table>6</table>
      <table>4</table>
      <table>8</table>
      <table>9</table>

**Comment by michalvasko** [comment]
Hi,
firstly, you are using a really old *sysrepo*/*netopeer2* version so I will not provide much support. Secondly, why do you think such a configuration is valid? As long as the leaf-list is configuration (`config` `true`), these data are not valid.

**Comment by som-1981** [comment]
Thanks for response.  The table is of type leaf-list and read-only.

**Comment by michalvasko** [comment]
Hi,
it seems similar instance were allowed only in YANG 1.1 so if you specify that your YANG uses this version, it should work.

**Comment by som-1981** [comment]
Hi,
The yang has version as 1.1 in the yang file but still we see issues where duplicate values are not allowed in table.

**Comment by michalvasko** [comment]
Hi,
it works fine with the current *libyang* so please update it. However, it is quite likely your legacy versions will not compile with it so it is up to you how you want to solve this.
