### ISSUE TITLE
One-way authentication using TLS

### ISSUE THREAD

**Issue by rakichinni** [CESNET/libnetconf2#252]
Hi,

Verified and able to establish a Netconf session over TLS.

The current implementation does two-way authentication which means 'server authenticates client' and 'client authenticates server'.

Am planning to implement one-way authentication in which only the client authenticates the server. Do we have any switch/option to achieve only one-way authentication - "client authenticates server"?

Any suggestions if anyone tried and achieved the same. (this is something similar to web browser authenticates web-server using certs)

Thanks,
Chinni

**Comment by michalvasko** [comment]
Hi,
of course, you are free to implement whatever you want but this would not be a compliant [NETCONF over TLS](https://tools.ietf.org/html/rfc7589) implementation. Also, the client certificate is used for `cert-to-name` that will get you the NETCONF username, I do not know how you plan to learn it in a secure way.

**Comment by rakichinni** [comment]
Hi,

Thanks for pointing about authorization based on cert-to-name.
We are planning to have only one global level of authorization which means 'every Netconf session is going to have the same level of authorization'.

Please let us know the complexity and amount of change needed to achieve one-way auth. If possible, could you please point me to a piece of code.

While going through the SSL documentation observed that ```SSL_CTX_set_verify``` performs peer authentication.
From libnetconf, we have below piece of code,
```SSL_CTX_set_verify(tls_ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT, nc_tlsclb_verify);```

Thanks,
Chinni

**Comment by michalvasko** [comment]
Hi,
I do not remember much from OpenSSL so you will have to go through it all yourself. But, obviously, you do not need this callback, which basically only for `cert-to-name`.

**Comment by rakichinni** [comment]
Thanks.

We achieved this with very little changes (at the client and server) that removed client authentication and cert-to-username mapping required for authorization.

**Comment by nickbroon** [comment]
@rakichinni are you able to share your change for one-way auth?
