### ISSUE TITLE
LIBSSH not found during compilation process

### ISSUE THREAD

**Issue by aswin19996** [CESNET/libnetconf2#255]
Hi, 

I am facing issues upon issuing the command **cmake -D CMAKE_BUILD_TYPE:String="Release" ..** in the build folder created after extracting libnetconf2.

The Error is as below:

-- OPENSSL found, required for TLS
CMake Error at CMakeModules/FindLibSSH.cmake:74 (file):
  file STRINGS file "/usr/include/libssh/libssh.h" cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:153 (find_package)

-- LIBSSH_VERSION_MAJOR not found, assuming libssh is too old and cannot be used!
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibSSH (missing: LIBSSH_INCLUDE_DIRS LIBSSH_LIBRARIES)
  (Required is at least version "0.7.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLibSSH.cmake:113 (find_package_handle_standard_args)
  CMakeLists.txt:153 (find_package)

I have also successfully installed the latest libssh version 0.9.5 in my system.
Could someone please guide me on how to solve this issue?

**Comment by michalvasko** [comment]
Hi,
the relevant error is
```
file STRINGS file "/usr/include/libssh/libssh.h" cannot be read.
```
but I do not know what causes it. I have just updated to *libssh* 0.9.5 and it worked just fine for me. Does the user you are running `cmake` with have access to `/usr/include/libssh/libssh.h`? Every should should be able to read that file, though.
