### ISSUE TITLE
How to avoid selection of cipher suite based on ( EC ) DHE in TLS Handshake Protocol

### ISSUE THREAD

**Issue by robbynet** [CESNET/libnetconf2#256]
Hello,
In the last standard version of libnetconf2, we can see a list of 18 cipher suite having (EC) DHE in the Client Hello.
- Wonder how to remove those 18 Cipher Suite of the Client Hello in the Handshake protocol ?
- Or either how to avoid Server Hello selecting one of then ?
I suspect that a knife on Client side should likely be more straightforward than on Server side.
The point is that I did not succeed to find out where to perform such knife in the libnetconf2 implementation !
=> Does someone should be able to help me to perform this modification in the libnetconf2 implementation ?
Regards.
Christian.

**Comment by michalvasko** [comment]
All these ciphers and algorithms are fully in control of *libssh* so that is what you need to change. It should read the OpenSSH client and server config files so that is probably what you should look at and modify.

**Comment by robbynet** [comment]
Thanks for your support, I confirm that Cipher Suite and TLS version can be tuned on NETCONF Client side using /etc/ssl/opensssl.cnf

**Comment by michalvasko** [comment]
Okay, thanks for the information, it may come handy for other users.
