### ISSUE TITLE
cmake errors when compiling libnetconf2

### ISSUE THREAD

**Issue by tcnyambira** [CESNET/libnetconf2#257]
I encountered the following issues when I did cmake for compiling libnetconf2 but I had successfully compiled libssh and libssh.h is present at usr/local/include/libssh/libssh.h

-- LIBSSH_VERSION_MAJOR not found in /usr/local/include/libssh/libssh.h, assuming libssh is too old
-- Performing Test HAVE_LIBSSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES
-- Performing Test HAVE_LIBSSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES - Failed
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

**Comment by michalvasko** [comment]
What *libnetconf2* version are you using? What *libssh* version have you installed?
