### ISSUE TITLE
make test failures 

### ISSUE THREAD

**Issue by tcnyambira** [CESNET/libnetconf2#258]
make test returned the following errors in the process of building libnetconf2. How can I fix these errors.

The following tests FAILED:
	  7 - test_server_thread (Failed)
	 18 - test_server_thread_valgrind (Failed)
Errors while running CTest
Makefile:129: recipe for target 'test' failed

**Comment by michalvasko** [comment]
Can you please at least provide the output of the test, so that I know why it failed?

**Comment by tcnyambira** [comment]
Plesase find below make and make test output

root@NTSimulator:~/ntsim-master/libnetconf2/build# make
Scanning dependencies of target compat
[  2%] Building C object CMakeFiles/compat.dir/compat/compat.c.o
[  2%] Built target compat
Scanning dependencies of target netconf2
[  4%] Building C object CMakeFiles/netconf2.dir/src/io.c.o
[  6%] Building C object CMakeFiles/netconf2.dir/src/log.c.o
[  8%] Building C object CMakeFiles/netconf2.dir/src/messages_client.c.o
[ 10%] Building C object CMakeFiles/netconf2.dir/src/messages_server.c.o
[ 12%] Building C object CMakeFiles/netconf2.dir/src/session.c.o
[ 14%] Building C object CMakeFiles/netconf2.dir/src/session_client.c.o
[ 16%] Building C object CMakeFiles/netconf2.dir/src/session_server.c.o
[ 18%] Building C object CMakeFiles/netconf2.dir/src/time.c.o
[ 20%] Building C object CMakeFiles/netconf2.dir/src/session_client_ssh.c.o
/home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c: In function ‘sshauth_hostkey_check’:
/home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:292:5: warning: ‘ssh_is_server_known’ is deprecated [-Wdeprecated-declarations]
     state = ssh_is_server_known(session);
     ^~~~~
In file included from /home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:40:0:
/usr/local/include/libssh/libssh.h:550:31: note: declared here
 SSH_DEPRECATED LIBSSH_API int ssh_is_server_known(ssh_session session);
                               ^~~~~~~~~~~~~~~~~~~
/home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:428:17: warning: ‘ssh_write_knownhost’ is deprecated [-Wdeprecated-declarations]
                 ret = ssh_write_knownhost(session);
                 ^~~
In file included from /home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:40:0:
/usr/local/include/libssh/libssh.h:548:31: note: declared here
 SSH_DEPRECATED LIBSSH_API int ssh_write_knownhost(ssh_session session);
                               ^~~~~~~~~~~~~~~~~~~
[ 22%] Building C object CMakeFiles/netconf2.dir/src/session_server_ssh.c.o
[ 25%] Building C object CMakeFiles/netconf2.dir/src/session_client_tls.c.o
[ 27%] Building C object CMakeFiles/netconf2.dir/src/session_server_tls.c.o
[ 29%] Linking C shared library libnetconf2.so
[ 29%] Built target netconf2
Scanning dependencies of target testobj
[ 31%] Building C object tests/CMakeFiles/testobj.dir/__/src/io.c.o
[ 33%] Building C object tests/CMakeFiles/testobj.dir/__/src/log.c.o
[ 35%] Building C object tests/CMakeFiles/testobj.dir/__/src/messages_client.c.o
[ 37%] Building C object tests/CMakeFiles/testobj.dir/__/src/messages_server.c.o
[ 39%] Building C object tests/CMakeFiles/testobj.dir/__/src/session.c.o
[ 41%] Building C object tests/CMakeFiles/testobj.dir/__/src/session_client.c.o
[ 43%] Building C object tests/CMakeFiles/testobj.dir/__/src/session_server.c.o
[ 45%] Building C object tests/CMakeFiles/testobj.dir/__/src/time.c.o
[ 47%] Building C object tests/CMakeFiles/testobj.dir/__/src/session_client_ssh.c.o
/home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c: In function ‘sshauth_hostkey_check’:
/home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:292:5: warning: ‘ssh_is_server_known’ is deprecated [-Wdeprecated-declarations]
     state = ssh_is_server_known(session);
     ^~~~~
In file included from /home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:40:0:
/usr/local/include/libssh/libssh.h:550:31: note: declared here
 SSH_DEPRECATED LIBSSH_API int ssh_is_server_known(ssh_session session);
                               ^~~~~~~~~~~~~~~~~~~
/home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:428:17: warning: ‘ssh_write_knownhost’ is deprecated [-Wdeprecated-declarations]
                 ret = ssh_write_knownhost(session);
                 ^~~
In file included from /home/tn/ntsim-master/libnetconf2/src/session_client_ssh.c:40:0:
/usr/local/include/libssh/libssh.h:548:31: note: declared here
 SSH_DEPRECATED LIBSSH_API int ssh_write_knownhost(ssh_session session);
                               ^~~~~~~~~~~~~~~~~~~
[ 50%] Building C object tests/CMakeFiles/testobj.dir/__/src/session_server_ssh.c.o
[ 52%] Building C object tests/CMakeFiles/testobj.dir/__/src/session_client_tls.c.o
[ 54%] Building C object tests/CMakeFiles/testobj.dir/__/src/session_server_tls.c.o
[ 54%] Built target testobj
Scanning dependencies of target test_init_destroy_server
[ 56%] Building C object tests/CMakeFiles/test_init_destroy_server.dir/test_init_destroy_server.c.o
[ 58%] Linking C executable test_init_destroy_server
[ 58%] Built target test_init_destroy_server
Scanning dependencies of target test_init_destroy_client
[ 60%] Building C object tests/CMakeFiles/test_init_destroy_client.dir/test_init_destroy_client.c.o
[ 62%] Linking C executable test_init_destroy_client
[ 62%] Built target test_init_destroy_client
Scanning dependencies of target test_time
[ 64%] Building C object tests/CMakeFiles/test_time.dir/test_time.c.o
[ 66%] Linking C executable test_time
[ 66%] Built target test_time
Scanning dependencies of target test_client_thread
[ 68%] Building C object tests/CMakeFiles/test_client_thread.dir/test_client_thread.c.o
[ 70%] Linking C executable test_client_thread
[ 70%] Built target test_client_thread
Scanning dependencies of target test_client_ssh
[ 72%] Building C object tests/CMakeFiles/test_client_ssh.dir/client/test_client_ssh.c.o
[ 75%] Linking C executable test_client_ssh
[ 75%] Built target test_client_ssh
Scanning dependencies of target test_fd_comm
[ 77%] Building C object tests/CMakeFiles/test_fd_comm.dir/test_fd_comm.c.o
[ 79%] Linking C executable test_fd_comm
[ 79%] Built target test_fd_comm
Scanning dependencies of target test_io
[ 81%] Building C object tests/CMakeFiles/test_io.dir/test_io.c.o
[ 83%] Linking C executable test_io
[ 83%] Built target test_io
Scanning dependencies of target test_server_thread
[ 85%] Building C object tests/CMakeFiles/test_server_thread.dir/test_server_thread.c.o
[ 87%] Linking C executable test_server_thread
[ 87%] Built target test_server_thread
Scanning dependencies of target test_client
[ 89%] Building C object tests/CMakeFiles/test_client.dir/client/test_client.c.o
[ 91%] Linking C executable test_client
[ 91%] Built target test_client
Scanning dependencies of target test_client_messages
[ 93%] Building C object tests/CMakeFiles/test_client_messages.dir/client/test_client_messages.c.o
[ 95%] Linking C executable test_client_messages
[ 95%] Built target test_client_messages
Scanning dependencies of target test_client_tls
[ 97%] Building C object tests/CMakeFiles/test_client_tls.dir/client/test_client_tls.c.o
[100%] Linking C executable test_client_tls
[100%] Built target test_client_tls



root@NTSimulator:~/ntsim-master/libnetconf2/build# make test
Running tests...
Test project /home/tn/ntsim-master/libnetconf2/build
      Start  1: test_io
 1/22 Test  #1: test_io .............................   Passed    0.07 sec
      Start  2: test_fd_comm
 2/22 Test  #2: test_fd_comm ........................   Passed    0.23 sec
      Start  3: test_init_destroy_client
 3/22 Test  #3: test_init_destroy_client ............   Passed    0.00 sec
      Start  4: test_init_destroy_server
 4/22 Test  #4: test_init_destroy_server ............   Passed    0.01 sec
      Start  5: test_time
 5/22 Test  #5: test_time ...........................   Passed    0.00 sec
      Start  6: test_client_thread
 6/22 Test  #6: test_client_thread ..................   Passed    0.01 sec
      Start  7: test_server_thread
 7/22 Test  #7: test_server_thread ..................***Failed    0.10 sec
      Start  8: test_client
 8/22 Test  #8: test_client .........................   Passed    0.00 sec
      Start  9: test_client_messages
 9/22 Test  #9: test_client_messages ................   Passed    0.00 sec
      Start 10: test_client_ssh
10/22 Test #10: test_client_ssh .....................   Passed    0.04 sec
      Start 11: test_client_tls
11/22 Test #11: test_client_tls .....................   Passed    0.02 sec
      Start 12: test_io_valgrind
12/22 Test #12: test_io_valgrind ....................   Passed    1.96 sec
      Start 13: test_fd_comm_valgrind
13/22 Test #13: test_fd_comm_valgrind ...............   Passed    1.90 sec
      Start 14: test_init_destroy_client_valgrind
14/22 Test #14: test_init_destroy_client_valgrind ...   Passed    0.73 sec
      Start 15: test_init_destroy_server_valgrind
15/22 Test #15: test_init_destroy_server_valgrind ...   Passed    1.23 sec
      Start 16: test_time_valgrind
16/22 Test #16: test_time_valgrind ..................   Passed    0.82 sec
      Start 17: test_client_thread_valgrind
17/22 Test #17: test_client_thread_valgrind .........   Passed    0.76 sec
      Start 18: test_server_thread_valgrind
18/22 Test #18: test_server_thread_valgrind .........***Failed    8.09 sec
      Start 19: test_client_valgrind
19/22 Test #19: test_client_valgrind ................   Passed    0.75 sec
      Start 20: test_client_messages_valgrind
20/22 Test #20: test_client_messages_valgrind .......   Passed    0.80 sec
      Start 21: test_client_ssh_valgrind
21/22 Test #21: test_client_ssh_valgrind ............   Passed    1.46 sec
      Start 22: test_client_tls_valgrind
22/22 Test #22: test_client_tls_valgrind ............   Passed    1.76 sec

91% tests passed, 2 tests failed out of 22

Total Test time (real) =  20.76 sec

The following tests FAILED:
	  7 - test_server_thread (Failed)
	 18 - test_server_thread_valgrind (Failed)
Errors while running CTest
Makefile:129: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by michalvasko** [comment]
Please, instead of `make test`, run `ctest --output-on-failure`, for example. Then paste the output.

**Comment by tcnyambira** [comment]
Hi Michal,
Thanks for your efforts to help. Kindly find attached the ctest output
[ctest output.txt](https://github.com/CESNET/libnetconf2/files/5313034/ctest.output.txt)

**Comment by michalvasko** [comment]
It seems that DSA keys are not supported on your platform. That is fairly common now and they were updated quite some time ago so you must be using an old version of *netopeer2*.
