### ISSUE TITLE
enumeration - range

### ISSUE THREAD

**Issue by som-1981** [CESNET/libnetconf2#259]
For example, enum TYPE_1 {value 0} and enum TYPE_16 {value 15} 
Can we just give first and last value instead of having   TYPE_2 ,TYPE_3,TYPE_4,TYPE_5,TYPE_6 ........... TYPE_14 and also the  value in yang file.
Thanks,

**Comment by michalvasko** [comment]
All your questions should be answered [here](https://tools.ietf.org/html/rfc7950#section-9.6.4.2).
