### ISSUE TITLE
processing yang-library data instead of <hello> content

### ISSUE THREAD

**Issue by rkrejci** [CESNET/libnetconf2#26]
Client side code currently parses `<hello>` content to get information about the server's schemas and to create libyang context. This way all the schemas are `implemented` on the client side while they are just imported on the server side.

If the server supports `ietf-yang-library` the primary way to get info about the server's schemas should be to get the yang-library data and create context according to it. yang-library data include information if the schema is imported or implemented so the context on the client side will be really the same as on the server side.

**Comment by michalvasko** [comment]
Regarding the `<hello>` message, capabilities should include only `implemented` modules anyway ([old YANG RFC](https://tools.ietf.org/html/rfc6020#section-5.6.4) implies this while not mentioning anything about `imported` modules, [new YANG RFC](https://tools.ietf.org/html/rfc7950#section-5.6.4) is even more brief and seems to rely primarily on `ietf-yang-library` data).
