### ISSUE TITLE
make build-rpm tests fail

### ISSUE THREAD

**Issue by pointerdk** [CESNET/libnetconf2#260]
When I run the "make test" with "-DENABLE_BUILD_TESTS=ON" all the tests pass as they should. However, when I subsequently run "make build-rpm" the tests start failing. See the attached file for build output.

[build-output.txt](https://github.com/CESNET/libnetconf2/files/5391391/build-output.txt)

I'm running CentOS 7 with "scl enable devtools-9".

**Comment by michalvasko** [comment]
That is definitely strange if the tests pass normally but not in the RPM build environment. I do not think I can help as I have never seen this before, some problem occurs during TLS CA certificate verification. Maybe old OpenSSL version is to blame, you can probably just ignore it.

**Comment by pointerdk** [comment]
Okay. Can I trigger til build-rpm without the tests?

**Comment by michalvasko** [comment]
Well, just modify the `cmake` options in the spec file.
