### ISSUE TITLE
How does reduce cpu usage when not message exchanging ?

### ISSUE THREAD

**Issue by foxge** [CESNET/libnetconf2#261]
Hi,

The nc_ps_poll is always polling the status of the session every NC_TIMEOUT_STEP(default 1ms) even though the session is idel, therefore, the CPU usage does not reduce on non-consumption.

Is there any way to reduce the CPU usage ? for example, is there programming API to support epoll mode or reactor mode ?

**Comment by michalvasko** [comment]
This is what [netopeer2 does](https://github.com/CESNET/netopeer2/blob/master/src/main.c#L955) to prevent this problem.

**Comment by foxge** [comment]
OK, thanks.
