### ISSUE TITLE
Requested startTime is later than current time.

### ISSUE THREAD

**Issue by som-1981** [CESNET/libnetconf2#264]
Hello,

The time is synced across all nodes. But still we see this error. Anything we are missing here?

create subscription rpc reply is <netconf:rpc-reply xmlns:netconf="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
  <netconf:rpc-error>
    <netconf:error-type>protocol</netconf:error-type>
    <netconf:error-tag>bad-element</netconf:error-tag>
    <netconf:error-severity>error</netconf:error-severity>
    <netconf:error-message unknown:lang="en">Requested startTime is later than the current time.</netconf:error-message>
    <netconf:error-info>
      <netconf:bad-element>startTime</netconf:bad-element>
    </netconf:error-info>
  </netconf:rpc-error>
</netconf:rpc-reply>

Thanks,

**Comment by michalvasko** [comment]
It seems like the problem mentioned [here](https://tools.ietf.org/html/rfc5277#section-2.1.1), in the `Start Time:` description.

**Comment by som-1981** [comment]
Thanks
