### ISSUE TITLE
libyang[0]: Failed to resolve identityref "iana-if-type:ethernetCsmacd

### ISSUE THREAD

**Issue by som-1981** [CESNET/libnetconf2#265]
Hello,

libyang[0]: Identity found, but in a non-implemented module "iana-if-type".
libyang[0]: Failed to resolve identityref "iana-if-type:ethernetCsmacd". (path: /ietf-interfaces:interfaces/interface[name='eth1']/type)
ERROR: Failed to parse <get> reply.
reply is null
==================================================================================iana-crypt-hash                   | 2014-08-06 | Imported    |                     |             |                               |
mavenir-stats                     | 2016-10-25 | Installed   | admin:admin         | 666         |                               |
ietf-yang-types                   | 2013-07-15 | Imported    |                     |             |                               |
mavenir-events                    | 2016-09-28 | Installed   | admin:admin         | 666         |                               |
iana-hardware                     | 2018-03-13 | Installed   |                     |             |                               |
iana-if-type                      | 2017-01-19 | Installed   |                     |             |                               |
ietf-interfaces                   | 2018-02-20 | Installed   | admin:admin         | 666         |                               | if-mib
ietf-hardware                     | 2018-03-13 | Installed   | admin:admin         | 666         |                               | hardware-state
=================================================================================

We have already installed iana-if-type and iana-hardware..

Thanks,

**Comment by michalvasko** [comment]
Based on the `sysrepoctl -l` output I can see that you are using the legacy software (sysrepo version 0.7.8). We no longer support that and I honestly cannot tell you why this does not work.

**Comment by som-1981** [comment]
We found the problem. The issue was we were using two different yang version for iana-if-type in client and server.
