### ISSUE TITLE
Option to set SSH algorithms

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libnetconf2#266]
Hi,

I need to change the used SSH algorithms in my netconf server based on libnetconf2, but I couldn't find a way to do it.
Is it planned to add support to the API, or make the underlying libssh session accessible to the application?

Thanks!

**Comment by michalvasko** [comment]
Hi,
this is all in the hands of *libssh*, *libnetconf2* does not have any options for this. While it would be possible to set the algorithms in the SSH session, they would get overwritten by the global configuration anyway (you can find mentioned this in their mailing list, if you think it does not make sense then there are at least 3 of us). So, if you set it in the configuration file (probably `/etc/ssh/sshd_config`), it should be used.

**Comment by awesomenode** [comment]
I figured out that libssh looks for the config file on `/etc/ssh/libssh_server_config` path by default and it works.
Thanks!
