### ISSUE TITLE
How do I delete sysrepo database data?

### ISSUE THREAD

**Issue by rydy** [CESNET/libnetconf2#268]
Hi ,
   How can I use the interface provided by libnetconf2 to delete data in sysrepo？Can you give me an example?
thanks
Best regards.

**Comment by michalvasko** [comment]
Hi,
I am not sure you understand the specific purposes of *libnetconf2*, *sysrepo*, and how they interface. You cannot directly do what you are asking, *netopeer2-server* essentially implements the missing functionality. Specifically, if a `edit-config` or `delete-config` RPC is received via NETCONF (processed by *libnetconf2*), the server then calls *sysrepo* API to delete the specific data.

**Comment by rydy** [comment]
I understand that. I can edit the data in the database using the 'nc_rpc_edit' interface, I want to delete the configured data. What interface should I use? Is there an interface for delete-config?

**Comment by michalvasko** [comment]
Well, yes, there is `nc_rpc_delete` (not surprisingly).

**Comment by rydy** [comment]
I got it, thank you very much.
