### ISSUE TITLE
Compilation error while creating simple libetconf based server

### ISSUE THREAD

**Issue by Rohit2387** [CESNET/libnetconf2#274]
Hi,

Whether these 2 header is must to be included for using libnetconf2 ?
#include<libnetconf2/session.h>
#include</root/netconf/libnetconf2-master/src/session_p.h>

And also in this libyang API
lys_set_private(node, my_get_rpc_clb);
it takes 2 input ?
second input is function pointer of which type?

**Comment by michalvasko** [comment]
For *libnetconf2*, you should include either (or even both in some cases) `nc_server.h` or `nc_client.h`, nothing else.

In *libyang* there is this prototype `void *lys_set_private(const struct lys_node *node, void *priv);`, it is up to the application what it puts there (you have probably taken that from *libnetconf2*, not sure how is that relevant).

**Comment by Rohit2387** [comment]
test_server_thread_sample.c:49:35: error: dereferencing pointer to incomplete type
  data = lyd_new_path(NULL, session->ctx, "/ietf-netconf:get-config/data", NULL, LYD_ANYDATA_CONSTSTRING,LYD_PATH_OPT_OUTPUT); 

Above error is coming if I am not including 
#include</root/netconf/libnetconf2-master/src/session_p.h>

**Comment by michalvasko** [comment]
The error is correct, you are not meant to be able to access `struct nc_session` attributes directly. Some are available using getters, though, so simply use `nc_session_get_ctx()` instead.

**Comment by Rohit2387** [comment]
OK Thanks,hope below headerr file are enough to start with simple netconf server using libnetconf2
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <libyang/libyang.h>
#include<nc_server.h>
