### ISSUE TITLE
Netconf client fails to parse <get> reply

### ISSUE THREAD

**Issue by ankit-ka** [CESNET/libnetconf2#277]
We are writing a netconf client software that is establishing netconf with a server and sending a <rpc-get> for ietf-interfaces module, as below:

```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <filter type="xpath" xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces" select="/if:interfaces"/>
    <with-defaults xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">report-all</with-defaults>
  </get>
</rpc>
```

The client seems to be getting a response from the netconf server, but then we see the following error:
```
lnc2_print_clb():nc ERROR: Failed to parse <get> reply
```

**Comment by michalvasko** [comment]
Does the client print any more messages before the one you mentioned? Having increased verbosity to at least `verbose`. You can also print the message the server is sending if you run *netopeer2* with `-c MSG`.

**Comment by ankit-ka** [comment]
Hello Michal, I realized that this issue was observed because the Netconf Server was not sending the schema information to my client. So the client was not having the module information. So I used the "ly_ctx_load_module()" at the client to first load the desired yang modules.
