### ISSUE TITLE
LY: Print error (No such file or directory) during edit config RPC

### ISSUE THREAD

**Issue by kr234** [CESNET/libnetconf2#278]
Sending edit config rpc fails with LY: Print error (No such file or directory). This happens in flow nc_send_rpc->nc_write_msg_io->lyd_print_clb(). Can you provide info on how to resolve this isssue.

lnc2_print_clb():nc VERBOSE: Session[3], sending message:

#209

 lnc2_print_clb():nc VERBOSE:Session[3], sending message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="10"><edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><target><running/></target><default-operation>merge</default-operation><config>

lnc2_print_clb():nc VERBOSE:Session[3], sending message:

#5128

lnc2_print_clb():nc VERBOSE:Session[3], sending message:

<user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
	//all the sent contents gets printed here.
</user-plane-configuration>

Dec:20:19:20:39:389813|error|5418|ncClient.cpp|806|ly_print_clb():ly ERROR: Print error (No such file or directory).

**Comment by michalvasko** [comment]
What exactly are you running? What is `ncClient.cpp`?

**Comment by kr234** [comment]
Hello,

         ncClient.cpp is the client that issues rpcs to the server and  the edit-config rpc is failing with below error

         ERROR: Print error (No such file or directory).]
         msg: failed to send the rpc[3].]

        This issue got resolved by increasing the buffer size in io.c  . 
        Previously it was #define WRITE_BUFSIZE (2 * BUFFERSIZE)  and it was changed to 12 kb  #define WRITE_BUFSIZE (25 * BUFFERSIZE) . 

         Wanted to understand more on this issue. should netconf client need to take care of limiting the data that is sent out to  netconf server.

**Comment by michalvasko** [comment]
> should netconf client need to take care of limiting the data that is sent out to netconf server.

No, this seems like a bug. Could you provide more information on the use-case? Best a way to simply reproduce the error.
