### ISSUE TITLE
Large number of SSH sessions opened one after the other

### ISSUE THREAD

**Issue by catalinvlad192** [CESNET/libnetconf2#284]
Hi!

I have the following issue:
After the first callhome procedure, when a working session is created, another callhome procedure is launched, resulting in a new session, even if the previous session is still working. As the first session is still working, the client deliberately closes the newest session, and the issue repeats, another callhome procedure is launched, another session is created, and then closed, etc.
In the meantime, the client is communicating with the server via the first session, but the waitCallHome thread, where I call nc_accept_callhome() function, detects the new session.
I am using version 0.12.33.
Can you please guide me with this issue?

Thank you very much!
Vlad Catalin

**Comment by michalvasko** [comment]
Unfortunately, I am not able to help. Version 0.12.x is really old and deprecated, we do not provide support for it anymore. To resolve this, you would have to update it.

**Comment by catalinvlad192** [comment]
Thank you!
I will try to update the version.
Have a great day!
