### ISSUE TITLE
malformed-message rpc-reply does not contain message-id

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libnetconf2#289]
Hi,

If I send an invalid get which results in malformed-message error the reply does not contain message-id.

Example for get:
```
<get>
  <filter type="xpath" select="&"/>
</get>
```

Response:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>rpc</error-type>
    <error-tag>malformed-message</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">A message could not be handled because it failed to be parsed correctly.</error-message>
  </rpc-error>
</rpc-reply>
```

If the error is e.g. operation-failed then it has message-id.

Example for get:
```
<get>
  <filter type="xpath" select="#"/>
</get>
```

Response:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="8">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Unexpected character(s) '#' (#).</error-message>
  </rpc-error>
</rpc-reply>
```

Also tried in netopeer docker which had the same result.

libnetconf2 version: 1.1.33
libyang version: 1.0.207

Thanks!

**Comment by michalvasko** [comment]
I am not sure this can be fixed in some reasonable way. Malformed message means the message could not be parsed (was not a valid XML), so I do not think it can be considered to have some `message-id` attribute. The only possibility would be to treat the XML as a string and try to find the element but that is prone to all kinds or errors.

**Comment by awesomenode** [comment]
Thanks for the quick reply. I close the ticket then.
