### ISSUE TITLE
cmake: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rohitkathuria102** [CESNET/libnetconf2#290]
I've trying to compile libnetconf2 for ARM

I've installed the toolkit and set the Compilers as::

export CC=/home/labadmin/rohit/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc

export CXX=/home/labadmin/rohit/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-c++

and 

exported the path ::

export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/home/labadmin/rohit/openssl-1.1.1c:/usr/local/openssl:/usr/local/lib:/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/bin"

now libssl.so.1.1 is at the path :: /usr/local/openssl

despite exporting the path i'm facing this error.
I have added the path /usr/local/openssl/lib to /etc/ld.so.conf and run ldconfig as suggested by this issue::

https://github.com/openssl/openssl/issues/3993

**Comment by michalvasko** [comment]
I cannot really help you as the problem is specific to your environment. Also, this is not a *libnetconf2* issue, the problem is loading a shared library, that is a generic Linux problem.

But I may be able to give you a couple of tips. You should now the problem is fixed when you execute `# ldconfig -p | grep libssl` and you get some output. So, you need to modify `ld` paths to find it and yes, `# ldconfig` command reloads the shared library paths based on the current settings (so you need to run it after making changes for then to actually take effect).

**Comment by Elko-Lemiso** [comment]
Im having the exact same issue on my aws instance, 

After running
`ldconfig -p | grep libssl`

This is what I get 

```
        libssl3.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl3.so
        libssl.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.3
        libssl.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so
```

What I notice is that there is no `libssl.so.1.1` listed, does that account for the error?
And what can I do to modify the `ld` path

**Comment by michalvasko** [comment]
Learn more about how to add searched directories in the manual `ldconfig(8)`.

**Comment by michalvasko** [comment]
What "resources" do you have in mind? I do not understand the question.

**Comment by MiladZarour** [comment]
Hi Guys 
I am having the exact same fail here:

`spl-token create-token
`spl-token: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

does anyone find any solution ??

Thx in advance

**Comment by jktjkt** [comment]
This project is not related to "Solana SPL blockchain"; you're talking to wrong people.

**Comment by kaushikc44** [comment]
On the same ground , trying to use __**spl-token create- token**__ throws the same sort of error.  If anyone has found the error do let me know thanks

**Comment by stevests** [comment]
Hello everyone, I have the same issue then kaushikc44. So if someone could help it would be grateful.

**Comment by michalvasko** [comment]
Please stop reporting whatever problems you have with other projects not authored by us.
