### ISSUE TITLE
Returning special characters in get/get-config rpc replies

### ISSUE THREAD

**Issue by lmartanovic** [CESNET/libnetconf2#291]
Hi guys.

I am implementing a netconf server using your library and have run into an issue with returning a string containing special characters ('\r', '\t', '\n' and the like) from my application.

I put my string data into the data tree using `lyd_new_output_leaf()`. As long as the string does not contain any special characters, everything seems to be working perfectly. However, when my data do contain special characters, these are present verbatim in the replies constructed by `nc_server_reply_data()` (I'd expect special characters to be XML-encoded in the output (e.g. '\n' as &x0A; and so on). This seems not to be the case and the only characters being XML-encoded are '<', '>', '"', and '&'. ) .
This is acceptable, but the '\r' character seems to be changed to '\n' in the rpc-reply recieved by the client (I am sure the string passed as value to lyd_new_output_leaf() does contain '\r'). I tried with two different python-based client implementations and "'\r'" was never returned correctly.

Could you please give me some advice as to how to return strings containing special characters correctly? Is there some way to enable XML-encoding for whitespaces that I missed, be it in libnetconf2 or in libyang? Should I be escaping these characters in a specific manner? If not, I would be OK with the replies containing raw whitespaces, even though it's pretty "ugly", but I'd still like at least the '\r' issue explained if possible.

I tried to look into the sources of both libnetconf2 and libyang and to look over the available documentation, but I still may have missed something. In that case I apologise and would be happy with just being pointed to the relevant source of information.

**Comment by michalvasko** [comment]
I have tried setting a value with `\n\t\r` and it was correctly returned to *netopeer2-cli*. But in the console print only the `\n` could be seen but all the characters were actually printed so it is just a "visual" bug, it should work fine in the code.

**Comment by lmartanovic** [comment]
Sorry to come back to you after such a long time. I've been since able to verify that the values are indeed returned correctly and the "incorrect" values were just a consequence of the way the XML parsers in the clients I use had been handling these characters (due to [end of line handling rules](https://www.w3.org/TR/REC-xml/#sec-line-ends)).

This issue should therefore be closed.

**Comment by lmartanovic** [comment]
Closing the issue - not a bug.
