### ISSUE TITLE
Memory leak in nc_sock_connect

### ISSUE THREAD

**Issue by yangtian127** [CESNET/libnetconf2#292]
In function nc_sock_connect:
...
        for (res = res_list; res != NULL; res = res->ai_next) {
            sock = _non_blocking_connect(timeout, sock_pending, res, ka);
            if (sock == -1) {
                if (!sock_pending || *sock_pending == -1) {
                    /* try the next resource */
                    continue;
                } else {
                    /* timeout, keep pending socket */
                    return -1; **//freeaddrinfo should be called to free memory before returning, the following error branches should do the same.**
                }
            }
,,,

**Comment by michalvasko** [comment]
Right, should be fixed.

**Comment by yangtian127** [comment]
OK, thanks.
