### ISSUE TITLE
Deadlock in nc_server_ch_client_thread_session_cond_wait if the sysrepo session fails to start

### ISSUE THREAD

**Issue by yangtian127** [CESNET/libnetconf2#293]
In function nc_server_ch_client_thread_session_cond_wait()
```C
    /* CH LOCK */
    pthread_mutex_lock(&session->opts.server.ch_lock);

    /* give the session to the user */
    data->session_clb(data->client_name, session);
```

In data->session_clb, if the sysrepo session fails to start, nc_session_free() will be called, as a call-home session, the call-home semaphore(session->opts.server.ch_lock) will be acquired again, causing a deadlock.

**Comment by michalvasko** [comment]
You are right and a return value should be added for the callback. However, since that is a NBC change and the situation should never really occur, I will wait with the bugfix. I hope you do not mind.

**Comment by yangtian127** [comment]
Due to performance problems, this happened in the old version of netopeer2. When sysrepo was processing a large amount of data, the session would fail to start.because of timeout. 
This problem is less likely to occur in the new version of netopeer2-server.

**Comment by michalvasko** [comment]
Fair enough, like I said, it will be fixed eventually, I have noted it down.

**Comment by yangtian127** [comment]
OK, thanks.
