### ISSUE TITLE
libyang2 branch compilation issue

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libnetconf2#296]
Hi!

When compiling the latest libnetconf2 on the libyang2 branch, I've ran into the following
issue:

session_server_tls.c:878:9: error: too few arguments to function 'lydict_insert'

It seems like the code relevant to the older (1.1.0>) OpenSSL versions doesn't compile yet.

Can we expect support for the older OpenSSL versions in the near future?
I'm currently using version 1.0.2u.

Thanks!

**Comment by michalvasko** [comment]
The error has nothing to do with OpenSSL, it is a *libyang* function. If you want to use any project from the `libyang2` branch, it must have all its dependencies installed also from the `libyang2` branch, in this case *libyang*.

**Comment by awesomenode** [comment]
I know that. But if you look at session_server_tls.c:878
`lydict_insert(server_opts.ctx, username, 0);`

lydict_insert() is called with 3 parameters, whereas in libyang2 the function takes 4 parameters. The reason this compile on newer machines, because this code is part of the else branch of
`#if OPENSSL_VERSION_NUMBER >= 0x10100000L // >= 1.1.0`
(line 478)

**Comment by michalvasko** [comment]
Right, missed that part, should be fixed now.

**Comment by awesomenode** [comment]
Works fine now, thanks!
