### ISSUE TITLE
Libnetconf2 skip other module capability exchange

### ISSUE THREAD

**Issue by namphuonghoanges** [CESNET/libnetconf2#298]
In session.c, there is a condition to skip YANG 1.0 schemas and skip YANG 1.1 schemas to show in capability exchange, this makes the cli after exchange cannot get all info of sysrepo. Can you delete this in next release?
line 1100
` } else if (version == LYS_VERSION_1 && mod->version > version) {
      /* skip YANG 1.1 schemas */
      continue;
  } else if (version == LYS_VERSION_1_1 && mod->version != version) {
      /* skip YANG 1.0 schemas */
      continue;
  }`

**Comment by michalvasko** [comment]
No, I cannot delete it because it is intentional and [required](https://tools.ietf.org/html/rfc7950#page-12).

**Comment by namphuonghoanges** [comment]
But as i see this code make the capability discovery only send existed module of netopeer2, If I add other modules like o-ran's modules or self-define module, the capability discovery step not showing the information of those modules. I think it is somehow an omission compared to RFC

**Comment by michalvasko** [comment]
> If I add other modules like o-ran's modules or self-define module

How exactly are you adding those modules?

**Comment by namphuonghoanges** [comment]
Using the sysrepoctl to import those modules? Did i miss any step to add those module to the capabilities discovery?

**Comment by michalvasko** [comment]
Okay, so I do not understand the problem. You are saying that you have installed some YANG 1.0 modules and they were not shown in the capabilities? Like I said, YANG 1.1 modules should not show up in the capabilities. And please ignore the code, it is correct.

**Comment by namphuonghoanges** [comment]
As I understand, if I add a  ietf-hardware module into sysrepo: 
`module ietf-hardware {
yang-version 1.1;
namespace "urn:ietf:params:xml:ns:yang:ietf-hardware";
prefix hw;`
When i using the netopeer2-server and cli to make a connection between them, the capability discovery should sending the package with info: "urn:ietf:params:xml:ns:yang:ietf-hardware?module=ietf-hardware&revision=2018-03-13&features=hardware-sensor" to netopeer-cli in the capabilities discovery step. But the code that I mention before skip these capabilities to sending to the cli. If i want to have those capabilities can exchange between

**Comment by namphuonghoanges** [comment]
Can you show me any RFC said that Yang 1.1 and 1.0 modules should not show up in the capabilities?

**Comment by michalvasko** [comment]
For the last time, the YANG 1.1 RFC says:
```
A server advertises support for YANG 1.1 modules by using
ietf-yang-library [RFC7895] instead of listing them as
capabilities in the <hello> message.
```

Meaning no YANG 1.1 modules will be shown in the capabilities (even no internal modules, actually). I have nothing more to say, they should not be there, so they are not.

**Comment by namphuonghoanges** [comment]
Thank you.
