### ISSUE TITLE
Query : Adding an attribute at the <rpc> tag-level

### ISSUE THREAD

**Issue by azeem0396** [CESNET/libnetconf2#299]
Hi,
I have a requirement to add a custom attribute in \<rpc \> tag. So i am looking at something like:
\<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="14"  CUSTOM_ATTR = "VALUE"\>

So i see that `nc_write_msg_io(struct nc_session *session, int io_timeout, int type, ...) `takes variable number of arguments and has the following code:
  ```
  case NC_MSG_RPC:
        content = va_arg(ap, struct lyd_node *);
        attrs = va_arg(ap, const char *);
```
and
```
    count = asprintf(&buf, "<rpc xmlns=\"%s\" message-id=\"%"PRIu64"\"%s>",
                         NC_NS_BASE, session->opts.client.msgid + 1, attrs ? attrs : "");
```

Looking at it , i am assuming that we can add the required attribute by simply passing a const char* with value as "CUSTOM_ATTR = \"VALUE\" " to the function call. 

However i would like this to happen in the regular nc_send_rpc flow and do not want to modify these function headers. I dont see any options to pass custom data within these functions so i was wondering if there was an existing method to do this ?

Thank you.
Azeem.

**Comment by michalvasko** [comment]
It seems it was only planned as a feature and did not get implemented by any functions calling `nc_write_msg_io()`. You are free to provide a pull request with some reasonable mechanism of adding these attributes because I am not able to implement it, way too much other work.

**Comment by azeem0396** [comment]
Thanks for the reply. I will try to add something for my particular project. If time permits, will try to raise a pull request with a more acceptable mechanism as the method I intent will most likely not be very acceptable ( I am thinking of appending this string as part of user data of nc_session and having the caller of nc_write_msg_io() check and pass this string along ).
