### ISSUE TITLE
The end of the message received in the callback set by nc_set_print_clb() is cut

### ISSUE THREAD

**Issue by catalinvlad192** [CESNET/libnetconf2#300]
Hi!

I am using libnetconf2, version 1.1.36, and I am setting a callback (by nc_set_print_clb()) where I save every message in a file.
Usually, everything works as expected, but when there are extremely long messages (around 10000 bytes or more), the end of the message is stripped, and only the first 4000 bytes (approximately) are received.
I want to mention that this does not affect the functionality, as the RPC is correctly received, parsed and used.
The issue is strictly related to the message received in the callback set by nc_set_print_clb().
Can you please help me with this issue?

Thank you!

**Comment by michalvasko** [comment]
Fixed in fe5e8c9bb6ecf5c15c535d2c163ef402309f38b5 (1.1.45, latest `devel`).

**Comment by catalinvlad192** [comment]
Great!
Thank you very much for your help!
