### ISSUE TITLE
iter->schema value null

### ISSUE THREAD

**Issue by rohitkathuria102** [CESNET/libnetconf2#308]
while connecting to the callhome,the controller is failing(segmentation fault)--core dumped,
running in gdb i'm getting this trace back::

0x00007ffff532faa8 in build_schema_info_yl (session=0x7fffc801c890, result=0x7ffff33da6f0)
    at /root/rohit3/libnetconf2/src/session_client.c:740
740                 **if (iter->schema->module != mod) {**
Missing separate debuginfos, use: debuginfo-install glibc-2.17-323.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libselinux-2.5-15.el7.x86_64 lksctp-tools-1.0.17-2.el7.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb) bt
#0  0x00007ffff532faa8 in build_schema_info_yl (session=0x7fffc801c890, result=0x7ffff33da6f0)
    at /root/rohit3/libnetconf2/src/session_client.c:740
#1  0x00007ffff5330e4b in nc_ctx_check_and_fill (session=0x7fffc801c890)
    at /root/rohit3/libnetconf2/src/session_client.c:1058

please respond as soon as possible.

**Comment by michalvasko** [comment]
Okay, so the crash should be fixed but I am still not sure there is not another underlying problem. Please update all the projects on the latest `devel` and continue using it, let me know if you encounter some other problems.
