### ISSUE TITLE
Possible dereference of a freed pointer when having a notif thread in client

### ISSUE THREAD

**Issue by azeem0396** [CESNET/libnetconf2#310]
Hi,

I am using libnetconf2 to implement a netconf client. I have created a notification thread using nc_recv_notif_dispatch() with the following call back passed to it
```C
void notif_clb(struct nc_session* session, const struct nc_notif* notif)  
{
        //do some stuff  -- A  
        void* userData = nc_session_get_data(session);  
        //do some stuff -- B  
        CallNotificationHandlingFunction(notif, userData);  
}  
```
The issue i am worried about is that it is possible for my client to initiate a disconnect (which will call the nc_session_free() function) while i am parsing a notification for the same session. This will clean up the session pointer.

Looking at the code for nc_session_free() , I dont see any locking mechanism in the nc_session_free code to ensure that any notification that are being handled will complete before clean up happens. If a context switch happens at A (in the above code) , and then the nc_session_free is executed, then calling nc_session_get_data would try to access a freed pointer.

Is there any thing i am missing that would prevent this sort of situation from arising ?. Or  in general is it safe to access the nc_session pointer from within the call back ?

**Comment by michalvasko** [comment]
Yeah, it was not exactly safe and overly complex anyway. Should now be fixed.
