### ISSUE TITLE
Feature - add the requestor's IP address to verbose logs?

### ISSUE THREAD

**Issue by esend7881** [CESNET/libnetconf2#312]
Would it be possible to also display the requestor's IP address?

The following code shows `Accepted a connection on 0.0.0.0:830.` in the logs:
https://github.com/CESNET/libnetconf2/blob/697729e41ef4463d59eea98517b48f79d693c847/src/session_server.c#L515

I think it would be useful to show more, such as `Accepted a connection on 0.0.0.0:830 from 123.456.789.1` or something like that.

**Comment by michalvasko** [comment]
Okay, why not, added.
