### ISSUE TITLE
FD leak if netconf session establishment failed over TLS

### ISSUE THREAD

**Issue by rakichinni** [CESNET/libnetconf2#313]
Hi,

libnetconf2 version used: Latest 1.0

Issue: FD leak if netconf session establishment fail over TLS.

Steps to reproduce:
1. Configure and start netopeer2-server with callhome over TLS.
netopeer2-server
2. Use different CA certs at netopeer2-cli for listen.
netopeer2-cli
3. Get pid of netopeer2-cli and /proc/<pid>/fd
ls -l
4. Try establish with different ca certifcate so that, nc fails.
5. listen --tls --host <ip> --port 4335 --cert <client.pem> --key <client.key> --trusted <ca.pem>
6. Check ls -l /proc/<pid>/fd

Repeat 4+ steps and observe an increase in open fd count.

We observed a steady increase in open fds (/proc/<pid>/fd/) in every failure scenario where certificate verification failed.
> [ERR]: SSL_connect failed (certificate verify failed).

Please let me know if anyone observed FD leak issue and any resolution for it.

Thanks,
Chinni

**Comment by michalvasko** [comment]
Please check the state of the sockets using `netstat` or `ss`.

**Comment by masif-cs** [comment]
With "ss -s", I am getting below summary:
Total: 3755 (kernel 3986)
TCP:   602 (estab 20, **closed 567**, orphaned 0, synrecv 0, timewait 34/0), ports 0

Transport Total     IP        IPv6
*	  3986      -         -        
RAW	  1         0         1        
UDP	  78        78        0        
TCP	  35        8         27       
INET	  114       86        28       
FRAG	  0         0         0

"ss -a" shows many in UNCONN state

**Comment by michalvasko** [comment]
Right, sockets should now be properly closed.
