### ISSUE TITLE
How do convert 'struct nc_reply_data' to 'struct nc_notif'?

### ISSUE THREAD

**Issue by rydy** [CESNET/libnetconf2#315]
Hi,
     If  'nc_recv_reply' returns 'NC_MSG_NOTIF', how do I get this notification?How do convert 'struct nc_reply_data' to 'struct nc_notif'?
Best regards,
Thanks.

**Comment by michalvasko** [comment]
The notification is stored in a buffer in this case, you need to call `nc_recv_notif()` to get it.

**Comment by rydy** [comment]
> The notification is stored in a buffer in this case, you need to call `nc_recv_notif()` to get it.

Can I still get this notification when I return to 'NC_MSG_NOTIF' using 'nc_recv_reply'?

**Comment by michalvasko** [comment]
Yes, that is what I meant but I was probably too brief so let me elaborate. When `nc_recv_reply()` returns `NC_MSG_NOTIF`, it means a notification was read, stored in a buffer, and the function returned. You can now do several things. For example, call `nc_recv_notif()` right away to get the received notification. Or you can ignore it (leave it up to some other thread, for example) and simply call `nc_recv_reply()` again to try to get the reply this time, it will not affect the stored buffered notification, it can be retrieved at any time in future (only) by calling `nc_recv_notif()`.

**Comment by rydy** [comment]
i got it, thanks.
