### ISSUE TITLE
Unexpected child element "status" in reply

### ISSUE THREAD

**Issue by BogdanF01** [CESNET/libnetconf2#317]
Hi,

I am using devel branch 
  "81916c6 (HEAD -> devel, origin/devel) VERSION bump to version 2.0.8" for libnetconf2
  "fd7603e4 (HEAD -> devel, origin/devel) VERSION bump to version 2.0.30" for libyang
and encountered an error with message: "Unexpected child element "status"

The rpc and corresponding reply are :
[rpc.txt](https://github.com/CESNET/libnetconf2/files/6782862/rpc.txt)

According to the attached yang modules element 'status' should be fine.
Had to change extension from .yang to .txt to be able to attach them here.
[o-ran-ald.txt](https://github.com/CESNET/libnetconf2/files/6782808/o-ran-ald.txt)
[o-ran-ald-port.txt](https://github.com/CESNET/libnetconf2/files/6782810/o-ran-ald-port.txt)

Could you please help figuring out if I am doing something wrong ?
It works on v1.

Thank you.

**Comment by michalvasko** [comment]
There were several things wrong before your use-case succeeded so please update *libyang* and *libnetconf2*, then it should work.
