### ISSUE TITLE
transition to v2 issues

### ISSUE THREAD

**Issue by BogdanF01** [CESNET/libnetconf2#318]
Hi

I am using devel branch
"81916c6 (HEAD -> devel, origin/devel) VERSION bump to version 2.0.8" for libnetconf2
"fd7603e4 (HEAD -> devel, origin/devel) VERSION bump to version 2.0.30" for libyang

I encountered following issues which were not present in v1:

1. Unexpected child elements in reply
   Description in the attached files below with the yang models that were used
[rpc_failure-reply.txt](https://github.com/CESNET/libnetconf2/files/6784412/rpc_failure-reply.txt)
[o-ran-troubleshooting.txt](https://github.com/CESNET/libnetconf2/files/6784416/o-ran-troubleshooting.txt)
[rpc_reject-reason.txt](https://github.com/CESNET/libnetconf2/files/6784418/rpc_reject-reason.txt)
[o-ran-file-management.txt](https://github.com/CESNET/libnetconf2/files/6784419/o-ran-file-management.txt)

2. Can not read time stamps received in notification body
   Description in the attached files below with the yang models that were used
[description.txt](https://github.com/CESNET/libnetconf2/files/6784446/description.txt)
[o-ran-performance-management.txt](https://github.com/CESNET/libnetconf2/files/6784448/o-ran-performance-management.txt)

3. Issue parsing some notifications body
   Description in the attached files below with the yang models that were used
[description.txt](https://github.com/CESNET/libnetconf2/files/6784531/description.txt)
[o-ran-software-management.txt](https://github.com/CESNET/libnetconf2/files/6784532/o-ran-software-management.txt)

Could you please help figuring out if I am doing something wrong  or something is missing.

Thank you

**Comment by michalvasko** [comment]
1. Should be fixed by https://github.com/CESNET/libnetconf2/issues/317.
2. That seems correct, the parameter [description](https://github.com/CESNET/libyang/blob/devel/src/tree_data.h#L535) explains why.
3. Not exactly sure what the problem may be but if you print `op` (and also `envp`) before calling `lyd_find_xpath()`, it should be obvious what is happening.

**Comment by BogdanF01** [comment]
Hi,

with update of devel branch to:
5a5d96a2 (HEAD -> devel, origin/devel) VERSION bump to version 2.0.35  for libyang 
a18739e   (HEAD -> devel, origin/devel) VERSION bump to version 2.0.9    for libnetconf2

all my initial problems are solved, now I ran into new ones:

1. Received an invalid message (Node "next-update-at" not found as a child of "reset" node.).
Please see attached file with description.
[description.txt](https://github.com/CESNET/libnetconf2/files/6848147/description.txt)

Please correct me if im wrong, I was looking in session_client.c , function 'recv_reply()' and I noticed that in v1 NC_MSG_REPLY_ERR_MSGID was returned immediately if expected msg id did not match the one in the queue or the incoming,
and now in v2 libyang parsing happens first with call to 'lyd_parse_op()' and this way NC_MSG_REPLY_ERR_MSGID will only be returned  if  the incoming message is same type as expected one (example:  rpc get with id:10 - rpc-reply data for id:9).

2. Received an invalid message (Unknown XML prefix "xml".).
Please see attached file with description.
[description.txt](https://github.com/CESNET/libnetconf2/files/6848413/description.txt)


Thank you.

**Comment by michalvasko** [comment]
You are right, this worked differently or rather did not work in v2. But it seems only a minor change in *libyang* was needed and it seems to behave the same way now that it did in v1.

**Comment by BogdanF01** [comment]
Thanks , NC_MSG_REPLY_ERR_MSGID  works for me now.

What about  2. Unknown XML prefix "xml".  , do you have any feedback on that ?

**Comment by michalvasko** [comment]
Sorry, thought it was connected to the first issue. Should work now (with latest *libyang* `devel`).

**Comment by BogdanF01** [comment]
Hi,
when is a new release for v2 expected ?
thanks.

**Comment by michalvasko** [comment]
Should be a few weeks.
