### ISSUE TITLE
Potential error(e.g., deadlock, ill peformance) due to the server_opts.authkey_lock

### ISSUE THREAD

**Issue by jenny-cheung** [CESNET/libnetconf2#320]
Hi, developers, thank you for your checking. The `lockserver_opts.authkey_lock` may not be correctly released if the `!server_opts.authkeys` satifies. Finally, the method returns with the unreleased lock `server_opts.authkey_lock`. The fix is to insert `pthread_mutex_unlock(&server_opts.authkey_lock);`  before returning.

https://github.com/CESNET/libnetconf2/blob/697729e41ef4463d59eea98517b48f79d693c847/src/session_server_ssh.c#L573
https://github.com/CESNET/libnetconf2/blob/697729e41ef4463d59eea98517b48f79d693c847/src/session_server_ssh.c#L577
https://github.com/CESNET/libnetconf2/blob/697729e41ef4463d59eea98517b48f79d693c847/src/session_server_ssh.c#L579

```
static int
_nc_server_ssh_add_authkey(const char *pubkey_path, const char *pubkey_base64, NC_SSH_KEY_TYPE type, const char *username)
{
    /* LOCK */
    pthread_mutex_lock(&server_opts.authkey_lock); the lock

    ++server_opts.authkey_count;
    server_opts.authkeys = nc_realloc(server_opts.authkeys, server_opts.authkey_count * sizeof *server_opts.authkeys);
    if (!server_opts.authkeys) {
        ERRMEM;
        return -1; //return without releasing lock
    }
    ...;

    /* UNLOCK */
    pthread_mutex_unlock(&server_opts.authkey_lock);

    return 0;
}
```

Best,

**Comment by michalvasko** [comment]
Fine, fixed.

**Comment by jenny-cheung** [comment]
Thanks!
