### ISSUE TITLE
[TLS] server identity check is missing 

### ISSUE THREAD

**Issue by j1y3p4rk** [CESNET/libnetconf2#322]
Hi Michal, 

For the TLS secure communication, NETCONF client MUST check the identity of server according to [RFC 7589](https://datatracker.ietf.org/doc/html/rfc7589#section-6). 

I found that libnetconf2 (Netopeer2-CLI) client is not behaving as it's supposed to be. It does not check the validation of hostname in server certificate.

As far as I know, with [this line](https://github.com/CESNET/libnetconf2/blob/891b73a376cf2141c6e765f89e106c94d28435db/src/session_client_tls.c#L639), OpenSSL wouldn't perform 'hostname validation' check. 

Could you consider or do you have any plan to update the code so it can comply with NETCONF over TLS specification?

**Comment by michalvasko** [comment]
Fine, the check was added but there are little options in *libssl* to customize it (make it less strict) and the error message is really brief so I expect users using this feature will no longer be able to connect and will not know why.
