### ISSUE TITLE
Converting an XML string to lyd_node in order to populate the response via nc_server_reply_data().

### ISSUE THREAD

**Issue by sterlite-del** [CESNET/libnetconf2#325]
Hi,

I am writing a small netconf server. Whenever I get a "GET" RPC I need to populate a response to it.

But, I am getting a response for the "GET" RPC as an XML string.

How do I convert this XML string to a lyd_node (which I can then use to make a response via the nc_server_reply_data API) ?

I would appreciate it if anyone could guide me in this regard.

Thanks!

**Comment by michalvasko** [comment]
You need to use *libyang* API. `lyd_parse_op()`, to parse an RPC/rpc-reply.

**Comment by sterlite-del** [comment]
Ok thank you. Closing this issue.
