### ISSUE TITLE
undefined reference to nc_new_session

### ISSUE THREAD

**Issue by sangamesh82** [CESNET/libnetconf2#330]
Hello,

I have started using this tool recently and have went through the tests folder and the examples in it. Started with a sample call home test. I have added the necessary C_INCLUDE_PATH and LD_LIBRARY_PATH, but I get error at linking time for 'nc_new_session' as undefined reference. The header file session_p.h from the src folder has been added and .I option is used as part of GCC.

Please let me know how to solve this and if I need to provide more information, please let me know.

wwr,
Sangamesh

**Comment by michalvasko** [comment]
`nc_new_session` is not a public function and `session_p.h` is not a public header so I am not sure what exactly you are doing but it is wrong. You are meant to include only `nc_client.h` if implementing a NETCONF client and `nc_server.h` if implementing a server.

**Comment by sangamesh82** [comment]
Hello Michal,

Got it, thanks.

I am implementing the NETCONF client with call home and other NETCONF features, and was referring the code examples from the tests folder, so I used the nc_new_session and session_p.h files.

wwr,
Sangamesh

**Comment by michalvasko** [comment]
The best example of a *libnetconf2* NETCONF client there is is *netopeer2-cli*. But it is quite simple so you will have to look at all the public functions and the general documentation.

**Comment by sangamesh82** [comment]
Oh ok, I have not looked at this, I will use it as a reference. It is cli based, and I want to build NETCONF client as a C API based. 

I am looking at https://netopeer.liberouter.org/doc/libnetconf2/devel/html/howto.html documentation.

**Comment by sangamesh82** [comment]
Is there any other documentation that I need to look at ?

**Comment by michalvasko** [comment]
No, there is no other.

**Comment by sangamesh82** [comment]
Thanks for the information Michal, will get started with my activities and will get back to you accordingly.
