### ISSUE TITLE
server SSH hangs

### ISSUE THREAD

**Issue by zhoulinghua** [CESNET/libnetconf2#34]
I tried to write the main function
```C
ly_ctx = ly_ctx_new(TESTS_DIR"/../schemas");
nc_server_init(ly_ctx);
snode = ly_ctx_get_node(ly_ctx, NULL, "/ietf-netconf:get");
nc_set_rpc_callback(snode, op_get);
ly_ctx_get_module(....) and start ssh server.
```
I use the MG-SOFT client to connect ssh server.
client send rpc package:

```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" essage-id="2">
  <get>
    <filter>
      <yanglib:modules-state xmlns:yanglib="urn:ietf:params:xml:ns:yang:ietf-yang-library"/>
    </filter>
  </get>
</rpc>
```

in op_get function:
```
lyd_print_file(stdout, root, LYD_XML, LYP_WITHSIBLINGS);
```
print:
```xml
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<data>
<modules-state xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-library">
<module>
<name>ietf-yang-metadata</name>
<revision>2016-08-05</revision>
<namespace>urn:ietf:params:xml:ns:yang:ietf-yang-metadata</namespace>
<conformance-type>import</conformance-type>
</module>

<module>
<name>yang</name>
<revision>2017-02-20</revision>
<namespace>urn:ietf:params:xml:ns:yang:1</namespace>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>ietf-inet-types</name>
<revision>2013-07-15</revision>
<namespace>urn:ietf:params:xml:ns:yang:ietf-inet-types</namespace>
<conformance-type>import</conformance-type>
</module>

<module>
<name>ietf-yang-types</name>
<revision>2013-07-15</revision>
<namespace>urn:ietf:params:xml:ns:yang:ietf-yang-types</namespace>
<conformance-type>import</conformance-type>
</module>

<module>
<name>ietf-yang-library</name>
<revision>2016-06-21</revision>
<namespace>urn:ietf:params:xml:ns:yang:ietf-yang-library</namespace>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>ietf-netconf</name>
<revision>2011-06-01</revision>
<namespace>urn:ietf:params:xml:ns:netconf:base:1.0</namespace>
<feature>writable-running</feature>
<feature>candidate</feature>
<feature>rollback-on-error</feature>
<feature>validate</feature>
<feature>startup</feature>
<feature>xpath</feature>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>ietf-netconf-monitoring</name>
<revision>2010-10-04</revision>
<namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</namespace>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>ietf-netconf-with-defaults</name>
<revision>2011-06-01</revision>
<namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults</namespace>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>notifications</name>
<revision>2008-07-14</revision>
<namespace>urn:ietf:params:xml:ns:netconf:notification:1.0</namespace>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>nc-notifications</name>
<revision>2008-07-14</revision>
<namespace>urn:ietf:params:xml:ns:netmod:notification</namespace>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>ietf-netconf-notifications</name>
<revision>2012-02-06</revision>
<namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications</namespace>
<conformance-type>implement</conformance-type>
</module>

<module>
<name>if</name>
<revision>2017-06-21</revision>
<schema>file:///opt/libnetconf2/schemas/if.yang</schema>
<namespace>utstar:tn705e:if</namespace>
<conformance-type>implement</conformance-type>
</module>

<module-set-id>13</module-set-id>
</modules-state>
</data>
</get>
```
after I call  `nc_server_reply_data(root, nc_wd, NC_PARAMTYPE_FREE)` server SSH hangs.

I do not know what's wrong. can you help me? thank you!

**Comment by michalvasko** [comment]
Hi,
unfortunately, *libnetconf2* does not have much documentation at the moment so I understand you have problems implementing your own server. Nevertheless, I think the interface is neat so you should be able to implement a simple one with a bit of my help :)

Just to answer shortly what is wrong, you are not using server poll API, without which no RPC replies will ever be sent. Your `op_get` seems fine, so you can keep that part, but after setting up the server (your first code snippet) you need to start the polling mechanism. For inspiration you can look at our NETCONF server implementation, specifically the [polling loop](https://github.com/CESNET/Netopeer2/blob/master/server/main.c#L983). The interesting core functions are `nc_accept`, `nc_ps_add_session` (called in `np2srv_new_session_clb`), and `nc_ps_poll`. The documentation for all of those should tell you how to use them.

Regards,
Michal

**Comment by zhoulinghua** [comment]
yes,I create thread ,the polling loop.

restart:
	/* initiate NETCONF server */
	if (server_init()) {
		ret = EXIT_FAILURE;
		goto cleanup;
	}

	printf("server init success!!!");
	

	pthread_attr_init(&thread_attr);
	pthread_attr_setdetachstate(&thread_attr, PTHREAD_CREATE_DETACHED);
	/* start additional worker threads */
	for (i = 1; i < thread_count; ++i) {
		idx = malloc(sizeof *idx);
		*idx = i;
		pthread_create(&np2srv.tids[*idx], &thread_attr, worker_thread, idx);
	}
	pthread_attr_destroy(&thread_attr);

	/* one worker will use this thread */
	np2srv.tids[0] = pthread_self();
	idx = malloc(sizeof *idx);
	*idx = 0;
	worker_thread(idx);

	/* wait for finishing processing thread */
	do {
		for (i = 0; i < thread_count; ++i) {
			if (np2srv.tids[i]) {
				break;
			}
		}
	} while (i < thread_count);

in worker_thread function:
while nc_ps_poll ,receive Hello package from  client.

I does not call nc_server_reply_data(root, nc_wd, NC_PARAMTYPE_FREE) ,The server is good.

**Comment by michalvasko** [comment]
This is the code from *netopeer2*, did you copy it? Why do not use it directly then, no need to write your own NETCONF server.

Regards,
Michal

**Comment by zhoulinghua** [comment]
I need add myslef database.so I refer to his realization

**Comment by michalvasko** [comment]
Not sure what your shared library does, but it may still be easiest to modify our `netopeer2-server` to suit your needs. Otherwise it is best to debug this yourself, you have our implementation that works and yours that does not, so just try to compare them.

Regards,
Michal

**Comment by zhoulinghua** [comment]
ok,I try modify netopeer2-server .thank you！！！
