### ISSUE TITLE
nc_accept_callhome return value

### ISSUE THREAD

**Issue by rohitkathuria102** [CESNET/libnetconf2#346]
Hi @michalvasko,
as we have currently :::

**nt nc_accept_callhome	(int 	timeout, struct ly_ctx * ctx, struct nc_session ** session )**		

returns  1 on success, 0 on timeout, -1 on error.

is there a way that if callhome fails we can know the reason for it failing (for example; incorrect password,or incorrect ssh public key etc. ) ?

**Comment by michalvasko** [comment]
There are lots of reasons why it may fail and the reason is always printed. You can set a logging callback to get the exact message.
