### ISSUE TITLE
Client authentication based on SSH using X.509 certificates

### ISSUE THREAD

**Issue by Ritesh545** [CESNET/libnetconf2#349]
Hi, 
In the libnetconf2 document, we can see that the client support three types of  authentications: 
  1. public-key,
  2. password, 
  3. interactive.
 
Does libnetconf2 support client authentication based on ssh using X.509 certificates or is there any plan to support this in the near future?

**Comment by michalvasko** [comment]
It is not supported and there is no plan to, currently.
