### ISSUE TITLE
Backporting message data race fix to v1.1.26

### ISSUE THREAD

**Issue by harishbsam** [CESNET/libnetconf2#353]
Hello,

Is it possible to backport the message concurrency [data race fix](https://github.com/CESNET/libnetconf2/commit/54f142a494cb896a925fa8508d1ef29ad82d0486#diff-903594ebdb0bcfef6fce31cb6bab71a459111a1f1adcddb3e79fdf2cb44c0e6b) made in v2.0.17 to v1.1.26. We are using v1.1.26 version of libnetconf2 and would like get a fix for the data race problem. We are looking for a way to bring in the fix without upgrading libnetconf2. Please let me know. 

Thanks!

**Comment by michalvasko** [comment]
As you can see, the changes were quite extensive and we simply do not have spare time to keep supporting all the versions and fixing all the problems in old versions, so I am sorry, we will not implement this. But you are welcome to if you need it.
