### ISSUE TITLE
Typo in action causes segfault

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libnetconf2#354]
Hi!

I accidentally made a typo when calling an action using Netopeer2, which caused a segmentation fault.

For example, after installing the attached test schema and config, then sending the following RPC:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
     xmlns:yang-1_1="urn:ietf:params:xml:ns:yang:1"
     message-id="1">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <bsics xmlns="urn:com:test">
      <animals>
        <species>dog</species>
        <example/>
      </animals>
    </bsics>
  </action>
</rpc>
```

netopeer crashes.

libyang version: 2.0.127
sysrepo version: 2.1.8
libnetconf2 version: 2.1.2
netopeer2 version: cdc1ad2f6b841f55de27ec996ccb0a8e4085030c
[action_issue.tar.gz](https://github.com/CESNET/libnetconf2/files/7725789/action_issue.tar.gz)

**Comment by michalvasko** [comment]
Could you run *netopeer2* with `gdb` and print the stack trace for the failed assert? Will most likely be just a missing check for opaque nodes. Or, provide a way of reproducing it because `nc_send_rpc()` refuses to send these data to the server since they have no operation parsed, not sure how you managed to send them.

**Comment by awesomenode** [comment]
```
Thread 6 "netopeer2-serve" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff328a700 (LWP 28168)]
0x00007ffff799c2ef in nc_server_send_reply_io (session=0x7fffe4001280, io_timeout=10, rpc=0x7fffe8000bc0) at ~/repos/libnetconf2/src/session_server.c:1433
1433	    if (!rpc) {
(gdb) bt
#0  0x00007ffff799c2ef in nc_server_send_reply_io (session=0x7fffe4001280, io_timeout=10, rpc=0x7fffe8000bc0) at ~/repos/libnetconf2/src/session_server.c:1433
#1  0x00007ffff799d226 in nc_ps_poll (ps=0x555555886650, timeout=10, session=0x7ffff3289e90) at ~/repos/libnetconf2/src/session_server.c:1812
#2  0x000055555556010d in worker_thread (arg=0x5555558720b0) at ~/repos/netopeer2/src/main.c:1022
#3  0x00007ffff74db6db in start_thread (arg=0x7ffff328a700) at pthread_create.c:463
#4  0x00007ffff6c2d71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by michalvasko** [comment]
Should be fixed in the latest *libyang*.

**Comment by awesomenode** [comment]
No segfault anymore. Thank you!
