### ISSUE TITLE
callhome request send by netconf_server with timeout

### ISSUE THREAD

**Issue by palaniace** [CESNET/libnetconf2#365]
how can achieve and configure , so that netconf_server should send callhome request with  periodically , instead of sending continuously . need some guidance for reconnect stragey on netconf server side.

Also how can i provide the maximum attempts . server can send the callhome request ..

**Comment by michalvasko** [comment]
Just configure `ietf-netconf-server` YANG module data and you can adjust all these parameters. [This](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-server%402019-07-02.yang#L377) is the relevant subtree.
