### ISSUE TITLE
libnetconf2 v2.x: nc_notif structure

### ISSUE THREAD

**Issue by rabhat31** [CESNET/libnetconf2#372]
Hi, I have a couple of questions.

Is the nc_notif structure no longer used in libnetconf2 v2.x ?
Is there a transition manual to v2.x available, similar to what was provided for libyang?

**Comment by rabhat31** [comment]
In the same vein as the prev questions, has nc_reply been removed as well? What is a replacement structure I can use?

**Comment by michalvasko** [comment]
> Is there a transition manual to v2.x available, similar to what was provided for libyang?

Unfortunately not.

> Is the nc_notif structure no longer used in libnetconf2 v2.x ?

`nc_notif` and `nc_reply` structures were removed because *libyang* v2 defines opaque nodes that are able to store non-YANG data that were stored separately before. So now you can always simply get a data tree with all the NETCONF-specific elements.
