### ISSUE TITLE
TLS connection causes bad certificate

### ISSUE THREAD

**Issue by ewagosk** [CESNET/libnetconf2#373]
Hi everyone,

Thank you for creating and maintaining a great set of libraries!

I am trying to use libnetconf2 to set up a NETCONF session over TLS. I have a root certificate called "ca.pem" from which I have two key/certificate pairs generated (server.crt/key and client.crt/key).

```
client$ pwd && ll
/home/oskar/cert
total 28
drwxrwxr-x  2 oskar oskar 4096 May 12 09:41 ./
drwxr-xr-x 19 oskar oskar 4096 May 12 09:55 ../
-rw-r--r--  1 oskar oskar 1654 May 12 09:40 ca.pem
-rw-r--r--  1 oskar oskar 2084 May 12 09:40 client.crt
-rw-r--r--  1 oskar oskar 3292 May 12 09:40 client.key
-rw-r--r--  1 oskar oskar 2036 May 12 09:40 server.crt
-rw-r--r--  1 oskar oskar 3246 May 12 09:40 server.key
```

I have during the past few days played around with OpenSsl and am able to create a TLSv1.3 connection using the s_connect and s_client commands like so:

`server$ openssl s_server -accept 3000 -CAfile ca.pem -cert server.crt -key server.key -state -msg`
```
client$ openssl s_client -connect 10.40.241.145:3000 -key client.key -cert client.crt -CAfile ca.pem
...
---
SSL handshake has read 3460 bytes and written 363 bytes
Verification: OK
---
...
---
read R BLOCK
```

This then allows me to communicate between the client and the server over TLS. When instead writing a small C application on the client side using the libnetconf2 library, the server rejects the very same(?) certificate. I have tried to boil it down to a minimum example:

```
#include <nc_client.h>

#define HOST "10.40.241.145"
#define TLS_PORT 3000
#define CERT_PATH "/home/oskar/cert"

int main(){
    nc_client_init();
    nc_verbosity(4);
    if(nc_client_tls_set_trusted_ca_paths(CERT_PATH "/ca.pem", NULL)){
        printf("nc_client_tls_set_trusted_ca_paths failed\n");
        return 1;
    }
    if(nc_client_tls_set_cert_key_paths(CERT_PATH "/client.crt", CERT_PATH "/client.key")){
        printf("nc_client_tls_set_cert_key_paths failed\n");
        return 1;
    }
    if(NULL == nc_connect_tls(HOST, TLS_PORT, NULL)){
        printf("nc_connect_tls failed\n");
        return 1;
    }
    return 0;
}
```

On the client side, running the code:
```
client$ ./demo 
[DBG]: nc_sock_connect(10.40.241.145, 3000, -1, -1)
[INF]: Trying to connect via IPv4 to 10.40.241.145:3000.
[INF]: Successfully connected to 10.40.241.145:3000 over IPv4.
[ERR]: SSL_connect failed (certificate verify failed).
nc_connect_tls failed
```

On the server side, still using the same openssl s_server command as above:
```
...
<<< ??? [length 0005]
    15 03 03 00 02
<<< TLS 1.3, Alert [length 0002], fatal bad_certificate
    02 2a
ERROR
140422655558080:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1528:SSL alert number 42
shutting down SSL
CONNECTION CLOSED
```

What I am wondering is if I have completely misunderstood what the nc_client_tls* commands do. Of course I won't be able to initiate a NETCONF session on the server side with just `openssl s_server`, but I am still surprised that the TLS connection is rejected by the server. If you have any insight in why this does not work, then I would be very grateful for the help! Thank you.

**Comment by michalvasko** [comment]
It all seems fine but there could be one problem preventing the connection. Fairly recently I have added a mandatory Common Name check of the server certificate to match the host you are connecting to as the client because it was required by some RFC. So, unless the CN of the server is `10.40.241.145`, the connection will be refused by OpenSSL. I did what I could to force the library to print some meaningful error but to no avail and I think it is just this generic one.

**Comment by ewagosk** [comment]
Hi Michal,

Thank you very much for the extremely quick reply. You managed to identify the exact issue. Generating a new certificate with the common name 10.40.241.145 got me past the issue. I have now also managed to perform a connection from a libnetconf2 client to the netopeer2 server implementation via TLS after understanding how the ietf-netconf-server configuration worked.

The issue can be closed, hope it helps someone else in the future!
Have a nice weekend!
/Oskar
