### ISSUE TITLE
[v2.1.11] nc_sock_listen_inet: Could not bind "X.X.X.X" port 830 (Permission denied).

### ISSUE THREAD

**Issue by Wexiwa** [CESNET/libnetconf2#375]
Hello,

It seems I have an issue with `libnetconf2` (v2.1.11) TCP socket binding to the default Netconf SSH port (`830`), as well as any other port below `1024`.

I am aware that those ports are restricted to privileged processes, so the process run as root (`UID 0`) and I even tried to set the executable file capabilities [CAP_NET_BIND_SERVICE](https://man7.org/linux/man-pages/man7/capabilities.7.html), but the error remains.

Here is how I tested and reproduced the issue:

I wrote of a small independent program that uses the same code as [nc_sock_listen_inet](https://github.com/CESNET/libnetconf2/blob/v2.1.11/src/session_server.c#L198) to open a socket, everything seems to work fine. Here is the output:

```text
UID: 0 (0)
Socket 3 created for 127.0.0.1:22
[ERR]: Could not bind "127.0.0.1" port 22 (Address already in use).
UID: 0 (0)
Socket 3 created for 127.0.0.1:830
Listening on 127.0.0.1:830...
Closing socket 127.0.0.1:830
UID: 0 (0)
Socket 3 created for 10.0.2.15:830
Listening on 10.0.2.15:830...
Closing socket 10.0.2.15:830
UID: 0 (0)
Socket 3 created for 0.0.0.0:830
Listening on 0.0.0.0:830...
Closing socket 0.0.0.0:830
UID: 0 (0)
Socket 3 created for 127.0.0.1:834
Listening on 127.0.0.1:834...
Closing socket 127.0.0.1:834
UID: 0 (0)
Socket 3 created for 127.0.0.1:4334
Listening on 127.0.0.1:4334...
Closing socket 127.0.0.1:4334
UID: 0 (0)
Socket 3 created for 127.0.0.1:8300
Listening on 127.0.0.1:8300...
Closing socket 127.0.0.1:8300
```

I tested port `22` for reference purpose, as I know it is used by the SSH server. Anyway, all other ports are free and the socket binding is done successfully.

Then using the same program while linking it against `libnetconf2` libraries, the issue I mention appears and the output becomes :

```text
UID: 0 (0)
Socket 3 created for 127.0.0.1:22
[ERR]: Could not bind "127.0.0.1" port 22 (Permission denied).
UID: 0 (0)
Socket 3 created for 127.0.0.1:830
[ERR]: Could not bind "127.0.0.1" port 830 (Permission denied).
UID: 0 (0)
Socket 3 created for 10.0.2.15:830
[ERR]: Could not bind "10.0.2.15" port 830 (Permission denied).
UID: 0 (0)
Socket 3 created for 0.0.0.0:830
[ERR]: Could not bind "0.0.0.0" port 830 (Permission denied).
UID: 0 (0)
Socket 3 created for 127.0.0.1:834
[ERR]: Could not bind "127.0.0.1" port 834 (Permission denied).
UID: 0 (0)
Socket 3 created for 127.0.0.1:4334
Listening on 127.0.0.1:4334...
Closing socket 127.0.0.1:4334
UID: 0 (0)
Socket 3 created for 127.0.0.1:8300
Listening on 127.0.0.1:8300...
Closing socket 127.0.0.1:8300
```

Notice that even the error on the port `22` have changed. Any port below `1024` does not work anymore.

My `netopeer2-server` is having the same issue so I suppose the behavior is the same for it (the same error message is logged: `daemon.err netopeer2-server[2005]: Could not bind "0.0.0.0" port 830 (Permission denied).`). Configuring a port above `1024` works fine but I really need to use `830` as it is the official one assigned by `IANA`.

Does `libnetconf2` has some kind of global initialization and/or may drop process privileges at some point ?

Do you have any knowledge of security measures that would prevent a process that links against "untrusted" user shared libraries to bind to those ports ? (it seems only binding to `libyang` and/or `sysrepo` does not produce the issue).

It should be added that I run my tests on a custom Linux (based on [PetaLinux v2020.1](https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/embedded-design-tools.html)) with [BusyBox](https://busybox.net/).

**Comment by michalvasko** [comment]
I do not think I can help you, you should get the error only if you do not have the required privileges, I have never seen it in any other case. So I would probably blame your custom Linux that may have some extra security features, no idea what else it could be.

**Comment by Wexiwa** [comment]
Hi Michal,

I am back with more info.

After investigating more, I found out that the issue also appears when linking to `libssh` (0.8.4).
Running `ldd` on it shows that it links against `libcap` through `libgcrypt` (1.8.4).
Linking against `libgcrypt` alone does not trigger the issue, howerver I had a quick look at where and why they use `libcap` only to find that for security purpose they drop all the process privileges in one of their [initialization method](https://github.com/gpg/libgcrypt/blob/libgcrypt-1.8.4/src/secmem.c#L539) (this behavior can enventually be disabled c.f. [GCRYCTL_DISABLE_PRIV_DROP](https://www.gnupg.org/documentation/manuals/gcrypt/Controlling-the-library.html)).

So my guess would be that there is some global initialization at work in `libssh` that end up dropping all privileges before my program or `libnetconf2` (and by extension `netopeer2-server`) open their sockets on restricted ports.

Do you think that something needs to be done on your side ? Additionally, for better security, should `libnetconf2` or `netopeer2-server` ensure to drop privileges after opening their sockets ?

**Comment by Wexiwa** [comment]
One workaround would be to compile `libssh` without `libgcrypt` support (`-DWITH_GCRYPT=OFF`), which would result in using `openssl` instead (c.f. their [CMakeLists.txt](https://git.libssh.org/projects/libssh.git/tree/CMakeLists.txt?h=stable-0.8#n50)), as I just tried it and `netopeer2-server` successfully binds to port `830`. 
However, I don't know what are the pros and cons between the two options.

Nevertheless, that means that `netopeer2-server` keeps all its privileges after that, which could be a security issue.

**Comment by michalvasko** [comment]
That will be the reason I have never encountered it, using `openssl` is the standard way of compiling *libssh*. Also, the server needs to be run as `root` because you can change its configuration at any time and it will then need to bind to another port, for example, if that is the change you make.

**Comment by Wexiwa** [comment]
Thanks again for your time.

I will stick with this configuration of `libssl` then.

Pardon my curiosity, but something still bugs me, does the Netconf RFC state that the server configuration (i.e. listening endpoints) can be changed at any point by authorized clients ? Or is it an "arbitrary" design choice ?
If there are no other use case where privileged capabilities are required, that would make more sense to require a server restart after editing those settings and be able to drop unwanted privileges.

Even if `CAP_NET_BIND_SERVICE` is required, it would be good to drop all the other.

**Comment by michalvasko** [comment]
NETCONF server configuration is a normal part of `running` datastore, which can be changed at any time, so yes, it is part of the specification, I suppose. But I think this is the only case where the privileges are required, by default. We have not really bothered with the capabilities and what have you, *netopeer2-server* is supposed to be a critical system daemon with its own configuration being sensitive, so it is expected it will run as `root`.

> make more sense to require a server restart after editing those settings

Maybe to you, I think this may be a major problem for some deployment use-cases.

**Comment by Wexiwa** [comment]
Noted, thanks for the highlights!
