### ISSUE TITLE
Error when send nc_rpc_estabsub ?

### ISSUE THREAD

**Issue by stoicity** [CESNET/libnetconf2#377]
When I create a rpc with nc_rpc_establishsub and then send it with nc_send_rpc to NETCONF server in CONFD suite. 
If I pass filter parameter in nc_rpc_establishsub as NULL, I could establish subscription successfully. If I specify the filter params, NETCONF server reply error.

![image](https://user-images.githubusercontent.com/29137639/172522940-b943042c-ca3d-49a4-be7b-dfbc2152e028.png)

Here is the code to create and send rpc:

![image](https://user-images.githubusercontent.com/29137639/172523157-4d6da2af-6810-43dd-bc00-449eb1b9cf31.png)

I have created a function to covert treedata to char * and follow the way nc_send_rpc create treedata for NC_RPC_ESTABLISHSUB and ly_print_mem, then print it out. Here this the result.

![image](https://user-images.githubusercontent.com/29137639/172525885-4c8b87eb-d24d-46ee-8321-c392a3ac066a.png)

If I used the above xml with 'stream-xpath-filter' tag swapping place with 'stream' tag and send with netconf-console, it was successfully. Something like this.

![image](https://user-images.githubusercontent.com/29137639/172526253-2df76c98-4805-4177-b71d-aabbdf294d77.png)

Note: I have applied the ietf-subscribed-notifications.yang to both client and server.

**Comment by michalvasko** [comment]
Try the latest *libyang* `devel`, it should work. Nevertheless, it is not specified that nodes from an `augment` must be appended as the last children of the parent, which is obviously the expectation here. But the specification is at fault, cannot really blame ConfD.

**Comment by stoicity** [comment]
I have used libyang `devel`, but segmentation fault occured. Here the gdb backtrace:

![image](https://user-images.githubusercontent.com/29137639/172983540-701e147b-891e-40a4-92b1-0a2ed1d39381.png)

**Comment by michalvasko** [comment]
Please pull the current `devel`, your lines do not match anymore. I think I have fixed this in the last change.

**Comment by stoicity** [comment]
Hi, I noticed a few console warning generated by libyang devel, should I consider using latest version of libnetconf2? Note: establish-subscription works successfully.
![image](https://user-images.githubusercontent.com/29137639/174534451-b073e3a3-7dcd-4d52-86c3-52f733c49e96.png)
