### ISSUE TITLE
Question about carrying data in an <ok> response

### ISSUE THREAD

**Issue by Makinashout** [CESNET/libnetconf2#380]
Hi,
I'm part of a research group as PhD candidate in which we use libnetconf2 as a NETCONF implementation for SDN virtual environments. We are in the early stages of the architecture design for our new research, and we find very convenient to return data inside an <ok> NETCONF RPC response. We have been researching in the RFC and we didn't found any MUST rule that avoid using the <ok> response as a carrier for data, however we wanted to be sure that this is a possibility and we are not breaking libnetconf2 by trying to embed data into an <ok/> response.
Thanks in advance.

**Comment by jktjkt** [comment]
Reading [the standard](https://datatracker.ietf.org/doc/html/rfc6241#section-4.4), its says:

> The `<ok>` element is sent in `<rpc-reply>` messages if no errors or warnings occurred during the processing of an `<rpc>` request, **and no data was returned from the operation**.

The point of standardization is interoperability. What do you hope to achieve by redefining the `<ok/>` response to encapsulate additional data? Presumably, nobody else but your SW would understand that.
