### ISSUE TITLE
PAM: memory leak in linux-pam >=1.4, <1.5

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libnetconf2#385]
As [shown here](https://github.com/CESNET/libnetconf2/runs/7370334707?check_suite_focus=true), there's a memleak in linux-pam which was [fixed back in 2020](https://github.com/linux-pam/linux-pam/pull/291), but only [released to the 1.5.x branch](https://github.com/linux-pam/linux-pam/commit/51318fd423a8ab4456a278ef0aff6ad449aab916). That version is not part of any Ubuntu release that is available on GitHub CI. So far, the CI has also been running on Ubuntu 18.04 which is too old to test PAM because the tests need the "confdir" thingy. I've tried updating the CI to use Ubuntu 22.04 (and therefore linux-pam 1.4.x), but that fails valgrind and ASAN tests due to that memleak.

@roytak, can you please either provide suppression files for valgrind and ASAN, or disable these tests on linux-pam < 1.5, or work with Ubuntu to cherry-pick that upstream patch to linux-pam?

**Comment by Roytak** [comment]
Thank you for noticing this. Suppression files have been written as that seems like the best solution.
