### ISSUE TITLE
RPC w/o message-id is not rejected

### ISSUE THREAD

**Issue by pfeige** [CESNET/libnetconf2#386]
Hi,

currently, a RPC w/o message-id is not rejected, but according to RFC 6241 this attribute is mandatory. Therfore, I guess such an RPC should be rejected with a missing-attribute error. What do you think?

BR,
Peter

**Comment by michalvasko** [comment]
You should see [this](https://github.com/CESNET/libnetconf2/blob/devel/src/session_client.c#L1822) error, what is happening instead?

**Comment by pfeige** [comment]
The sent snippet is
~~~
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <nc:lock>
      <nc:target><nc:running/></nc:target>
   </nc:lock>
</nc:rpc>
~~~
And the reply is
~~~
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><ok/></rpc-reply>
~~~

**Comment by michalvasko** [comment]
Okay, the server was not checking for it, only the client. Proper error should now be generated.

**Comment by pfeige** [comment]
It works.
Thanks!
