### ISSUE TITLE
How to disable xpath style in rpc?

### ISSUE THREAD

**Issue by DubHokku** [CESNET/libnetconf2#391]
Hi,

tried to send nc_rpc* to Cisco xrv9000 ( [this models set](https://github.com/YangModels/yang/tree/main/vendor/cisco/xr/761) is used ), but xrv9k returns `<rpc-error>`.

i  make: `nc_rpc_get( "Cisco-IOS-XR-ipv4-acl-oper:ipv4-acl-and-prefix-list", NC_WD_UNKNOWN, NC_PARAMTYPE_FREE );`
and `nc_send_rpc()` send this rpc:

```
  <get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <filter type="xpath" xmlns:ipv4-acl-oper="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-acl-oper" select="ipv4-acl-oper:ipv4-acl-and-prefix-list"/> 
  </get>
```

but if to use: `nc_rpc_act_generic_xml( "<get xmlns='urn:ietf:params:xml:ns:netconf:base:1.0'><filter><ipv4-acl-and-prefix-list xmlns='http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-acl-oper'/></filter></get>", NC_PARAMTYPE_CONST );`

`nc_send_rpc()` will send:

```
  <get xmlns='urn:ietf:params:xml:ns:netconf:base:1.0'>
    <filter>
      <ipv4-acl-and-prefix-list xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-acl-oper"/>
    </filter>
  </get>
```

then xrv9k are return `<rpc-reply>`!

how i can tell `nc_rpc_get()` not  to use `xpath` in this rpc?

---
ps:
`<capabilities>` xrv9k not is set `<capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>`.

also i'am verify netconf session context feature:

```
ietf_netconf = ly_ctx_get_module( ctx, "ietf-netconf", "2013-09-29" );
lys_feature_value( ietf_netconf, "xpath" );
```
`lys_feature_value()` return `ENOT`.

----
ps2:
i have modify libnetconf2 in `session_client_ssh.c` near:

```
if (nc_ctx_check_and_fill(session) == -1) {
    WRN(session, "/* store information for session connection */ ");
    // goto fail;
```
for resolve issue ["tailf:arg-type" not found, close-session #383](https://github.com/CESNET/libnetconf2/issues/383), 

cause else libnetconf2 are send `<close-session>` during parsing  `<hello>` capabilities.

**Comment by michalvasko** [comment]
Use
```C
nc_rpc_get("<ipv4-acl-and-prefix-list xmlns='http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-acl-oper'/>", NC_WD_UNKNOWN, NC_PARAMTYPE_CONST);
```
and it should work.

**Comment by DubHokku** [comment]
Thanks!
