### ISSUE TITLE
[Question] Chunk framing without message

### ISSUE THREAD

**Issue by catalinvlad192** [CESNET/libnetconf2#395]
Hi!
I am using version 2.0.24 and I noticed that, during client's get-schema, there is no message received in the callback set with nc_set_print_clb_session() function, but checking the logs from server side, I can see that the message is correctly received.
From logs received in the callback, the message looks like this:
Session 1: Sending message:#320
Sending message:##
Is this made on purpose?

Thank you!

**Comment by michalvasko** [comment]
It is not on purpose and the logging seems to work fine in the latest `devel` version 2.1.20, so I cannot help you.
