### ISSUE TITLE
[question] is libPAM library is mandatory

### ISSUE THREAD

**Issue by siprab** [CESNET/libnetconf2#396]
while compiling the libnetconf2 getting below error: 
CMake Error at /usr/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibPAM (missing: LIBPAM_LIBRARIES LIBPAM_INCLUDE_DIRS)

We know that the package libPAM is missing in our setup. However just wanted to ask is it compulsory or we can compile libnetconf2 bypassing this package. kindly suggest. 

Thanks

**Comment by michalvasko** [comment]
It is required currently because otherwise the `keyboard-interactive` SSH authentication method would not work. Perhaps it can be disabled without the library but we thought this new dependency should not cause any problems.

**Comment by michalvasko** [comment]
Like I said, it was a mandatory requirement. But I have changed it and if you use the current `devel` branch, it should not longer be needed.

**Comment by sjd-xlnx** [comment]
Hi Michal,

I'm also having problems with libpam. It is not available on my system, and I'm currently trying to install it (from https://github.com/linux-pam/linux-pam), but it has issues and I don't succeed currently. I'll try the devel branch as suggested, but can I also suggest/request:
1) please list libpam as a dependency in the README for the mainpage
2) can you say which particular modules of libpam are required (it seems to be a huge library of packages, and I'm pretty sure not all of them are mandatory - might be able to get a build together that way)
3) any chance of not using libpam? I was using an older version of libnetconf2 which didn't use libpam, and only got this error when updating to latest version. What did you use prior to libpam?

Thanks in advance.

**Comment by michalvasko** [comment]
1. It was the purpose of last changes I made but somehow forgot to actually add it, should now finally be there (`devel`).
2. Sorry, I am not sure, we have just been using the package.
3. Yes, in the version in `devel`, please use that. It should only be a few weeks until the next release.
