### ISSUE TITLE
Getting error Cert verify: fail (self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by rosy8** [CESNET/libnetconf2#397]
Hi Michal,

We using the following libnetcon2 API for fetcting the certificates info during the TLS callhome.
```
    nc_server_tls_set_server_cert_clb(tls_set_server_cert_clb, NULL, NULL);
    nc_server_tls_set_server_cert_chain_clb(tls_set_server_cert_chain_clb, NULL, NULL);
    nc_server_tls_set_trusted_cert_list_clb(tls_set_trusted_cert_list_clb, NULL, NULL);
```
However the certificate validation is failing with the following error 
```
[ERR]: Cert verify: fail (self signed certificate in certificate chain).
[ERR]: SSL_accept failed (certificate verify failed).
```
**Netopeer2-cli output :**
```
cmd_listen: Waiting 99999s for a TLS Call Home connection on port 4335...
nc VERBOSE: Accepted a connection on ::0:4335 from ::ffff:XXXXXXXXX.
nc ERROR: SSL_connect failed (Success).
cmd_listen: Receiving TLS Call Home on port 4335 failed.
listen: unrecognized option '--tls'
cmd_listen: Unknown option -?.
listen [--help] [--timeout <sec>] [--host <hostname>] [--port <num>]
   SSH [--ssh] [--login <username>]
   TLS  --tls  [--cert <cert_path> [--key <key_path>]] [--trusted <trusted_CA_store.pem>]
>  listen --timeout 99999 --tls --cert /root/certs/ems_cert.pem --key /root/certs/ems_key.pem --trusted /root/certs/chain_cert.pem 
cmd_listen: Waiting 99999s for a TLS Call Home connection on port 4335...
nc VERBOSE: Accepted a connection on ::0:4335 from ::ffff:XXXXXXXXXX
nc ERROR: SSL_connect failed (tlsv1 alert unknown ca).
cmd_listen: Receiving TLS Call Home on port 4335 failed.
```
Please do let me know  if we missing anything here.

**FYI -  The openssl verify command between the certificates returns OK.**
```
bash-4.2$ openssl verify -verbose -CAfile server_cacert-0-0.pem ems_cert.pem
ems_cert.pem: OK
bash-4.2$ 
```
Would  not the netconf libs consider the cert list returned by the **nc_server_tls_set_trusted_cert_list_clb**  api callback  to be trusted ? Or additionaly we need to use some other API for doing so ?

Thank you in advance.

**Comment by michalvasko** [comment]
Look at the test server, lines [713](https://github.com/CESNET/libnetconf2/blob/master/tests/test_server_thread.c#L713) - 728 are performing the most basic setup so that the client can connect. I would say you set the callbacks but do not set the actual "certifcates" (they are just arbitrary names that are then referenced by endpoints).
