### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by hi-Mr-ye** [CESNET/libnetconf2#401]
Hi
I did the cmake operation, and make install operation
but make install dispaly error
![image](https://user-images.githubusercontent.com/90752673/207749025-ef3bb33d-66c2-4e3c-b30d-a6c757c967f8.png)
How to solve it?

**Comment by jktjkt** [comment]
The actual error message is not included; it's shown before this snippet.

**Comment by michalvasko** [comment]
Yes, I am not able to help because of what @jktjkt said. Also, please make sure you are compiling a reasonably recent version.

**Comment by hi-Mr-ye** [comment]
error message:
![image](https://user-images.githubusercontent.com/90752673/208018811-9e96ba6a-51aa-423f-8941-cc4fc43179fd.png)
I synced the latest libnetconf2 code

**Comment by hi-Mr-ye** [comment]
error message:
![image](https://user-images.githubusercontent.com/90752673/208019095-9a0b96c8-b0fb-4bee-8040-eb48ac3d9832.png)

I synced the latest libnetconf2 code.

**Comment by michalvasko** [comment]
That is a problem of your system, you have issues with your dynamic libraries. Specifically, `libpam` is linking `libaudit` that is not in the known paths, I cannot help you with this.
