### ISSUE TITLE
NETCONF session timeout when send multiple RPC

### ISSUE THREAD

**Issue by onghoaibao** [CESNET/libnetconf2#402]
Hi Michalvasko,

I have use case like this. 
**(1)** In NetconfClient app has a callhome, when recieve a connection from a NETCONF server:
1.  NETCONF Client app will send an RPC `nc_rpc_act_generic` to server.
2. After that every 1 second NETCONF Client app will send rpc GET `nc_rpc_get` to NETCONF server to probe.

with one NETCONF no any problem, but I have 10 NETCONF Server (the same config) connect to callhome of NETCONF Client app at the same time and run action **(1)** at step 1, then I get the problem with some NETCONF Server:
![image](https://user-images.githubusercontent.com/47877762/211179074-b8bc8582-fa0f-4bbe-b263-6be0f7b79b72.png)
I also investigate and I think the problem here **SSH connection timeout**.

Note: every connection callhome established will be run asynchronously

Do you have any idea for this one?

Version lib:
- libssh-0.9.6
- libnetconf2-2.0.19
- libyang2.0.231

Thank so much.

**Comment by michalvasko** [comment]
Can you provide more output, some messages before the one you included? But a timeout is possible with lots of concurrent `get` RPCs being sent (seems like a design problem).

**Comment by onghoaibao** [comment]
it doesn't show anything other than that error.
this error is unstable. when NetconfClient App send multiple `nc_rpc_act_generic`. 
I have tried to send it sequentially it doesn't error anymore.  It mean when the first request ends, the second will come, same for the rest of the requests.
 
So does the `nc_rpc_act_generic` method support sending multiple requests and receiving at the same time?

**Comment by michalvasko** [comment]
It is not limited by `nc_rpc_act_generic` but by the [NETCONF spec](https://datatracker.ietf.org/doc/html/rfc6241#section-4.5) and hence by *netopeer2-server*.
