### ISSUE TITLE
Questions about libnetconf2-API.

### ISSUE THREAD

**Issue by rydy** [CESNET/libnetconf2#406]
Hi,

Does `libnetconf2-API` support multiple threads calls for the same session?

Best Regards,
thanks

**Comment by michalvasko** [comment]
Do you have an additional question to what is mentioned in the [docs](https://netopeer.liberouter.org/doc/libnetconf2/master/html/howtoinit.html)?

**Comment by rydy** [comment]
> Do you have an additional question to what is mentioned in the [docs](https://netopeer.liberouter.org/doc/libnetconf2/master/html/howtoinit.html)?

I see: `every other thread you should call nc_thread_destroy() just before it exits`.
I have one more question, The APIs of the [client communication](https://netopeer.liberouter.org/doc/libnetconf2/master/html/howtoclientcomm.html) are thread-safety, right?

**Comment by michalvasko** [comment]
Yes, the function on the page you referenced are thread-safe.

**Comment by rydy** [comment]
> Yes, the function on the page you referenced are thread-safe.

Is there a problem with the following scenario with multiple threads?
Step 1: The main-thread send `get` via [nc_send_rpc()](https://netopeer.liberouter.org/doc/libnetconf2/master/html/group__client__session.html#gaeac0805b9a2f6538244c52eead088612),
Step 2: The child-thread send `edit_config` via [nc_send_rpc()](https://netopeer.liberouter.org/doc/libnetconf2/master/html/group__client__session.html#gaeac0805b9a2f6538244c52eead088612),
Step 3: The main-thread receive reply of the child-thread  via [nc_recv_reply()](https://netopeer.liberouter.org/doc/libnetconf2/master/html/group__client__session.html#ga3cfe333eeb6dea6fa85d0a9794ab7d7a)
If this happens, how do you ensure reply are consistent?

**Comment by michalvasko** [comment]
That should actually work, you pair the replies to the sent RPCs with the `msgid` parameter of `nc_recv_reply()`. But you will also have to pass the `rpc` used when calling `nc_send_rpc()`.

**Comment by rydy** [comment]
> That should actually work, you pair the replies to the sent RPCs with the `msgid` parameter of `nc_recv_reply()`. But you will also have to pass the `rpc` used when calling `nc_send_rpc()`.

Ok, I misunderstood.

**Comment by rydy** [comment]
I still have some doubts about the use of nc_thread_destroy(), My application has multiple threads and some child threads not use [libnetconf2-API](https://netopeer.liberouter.org/doc/libnetconf2/master/html/howtoclientcomm.html).  Do they also need to call [nc_thread_destroy()](https://netopeer.liberouter.org/doc/libnetconf2/master/html/session_8h.html#a63af405e357301bf30772e878281d3f2) before they exits?

**Comment by michalvasko** [comment]
It is just for clearing reachable memory so if you do not care about that, you can ignore it altogether. Nevertheless, the function probably needs to be called in every thread that is created after `nc_client_init()` is called, not sure. It is actually *libcrypto* that requires this.

**Comment by rydy** [comment]
> It is just for clearing reachable memory so if you do not care about that, you can ignore it altogether. Nevertheless, the function probably needs to be called in every thread that is created after `nc_client_init()` is called (even though they do not call any _libnetconf2_ functions), not sure. It is actually _libcrypto_ that requires this.

Thank you for your reply.
