### ISSUE TITLE
The application occasionally exits abnormally after calling nc_session_free.

### ISSUE THREAD

**Issue by rydy** [CESNET/libnetconf2#409]
Hi Michal,
    I have a question about `nc_session` management,  the `nc_session` is released after [nc_session_free](https://netopeer.liberouter.org/doc/libnetconf2/master/html/session_8h.html#a2f0ce65db8b580667f210af36cf2c0ea) is called, but the [nc_recv_notif_thread](https://github.com/CESNET/libnetconf2/blob/master/src/session_client.c) is still working, is this a bug?
```
static void *
nc_recv_notif_thread(void *arg)
{
    struct nc_ntf_thread_arg *ntarg;
    struct nc_session *session;
    nc_notif_dispatch_clb notif_clb;
    void *user_data;

    void (*free_data)(void *);
    struct lyd_node *envp, *op;
    NC_MSG_TYPE msgtype;

    /* detach ourselves */
    pthread_detach(pthread_self());

    ntarg = (struct nc_ntf_thread_arg *)arg;
    session = ntarg->session;
    notif_clb = ntarg->notif_clb;
    user_data = ntarg->user_data;
    free_data = ntarg->free_data;
    free(ntarg);

    while (ATOMIC_LOAD_RELAXED(session->opts.client.ntf_thread_running)) {
        msgtype = nc_recv_notif(session, NC_CLIENT_NOTIF_THREAD_SLEEP / 1000, &envp, &op);
        if (msgtype == NC_MSG_NOTIF) {
            notif_clb(session, envp, op, user_data);
            if (!strcmp(op->schema->name, "notificationComplete") && !strcmp(op->schema->module->name, "nc-notifications")) {
                lyd_free_tree(envp);
                lyd_free_all(op);
                break;
            }
            lyd_free_tree(envp);
            lyd_free_all(op);
        } else if ((msgtype == NC_MSG_ERROR) && (session->status != NC_STATUS_RUNNING)) {
            /* quit this thread once the session is broken */
            break;
        }

        usleep(NC_CLIENT_NOTIF_THREAD_SLEEP);
    }

    VRB(session, "Notification thread exit.");
    ATOMIC_DEC_RELAXED(session->opts.client.ntf_thread_count);
    if (free_data) {
        free_data(user_data);
    }

    return NULL;
}
```

**Comment by michalvasko** [comment]
Yes, if the thread is running after the session was freed that is definitely a problem but I do not see how it could happen, the threads are stopped as the [first thing](https://github.com/CESNET/libnetconf2/blob/master/src/session.c#L810) when freeing a session.

**Comment by rydy** [comment]
> Yes, if the thread is running after the session was freed that is definitely a problem but I do not see how it could happen, the threads are stopped as the [first thing](https://github.com/CESNET/libnetconf2/blob/master/src/session.c#L810) when freeing a session.

You are right, I don't think that's going to happen.

**Comment by rydy** [comment]
I don't think[ libnetconf2-API](https://netopeer.liberouter.org/doc/libnetconf2/master/html/howtoclientcomm.html) is thread-safe because the lock location does not cover the whole `nc_session`. the `nc_session` is not NULL after [nc_session_free](https://netopeer.liberouter.org/doc/libnetconf2/master/html/session_8h.html#a2f0ce65db8b580667f210af36cf2c0ea) was called. What's your opinion on this?

**Comment by michalvasko** [comment]
What exactly do you mean? AT the point you are calling `nc_session_free()` on a session you must make sure the session is no longer used anywhere by your application (except for the library threads such as the notification thread). That is how it always works because it is generally redundant to make this thread safe and in any case, how exactly do you think it should work? You be able to free a session in several threads and the library handling so that it is actually freed only once? Why would you need such functionality?

**Comment by rydy** [comment]
> What exactly do you mean? AT the point you are calling `nc_session_free()` on a session you must make sure the session is no longer used anywhere by your application (except for the library threads such as the notification thread). That is how it always works because it is generally redundant to make this thread safe and in any case, how exactly do you think it should work? You be able to free a session in several threads and the library handling so that it is actually freed only once? Why would you need such functionality?

I see what you mean, maybe we have different ideas about thread safety.
As I understand it, even if the caller calls the API incorrectly(For example: calling `nc_session_free()` and then calling `nc_send_rpc()`), it should not exit abnormally.

**Comment by michalvasko** [comment]
Perhaps, but I am referring to the official thread-safety, look at functions such as `free()`. It is completely thread-safe but that does not mean you can access a value after calling `free()` on it.

**Comment by rydy** [comment]
> Perhaps, but I am referring to the official thread-safety, look at functions such as `free()`. It is completely thread-safe but that does not mean you can access a value after calling `free()` on it. It is not worth it to cover these use-cases so it is never done but that does not break thread-safety. Also, it is exactly the reason why `*_free()` is used as the name of the function, it has all the properties of `free()`, regarding thread-safety and everything else (such as making the value/session unusable after calling it).

I got it, thank you for your reply.
