### ISSUE TITLE
SSH connect problem 

### ISSUE THREAD

**Issue by cigdem123** [CESNET/libnetconf2#411]
I'm connecting with socket but i'm getting this error when connecting via ssh :

server -s /home/yagmur/.ssh/id_rsa
Using SSH!
[ERR]: Failed to set hostkey "server_hostkey" (/home/yagmur/.ssh/id_rsa).
Error while accepting a hello message.
------------------------------------------------------
client -s get-config candidate
[ERR]: Starting the SSH session failed (Socket error: Connection reset by peer).
Couldn't connect to the server
----------------------------------------------------------------------------
How can i solve this problem ?

**Comment by michalvasko** [comment]
Not sure what the problem is, there are no details. What *libssh* version are you using?
