### ISSUE TITLE
Can libnetconf2 client connects to real router? 

### ISSUE THREAD

**Issue by Zephyre777** [CESNET/libnetconf2#419]
I have used libnetconf2 to write a netconf client. When I was using the netopeer2 server to server reply, everything(get, get-schema etc.) works fine. But when I try to use it to connect to real device it throws segmentation fault at nc_connect_ssh().  
I would like to know if it can only connect to server that is implemented with libnetconf2 or not?  
Thanks!

**Comment by jktjkt** [comment]
NETCONF is a standard, SSH is a standard, and both libssh and libnetconf2 aim to implement these standards. If your code which uses `libnetconf2` segfaults during connecting to another device, either there's a bug in your code, or in libnetconf2, or in libssh. Please post your code and the backtrace. Also, I suggest using ASAN+UBSAN for debugging "mysterious segfaults".

**Comment by michalvasko** [comment]
You are using *libnteconf2* without debugging symbols so it is not too helpful. But I do not really understand the stack trace anyway, did it crash in ASAN code? That is most strange.

**Comment by Zephyre777** [comment]
Thanks a lot! 
I found that the device I am connecting to does not support public key authentication so I changed it to password authentication.
I tried to run the client with debugging symbols and it turned out that the connection and authentication were both successful.
