### ISSUE TITLE
Polling empty session when realloc function failed

### ISSUE THREAD

**Issue by q664742232** [CESNET/libnetconf2#426]
https://github.com/CESNET/libnetconf2/blob/ac1786b742cff30a57b7ca51862b68b308cc87ef/src/session_server.c#LL1179C14-L1179C14

Is need to add ```--ps->session_count``` when realloc failed, just like line 1184 ?

**Comment by michalvasko** [comment]
No, all the sessions are then freed. But I am not sure why are you looking at that code, it is never going to actually happen and even if so, you would have more serious problems than a wrong counter.

**Comment by q664742232** [comment]
We are doing update from v1.1.46 to v2.x and I’m going through our private patch of libnetconf2 of v1.1.46. This is one of the patches.
Thanks for the answer, and I'll take a good look at this part of the code again.

**Comment by q664742232** [comment]
ok I agree with you and will focus on more important ones. thank you for your time
