### ISSUE TITLE
Use CLOCK_MONOTONIC at some places instead of CLOCK_REALTIME

### ISSUE THREAD

**Issue by mohitarora24** [CESNET/libnetconf2#43]
As per my understanding, at many places monotonic clock should be used instead of real time clock.

Like in the main loop of nc_ps_poll. Timeouts are affected using real time clock when changing TOD of the system.

Also, last_rpc & idle timeout calculations for call home connections should also be using monotonic clocks.

I'm saying this because I was using a very slightly modified version of nc_ps_poll in my code. On changing the system time backwards (say by 2 hours), thread having nc_ps_lock got stuck in a loop for 2 hours, and other threads were deprived of the lock during that time.
Changing to monotonic clock in nc_ps_poll solved the issue.

I thought to change nc_gettimespec to use monotonic clock, but it's being used for pthread_mutex_timedlock & pthread_cond_timedwait which need absolute time.

So selective changes need to be made.

**Comment by mohitarora24** [comment]
Hi, Thanks for the quick fix.

One query...
In `nc_ps_poll` - we're using mono clock now. So same `ts_cur.tv_sec` is passed to `nc_ps_poll_session`.
And inside `nc_ps_poll_session` we use this value to check for idle timeout:
```
(now >= session->opts.server.last_rpc + server_opts.idle_timeout)
```

However as I can see - we update last_rpc using:
```
cur_session->opts.server.last_rpc = time(NULL);
```
So `last_rpc` is the real time, howver `now` is the monotonic time. It would misbehave, I guess?
# 

In functions like `nc_server_ch_client_thread_session_cond_wait` it's compared against real time only...
```
nc_gettimespec_real(&ts);
nc_addtimespec(&ts, NC_CH_NO_ENDPT_WAIT);
 .
 .
 ... (ts.tv_sec >= session->opts.server.last_rpc + idle_timeout) ,,,
```

**Comment by michalvasko** [comment]
Hi,
I missed this, thanks.

Regards,
Michal
