### ISSUE TITLE
Getting error message from libnetcionf2 -  nc_error Waiting for notification thread exit failed (timed out).

### ISSUE THREAD

**Issue by sagar2725** [CESNET/libnetconf2#431]
Hello Netconf Team,

I am getting below error from libnetconf2 in my application. Can someone please let me know what are the probable causes of this error ?

Regrads
Sagar

**Comment by Roytak** [comment]
Hi, it is hard to tell without further information, but it most likely has something to do with your `nc_notif_dispatch_clb` notification callback.

**Comment by michalvasko** [comment]
Yes, can you please share some more details? And the *libnetconf2* version you are using?
