### ISSUE TITLE
libnetconf2 session client aborted in FD_SET and select when (fd > 1024), update to epoll/poll? 

### ISSUE THREAD

**Issue by starx1000** [CESNET/libnetconf2#439]
Hi,
 - libnetconf2 version 2.1.37

Currently we are facing a libnetconf abort issue and we see that it is failed in     
```c
FD_SET(sock, &wset);
```
the sock id is 1065,  I see in some articles that the fd number should less than 1024 when use this API.

https://stackoverflow.com/questions/49021919/more-than-1024-clients-using-fd-set

Is it possible to change this usage to use "poll" or "epoll" ?  thank you. 

https://github.com/CESNET/libnetconf2/blob/4514f16d71665a1b2c7ad29908474ef67526ed07/src/session_client.c#L1620

```
#0  0x00007ffa05108794 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffa050b7afe in raise () from /lib64/libc.so.6
#2  0x00007ffa050a090f in abort () from /lib64/libc.so.6
#3  0x00007ffa050a160f in __libc_message.cold () from /lib64/libc.so.6
#4  0x00007ffa0519c819 in __fortify_fail () from /lib64/libc.so.6
#5  0x00007ffa0519c765 in __fdelt_warn () from /lib64/libc.so.6
#6  0x00007ffa002afd8f in sock_connect (timeout_ms=-1, sock_pending=0x0, res=<optimized out>, ka=0x7ff934044cf8) at /usr/src/debug/libnetconf2-2.1.37-1.fc38.x86_64/src/session_client.c:1620
#7  0x00007ffa002b4e21 in nc_sock_connect (host=0x7ff9d27fb6a0 "configserver", port=<optimized out>, timeout_ms=-1, ka=0x7ff934044cf8, sock_pending=0x0, ip_host=0x7ff9d27fb550)
```

(gdb) p sock
$1 = 1065
(gdb) p wset
$2 = {fds_bits = {0 <repeats 16 times>}}

**Comment by michalvasko** [comment]
No problem, fixed.

**Comment by starx1000** [comment]
great, thank you!
