### ISSUE TITLE
Missing NC_PSPOLL_REPLY_ERROR in nc_ps_poll result

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libnetconf2#443]
Hi,

When rpc-error is sent directly by libnetconf2 library, `NC_PSPOLL_REPLY_ERROR` flag is not set in `nc_ps_poll` result.
For example, when sending this invalid netconf rpc:

```
<rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <invalid>
    <data/>
  </invalid>
</rpc>
```

Since this flag is used for out-rpc-errors, this will not be incremented correctly in this case.

libyang version: 2.1.132
sysrepo version: 2.2.125
libnetconf2 version:  2.1.39

Thank you in advance!

**Comment by michalvasko** [comment]
Right, fixed in the latest `devel` (failed to reference it properly).

**Comment by awesomenode** [comment]
Now it works with latest version, thanks!
