### ISSUE TITLE
Is "session idle timeout elapsed" a error or a normal use case?

### ISSUE THREAD

**Issue by starx1000** [CESNET/libnetconf2#444]
hi,
  Currently when session idle timeout elapsed happen a error log will be printed.

  https://github.com/CESNET/libnetconf2/blob/4514f16d71665a1b2c7ad29908474ef67526ed07/src/session_server.c#L1581

This log will print when default configuration used( timeout 3600 ) unless explicitly set it to 0
```
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    <listen>
        <idle-timeout>0</idle-timeout>
```

the code print like 
```c++
                        case NC_PSPOLL_SESSION_TERM | NC_PSPOLL_SESSION_ERROR:
                            ERR(cur_session, "%s.", msg);
```
is it VRB(info log) enough for this use case?
e.g 
```c++
  VRB (cur_session, "%s.", msg);
```

reference link: 
https://github.com/CESNET/libnetconf2/blob/4514f16d71665a1b2c7ad29908474ef67526ed07/src/session_server.c#L1778

**Comment by michalvasko** [comment]
Does it matter that much to you? I think it can be interpreted as an error, you should not generally want to have your sessions terminated because of the idle timeout. It is there rather to prevent inactive sessions from holding server resources.

**Comment by starx1000** [comment]
With default configuration, after 3600s we will get the error log, the tester are tending to think that error log in normal use cases should not happen.
So the only choice currently is to set the idle timeout to 0.
>>
Our configuration usually happens during system startup and after that time there is no configuration happen(no data). or very unlikely to have configuration changes( in most cases )
So the server will think the client is idle and will terminate the client.

besides I think client recovery can happen, right?
```
After the client terminated, if some new configuration changes come the client call nc_send_rpc will get a NC_MSG_ERROR and 
   nc_session_get_status(nc_session) != NC_STATUS_RUNNING

then client application can retry to re-connect and send data.  
```

if the client can be recovered from idle timeout, I am prefer to use default configuration 3600s idle timeout , which can save server resources. this need this log prints not ERR.  

if the client can not be recovered from idle timeout, then I have to use idle timeout 0.

**Comment by michalvasko** [comment]
The client cannot be "recovered", the text was probably trying to say that the session then correctly terminates and can be reestablished. So yes, if you do not mind possible stale sessions, disable the idle timeout.

**Comment by starx1000** [comment]
OK, great thanks.
