### ISSUE TITLE
Failed to create nc_rpc_get due to missing "ietf-netconf-with-defaults" module in the context

### ISSUE THREAD

**Issue by pekseow** [CESNET/libnetconf2#445]
Hi there, 

I am using Netconf Client library from the latest version of libnetconf2 (v.2.1.37) and have encountered some error while attempting to perform _nc_rpc_get_.
e.g.
```

       NcResult ncResult{};

        auto session = connect(host, port, isTlsEnabled);
        if (!session) {
            ncResult.result = false;
            Logger::logError("NetconfClient failed to connect");
            return ncResult;
        }

        struct nc_rpc *rpc = nc_rpc_get(filter.c_str(), NC_WD_ALL, NC_PARAMTYPE_CONST);
        ncResult = executeRpc(session, rpc);

        nc_rpc_free(rpc);
        close(session);

```

The following error was seen on the console:
_libyang[0]: Module "iana-if-type" parsed with the wrong revision ("2019-02-08" instead "2021-06-21").
libyang[0]: Parsing module "iana-if-type" failed.
libyang[0]: Loading "iana-if-type" module failed. (path: Path "/".)
libyang[0]: Module "iana-if-type" parsed with the wrong revision ("2019-02-08" instead "2021-06-21").
libyang[0]: Parsing module "iana-if-type" failed.
libyang[0]: Loading "iana-if-type" module failed.
libyang[0]: Parsing module "o-ran-interfaces" failed.
libyang[0]: Loading "o-ran-interfaces" module failed.
libyang[0]: Parsing module "o-ran-synchronization" failed.
Session 6 [ERR]: Missing "ietf-netconf-with-defaults" module in the context.
Session 6 [ERR]: Failed to create RPC, perhaps a required feature is disabled_

There seems to be two issues:
1. On my Netconf server, I have _iana-if-type@2021-06-21.yang_, however, NCClient is picking up the version of iana-if-type.yang that comes with the library. I have set nc_client_set_schema_searchpath() but noticed that the iana-if-type@2021-06-21.yang is missing from the schema directory.

And I suspect the other modules that depends on the iana-if-type module failed to load as a result.

2. Missing "ietf-netconf-with-default", wouldn't the ncclient download (via get-schema) this ietf module from the Netconf server? I know it is loaded on the Netconf Server but did not see any get-schema for this module in the server log.

I would greatly appreciate it if you could help me figure out the possible root causes of these errors?

Cheers,
Pek Lee

**Comment by michalvasko** [comment]
You are asking questions mostly about NCClient, which is not our project and we know nothing about so we cannot help. If you need some help with *libnetconf2* then please state your queries clearly. Otherwise contact the maintainers of NCClient.

**Comment by pekseow** [comment]
Hi Michal,
Sorry about the confusion, I am referring to libnetconf2-based NETCONF Client. 
I will enable the verbose message and provide the details soon. 

The main problem I am facing is the NETCONF client seems to be unable to load the required libraries.

**Comment by pekseow** [comment]
Hi Michal,

After enabling verbose messaging, it seems that libnetconf2 library was unable to load a specified version of o-ran-interfaces module (i.e. o-ran-interfaces@2021-03-22) due to failure to parse the required version of iana-if-type module (i.e. iana-if-type@2021-06-21).  Is there limitation with loading specific version of module?

```
 : 
Session 3 [INF]: Capability for <get-schema> support found.
Session 3 [INF]: Capability for yang-library support found.
Session 3 [INF]: Capability for XPath filter support found.
Session 3 [INF]: Capability for NMDA RPCs support not found.
 : 
 : 
 : 
Session 3 [INF]: Reading module "o-ran-interfaces@2021-03-22" from local file "/phoenix/component_tests/config/yang_ncclient/o-ran-interfaces@2021-03-22.yang".
Session 3 [INF]: Reading module "iana-if-type@2021-06-21" from local file "/usr/local/share/yang/modules/iana/iana-if-type.yang".
libyang[0]: Module "iana-if-type" parsed with the wrong revision ("2019-02-08" instead "2021-06-21").
libyang[0]: Parsing module "iana-if-type" failed.
libyang[0]: Loading "iana-if-type" module failed. (path: Path "/".)
Session 3 [WRN]: Failed to load module "o-ran-interfaces@2021-03-22".
```
From my understanding of the Netconf Client function, _nc_client_set_schema_searchpath()_, if the module if not found in directory specified, it would fetch from server.

I would expect that libnetconf2 to do a _<get-schema>_ to obtain the right version of module from the server. However, from the log, that did not happen. It seems to read the version from _/usr/local/share_. 

Hope you can help shed some light.

Thank you.

**Comment by michalvasko** [comment]
> I would expect that libnetconf2 to do a to obtain the right version of module from the server. However, from the log, that did not happen. It seems to read the version from /usr/local/share.

It is not that simple to always get this right. The problem here is that the local file does not have the revision in its name, rename `/usr/local/share/yang/modules/iana/iana-if-type.yang` to `/usr/local/share/yang/modules/iana/iana-if-type@2019-02-08.yang` and it may fix the issue.

**Comment by michalvasko** [comment]
Fine, it seems the fix was fairly easy and should not cause any additional problems.

**Comment by pekseow** [comment]
Thank you, Michal!
