### ISSUE TITLE
TLS: Cannot use SAN certificates: nc_server_config_create_cert_to_name: Assertion `n' failed.

### ISSUE THREAD

**Issue by AeroFlorian** [CESNET/libnetconf2#458]
Hello, 

when configuring module ietf-netconf-server:netconf-server with 

netconf-server-parameters/client-identity-mappings/cert-to-name/map-type x509c2n:san-rfc822-name, there is an assertion in libnetconf2:

![image](https://github.com/CESNET/libnetconf2/assets/32739256/c2467b7a-f445-4dc0-8ac0-5fe0b9a4a0a2)

This is a regression compared to release 2.1.34

This is due to leaf `name`not found in cert-to-name list.

However, YANG model `ietf-x509-cert-to-name@2014-12-10.yang` imported with libnetconf2 specifies that leaf `name` is set only if map-type is `specified`:

![image](https://github.com/CESNET/libnetconf2/assets/32739256/d62d9677-3244-4b18-8896-193c4101783a)

This results in unavailability to use SAN certificates in TLS with the new version 

The issue can be reproducible with netopeer2-server and the 4 xmls below: 

[tls_truststore.xml.txt](https://github.com/CESNET/libnetconf2/files/14131251/tls_truststore.xml.txt)
[tls_callhome.xml.txt](https://github.com/CESNET/libnetconf2/files/14131252/tls_callhome.xml.txt)
[tls_keystore.xml.txt](https://github.com/CESNET/libnetconf2/files/14131253/tls_keystore.xml.txt)
[tls_listen.xml.txt](https://github.com/CESNET/libnetconf2/files/14131254/tls_listen.xml.txt)

Versions taken:
| Library | Version |
|---------|----------|
| Netopeer2 | 2.2.13 |
| libyang | 2.1.148|
| sysrepo | 2.2.150 |
| libnetconf2 | 3.0.8 |

**Comment by michalvasko** [comment]
Right, fixed.

**Comment by AeroFlorian** [comment]
Works perfectly on 3.0.11
Thanks!
