### ISSUE TITLE
Set ietf-netconf-server idle-timeout to 0 will causes the client can not connected.([ERR]: LN: Session 2: Client <hello> timeout elapsed) libnetconf2 3.0.8

### ISSUE THREAD

**Issue by starx1000** [CESNET/libnetconf2#459]
Hi,
 In Libnetconf2 version [Version 3.0.8](https://github.com/CESNET/libnetconf2/releases/tag/v3.0.8).

when add `<idle-timeout>0</idle-timeout>` setting to ietf-netconf-server the client can not be connected, 
the server will always report 
`[ERR]: LN: Session 2: Client <hello> timeout elapsed.`

the reason is that in 
https://github.com/CESNET/libnetconf2/blob/d44d328e5773a4f34aad66d8754f9a1915c05729/src/session.c#L1484

timeout_io used the same value for ietf-netconf-server's idle-timeout value, if the idle_timeout set to 0, this timeout_io == 0,
causes the `    r = nc_read_msg_poll_io(session, timeout_io, &msg);` Return immediately and failed.

As according to ietf-netconf-server.yang , 0 should be supported for never drops inactive client session.

Can you please have a look for this?

Maybe we can change it like this?
```
  if(server_opts.idle_timeout ==0)
     timeout_io = 180 * 1000;  // 180 seconds default value
 else
     timeout_io = server_opts.idle_timeout * 1000;
```
or simply change to      `timeout_io = 180 * 1000;  // 180 seconds default value` ?
Will it block the server here forever if the client have no password action if set timeout_io to -1( permanent)?

References:

https://github.com/CESNET/libnetconf2/blob/d44d328e5773a4f34aad66d8754f9a1915c05729/modules/ietf-netconf-server%402023-12-28.yang#L452

>> If set to zero, then the server
           will never drop a session because it is idle.
```
      leaf idle-timeout {
        type uint16;
        units "seconds";
        default "180"; // three minutes
        description
          "Specifies the maximum number of seconds that a NETCONF
           session may remain idle. A NETCONF session will be
           dropped if it is idle for an interval longer than this
           number of seconds.  If set to zero, then the server
           will never drop a session because it is idle.";
      }
```

Detect session timeout:

https://github.com/CESNET/libnetconf2/blob/d44d328e5773a4f34aad66d8754f9a1915c05729/src/session_server.c#L1591

XML configuration:
```
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    <listen>
        <idle-timeout>0</idle-timeout>
        <endpoints>
            <endpoint>
                <name>default-ssh</name>
```

**Comment by michalvasko** [comment]
Yes, `0` was not supported, fixed.

**Comment by starx1000** [comment]
OK, thank you
