### ISSUE TITLE
Using the latest libnetconf2 with older ietf-keystore version

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libnetconf2#461]
Hi!

I'm trying to update to the latest libnetconf2 version, but I realized
that it depends on new versions (2019-11-20) of the ietf-keystore and ietf-
truststore models.

For compatiblity reasons I can't use these versions. Can libnetconf2
work with the older versions somehow? Is there perhaps an easy solution
to this problem, do you have any advice on how to tackle this?

Thanks!

**Comment by Roytak** [comment]
Hi, unfortunately no, I do not think that is possible. You would have to alter the implementation.

**Comment by michalvasko** [comment]
The previously used revisions were significantly changed compared to the current ones so they are incompatible and so is the library.

**Comment by awesomenode** [comment]
Sorry, I meant that I have to use the 2019-11-20 version of the ietf-keystore, ietf-truststore and ietf-crypto-types models.

What workaround would you recommend in this case? I guess because of the significant changes, compatibility with the older versions is out of the question, but perhaps there is another way? Maybe somehow circumvent some of the hardwired logic of libnetconf?

**Comment by michalvasko** [comment]
There is no workaround, the new version was written specifically with the purpose of using the latest (we hoped released but not yet, we will update them as soon as they are finally released) YANG modules. So the only suggestion I can give is to stick with the older version of *libnetconf2* until the modules you are depending on are updated.
