### ISSUE TITLE
OCSP support

### ISSUE THREAD

**Issue by kavk7** [CESNET/libnetconf2#463]
Hi,

Does libnetconf2 supports OCSP based peer certificate revocation status check ?
NOTE: currently using "2.1.25" version of libnetconf2 library.

Thanks!

**Comment by michalvasko** [comment]
No, it is not supported in any version and there no plans to. However, the YANG modules we are currently using in *libnetconf2* are still not finalized and this feature was mentioned yesterday. If it gets to the actual YANG modules, it would probably get implemented at some point.

**Comment by kavk7** [comment]
okay. Thank you.
