### ISSUE TITLE
Authenticate users with central user management

### ISSUE THREAD

**Issue by mattiaswal** [CESNET/libnetconf2#486]
I have been using netopeer2 as netconf server and the users are described in ietf-system and becomes entries in /etc/shadow,
This has worked before, but now (since the ietf-netconf-server YANG upgrade and libnetconf refactor),
it is also required to specify them in in ietf-netconf-server  as well. 

<pre>
{
    "ietf-netconf-server:netconf-server": {
	"listen": {
	    "endpoints": {
		"endpoint": [
		    {
			"name": "default-ssh",
			"ssh": {
			    "tcp-server-parameters": {
				"local-address": "::"
			    },
			    "ssh-server-parameters": {
				"server-identity": {
				    "host-key": [
					{
					    "name": "default-key",
					    "public-key": {
						"central-keystore-reference": "genkey"
					    }
					}
				    ]
				},
<b>
				"client-authentication": {
				    "users": {
					"user": [
					    {
						"name": "admin",
						"libnetconf2-netconf-server:keyboard-interactive": {
						    "libnetconf2-netconf-server:use-system-auth": {}
						}
					    }
					]
				    }
</b>
				}
			    }
			}
		    }
		]
	    }
	}
    }
}
</pre>
Why this change? Or am I doing something wrong?

**Comment by michalvasko** [comment]
Okay, but like I said, we do want to support this use-case. How exactly to support the system users has not yet been decided, we may use this `feature` if it seems sensible but we have tried to have a fixed feature set for now.

**Comment by mattiaswal** [comment]
Thanks for the quick answer. I can work around the problem.
