### ISSUE TITLE
Can we load a module which is not part of capablity advertised by server

### ISSUE THREAD

**Issue by devanathan-krishnan** [CESNET/libnetconf2#495]
into default libyang context created by libnetconf. The client uses nc_connect_ssh with NULL ly_ctx.

We are using Yumapro server, which sends some attributes in response to getbulk which is not known to the libnetconf2 client side and we are getting following error.
**_ERROR: Received an invalid message (Unknown (or not implemented) YANG module with namespace "
[http://yumaworks.com/ns/yumaworks-attrs"](http://yumaworks.com/ns/yumaworks-attrs%22)
for metadata "ya:datapath".)._**
We found that this yang is not advertised in capabilities by the server but still the attributes from the yang are used in the response.
https://github.com/YumaWorks/yumapro-yang/blob/main/yumaworks/yumaworks-attrs.yang

I am looking for option to load the yang into libnetconf2 explicitly to overcome this issue. How can I do that?

**Comment by michalvasko** [comment]
I suggest you provide your own `ly_ctx` for `nc_connect_ssh()` with the missing module loaded. When connecting, *libnetconf2* should load all the advertised modules just like before.
