### ISSUE TITLE
Netconf connection times out even with idle-timeout configured to 0

### ISSUE THREAD

**Issue by Krisscut** [CESNET/libnetconf2#496]
Hi !

**Versions:**
_netopeer2-2.2.13
sysrepo-2.2.150
libnetconf2-3.0.11.devel
libyang-2.1.148
libssh-0.10.5_

I'm having an issue using the idle-timeout to configure a listen endpoint like so: https://github.com/CESNET/libnetconf2/blob/47ca0fb5f94588d112ec2bf26946948189e1c18d/modules/ietf-netconf-server%402023-12-28.yang#L452-L462

![image](https://github.com/user-attachments/assets/7fa61f5a-7a36-4a65-ad18-d409a01dcedc)

I noticed there was an issue created earlier this year about it, see https://github.com/CESNET/libnetconf2/issues/459
I have the fix in my version (see last one):
![image](https://github.com/user-attachments/assets/88fd670f-f983-4ee4-a750-edb98fd51a39)

I'm having this error log, note that I patched some more logs in the lib and the timeout is correctly set to -1
![image](https://github.com/user-attachments/assets/df42fbf3-f709-41a9-a012-f5b2f55e7b78)

![image](https://github.com/user-attachments/assets/0e134466-a17b-4105-b0e5-b4d29ba1c174)

Could it be the version of the libssh that cause the problem ?

**Comment by michalvasko** [comment]
Seems to be a bug in *libssh*, [this](https://git.libssh.org/projects/libssh.git/tree/src/session.c#n806) timeout is used, which is actually [0](https://git.libssh.org/projects/libssh.git/tree/include/libssh/session.h#n101). I will report it later but it will take some time until it gets into an actual release.

**Comment by Krisscut** [comment]
Applying that change seems to solve the issue without any side effects that I noticed.

```diff
diff --no-dereference -ruN libssh-0.10.5.origin/src/session.c libssh-0.10.5/src/session.c
--- libssh-0.10.5.origin/src/session.c	2023-05-04 14:37:20.000000000 +0300
+++ libssh-0.10.5/src/session.c	2024-07-24 17:03:43.207785726 +0300
@@ -724,7 +724,7 @@
     int ret = SSH_OK;
 
     /* If a timeout has been provided, use it */
-    if (timeout >= 0) {
+    if (timeout >= 0 || timeout == SSH_TIMEOUT_INFINITE) {
         timeout_ms = timeout;
     } else {
         if (ssh_is_blocking(session)) {
```

**Comment by Krisscut** [comment]
For reference for future viewers, link to issue on libssh repo https://gitlab.com/libssh/libssh-mirror/-/issues/261

**Comment by michalvasko** [comment]
It will take some time till the fix is made and then released, so a workaround was committed until then.
