### ISSUE TITLE
Custom Netconf Capability

### ISSUE THREAD

**Issue by svashok** [CESNET/libnetconf2#499]
Hi,

As part of standard Netconf capability exchange the following may get exchanged between the server and client - candidate, rollback-on-error, validate, etc. Is it possible to add custom defined capabilities to Netconf server, like the Network Function Type, NF software version, etc.? Basically, how does the server get these capabilities information from the application during start up?

Thanks

**Comment by Roytak** [comment]
Hi, I believe the server gets this list from the YANG modules loaded into the libyang context that is used for accepting new sessions. Another option is to use [nc_server_set_capability](https://netopeer.liberouter.org/doc/libnetconf2/devel/html/group__server__functions.html#ga58104bd9af87c7b282dde7aa9f746beb).

**Comment by jktjkt** [comment]
The set of NETCONF capabilities is ["regulated"](https://datatracker.ietf.org/doc/html/rfc7803), and there's a [registry maintained by IANA](https://www.iana.org/assignments/netconf-capability-urns/netconf-capability-urns.xhtml). You are not expected to add custom entries into that list.

Prior to YANG 1.1, these capabilities would include a "list of supported YANG models", essentially. That's no longer the case as of YANG 1.1, and The Correct Way™ is to use the `ietf-yang-library`. The TL;DR version is that this is all done by sysrepo and netopeer2 for you (if you use these), and all of the YANG models which are available, along with their [features](https://datatracker.ietf.org/doc/html/rfc7950#section-5.6.2) are provided as state data in the [`ietf-yang-library` YANG model](https://datatracker.ietf.org/doc/html/rfc8525).

Regarding software version (etc), I suggest to take a look at the [`ietf-system`](https://datatracker.ietf.org/doc/html/rfc7317) and [`ietf-hardware`](https://datatracker.ietf.org/doc/html/rfc8348) models. If you're looking for an implementation of these with sysrepo, there's the [velia](https://github.com/CESNET/velia) project which you might (or might not) find useful.
