### ISSUE TITLE
missing CPackConfig.cmake file?

### ISSUE THREAD

**Issue by gherlein** [CESNET/libnetconf2#5]
CMake Error at CMakeLists.txt:36 (include):
  include could not find load file:

    CPackConfig.cmake

am I just missing a step that creates this file or is it missing?

**Comment by michalvasko** [comment]
Hi,
I have not encountered such an error, so I cannot really help you. But based on what I read, **CPack** is a packaging tool included in **CMake**, were you just trying to build and install *libnetconf2* or did you do something different? I don't think you need to do anything related to **CPack**.

Regards,
Michal

**Comment by gherlein** [comment]
This is an issue with libssh
