### ISSUE TITLE
Libnetconf2 build with static build of libssh

### ISSUE THREAD

**Issue by srikanthsubbaramu** [CESNET/libnetconf2#502]
Hi Michal, 

we have built libssh with -DSHARED_LIBS=OFF for libssh 0.10.6, when we try to compile with same, 
[root@lpt-fhyz314 build]# cmake -DBUILD_SHARED_LIBS=OFF  -DLIBSSH_LIBRARIES=/usr/local/lib64/libssh.a ..
CMake Warning at CMakeLists.txt:178 (message):
  valgrind executable not found! Disabling memory leaks tests.

-- Could NOT find CMocka (missing: CMOCKA_LIBRARIES CMOCKA_INCLUDE_DIR) (Required is at least version "1.0.1")
-- Disabling tests because of missing CMocka
-- Could NOT find Uncrustify (missing: UNCRUSTIFY) (Required is at least version "0.77")
-- Could NOT find MbedTLS (missing: MBEDTLS_INCLUDE_DIRS MBEDTLS_LIBRARIES) (Required is at least version "3.5.0")
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibSSH (missing: LIBSSH_LIBRARIES) (Required is at least
  version "0.9.5")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLibSSH.cmake:113 (find_package_handle_standard_args)
  CMakeLists.txt:255 (find_package)

i see above issue even if /usr/local/lib64/libssh.a is present, can you let us know if we have any alternative?

Thanks,
Srikanth

**Comment by michalvasko** [comment]
It should work if you also define `LIBSSH_INCLUDE_DIRS` where the include files are.
