### ISSUE TITLE
[ERR]: SSL_accept timeout.

### ISSUE THREAD

**Issue by Nandhu-rak** [CESNET/libnetconf2#504]
> **[ERR]: SSL_accept timeout.**

> [WRN]: inet_ntop() failed (No space left on device).
> 		....
> **[ERR]: SSL_accept timeout.**

> [WRN]: inet_ntop() failed (No space left on device).

It seems the multiple call home failure causing some memory leak issue and over a time which leads to the memory exhaustion...

**Comment by michalvasko** [comment]
What versions of the projects are you using? Have you looked at the memory consumption?

**Comment by Nandhu-rak** [comment]
As per the health-check log,512MB application memory is getting exhausted.
Also, there is an increase of memory  of size ~2.59MB observed from timestamp Aug7 00:44:33 UTC to Aug7 00:44:03 within ~30s.

 "version"           : "0.1.19-9",

**Comment by michalvasko** [comment]
What is that version exactly, where did you get it?

**Comment by Nandhu-rak** [comment]
i got this from crash file, may i know where to get it

**Comment by Nandhu-rak** [comment]
version 0.9.3

**Comment by michalvasko** [comment]
Okay, that is possible and would be a [7 year old version](https://github.com/CESNET/libnetconf2/tree/v0.9-r1). We do not support that and you will have to update to the latest release v3.3.3.
