### ISSUE TITLE
mbedtls: `mbedtls_x509_get_subject_alt_name_ext` is now a private API

### ISSUE THREAD

**Issue by rcmcdonald91** [CESNET/libnetconf2#510]
See here:
[https://github.com/Mbed-TLS/mbedtls/commit/25b282ebfe5cb84e73d6194e83dc8d6c5d9a25e4](https://github.com/Mbed-TLS/mbedtls/commit/25b282ebfe5cb84e73d6194e83dc8d6c5d9a25e4)

This breaks the build with at least mbedtls 3.6.0+

**Comment by Roytak** [comment]
Hello, you are right the API is now private. There was another API that the same thing happened to and based on my feedback they reverted it, see https://github.com/Mbed-TLS/mbedtls/commit/762f9f9cbb345fe3cfe8d412a876856e2e97785d . However, they did not revert it for this specific API and I missed it back then. So I agree to rewrite it without using the API.
