### ISSUE TITLE
Unexpected behavior on carrier delete attempt

### ISSUE THREAD

**Issue by zdevcic** [CESNET/libnetconf2#521]
Hello,

we are observing strange behavior when attempting to delete one carrier. In the test configuration we have 5 carriers: 3 Tx carriers active and 2 Rx carriers active. Carrier we want to delete is TxCarrier0, it is successfully moved to INACTIVE state first, and then we attempt to delete carrier using the following command from netopeer2-cli:

**edit-config --target running --config=delete_carrier.xml --defop=replace**

where delete_carrier.xml has following content

```
<user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
  <tx-array-carriers operation="delete" >
    <name>TxCarrier0</name>
  </tx-array-carriers>
</user-plane-configuration>
```

But, as an result we can see Netconf flows attempting to delete all 5 carriers. 

What is the catch? Can you please clarify further.

Thanks a lot.

**Comment by michalvasko** [comment]
I assume `name` is a leaf-list based on your description (a bit weird but possible). Then there is nothing unexpected about this, an operation is applied on each element. You specified `delete` for `tx-array-carriers`, so this element (assuming a container) is being deleted with all the descendants. Just move the operation to the element you actually want it to affect and it should work as expected.

**Comment by michalvasko** [comment]
Ah, sorry, I missed that your `operation` metadata has no namespace prefix so it is ignored. All the YANG metadata need namespaces, learn the details for this case in the [RFC](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2), `operation`. So, because you are using the default operation `replace`, all the previous data are simply being deleted and only the new data snipped configured. My second suggestion is for you to use `merge` default operation, it does not seem to me you are trying to replace the whole configuration.

**Comment by zdevcic** [comment]
Using `--defop=merge` was first thing we attempted, actually. And in that case no change was triggered, we get

**No datastore changes to apply.**

response from Netconf server. So in this case also we are missing namespace?

**Comment by michalvasko** [comment]
Yes, it works exactly as expected. Please learn how exactly is `edit-config` content applied in the RFC I referenced before.

**Comment by zdevcic** [comment]
I have made suggested namespace change and originally reported issue is resolved. But, now new issue is encountered during the edit-config processing:

`Invalid leafref value "TxCarrier0" - no target instance "/user-plane-configuration/tx-array-carriers/name" with the same value. (Data location "/o-ran-uplane-conf:user-plane-configuration/low-level-tx-links[name='TxLink8']/tx-array-carrier".)`

Please clarify, what else could be wrong. Thanks a lot.

**Comment by michalvasko** [comment]
I do not understand what you are asking. It seems the edit you are trying to apply is causing the resulting data to not be valid - a leafref is missing its target - so the change is correctly refused.

**Comment by zdevcic** [comment]
You are right, needed to delete complete tree. Since TxLink8 holds reference for the TxCarrier0 have to delete that one first.

All is working now. 

Thanks a lot for your support.
