### ISSUE TITLE
Invalid RPC tags cause netopeer2-server to SIGSEGV.

### ISSUE THREAD

**Issue by unmanned-player** [CESNET/libnetconf2#54]
Hello,

If you send an invalid RPC such as the one below, the latest libnetconf2 crashes.

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="5">
  <blah-blah/>
</rpc>
```

The error seems to originate in `src/messages_server.c:470` where it attempts to get the error message path. Call to `ly_errpath` can return `NULL` which isn't verified in the switch case for `LYVE_INELEM` which crashes with SIGSEGV.

For now, I've patched those lines with:
```
        case LYVE_INELEM:
            str = ly_errmsg(ctx);
            if (str) {
                if (strstr(str, "Unknown")) {
                    e = nc_err(NC_ERR_UNKNOWN_ELEM, NC_ERR_TYPE_PROT, ly_errpath(ctx));
                } else if (strstr(str, "Unsupported")) {
                    e = nc_err(NC_ERR_OP_NOT_SUPPORTED, NC_ERR_TYPE_APP);
                    return e;
                }
            } else {
                e = nc_err(NC_ERR_UNKNOWN_ELEM, NC_ERR_TYPE_PROT, ly_errpath(ctx));
            }
            break;
```

I could be wrong. Could you please have a look at it instead?

Thanks,
Anandu

**Comment by michalvasko** [comment]
Hi Anandu,
right, it should work now with the latest *libyang* `devel`.

Regards,
Michal
