### ISSUE TITLE
Whether to support "when" syntax ?

### ISSUE THREAD

**Issue by zyboy2000** [CESNET/libnetconf2#63]
i have a yang module ,it has "when" synatx, I find "relove_when" return error,  i wonder how to judge this variable(type) value ? or it does not support ?

 when "/oc-platform:components/oc-platform:component/" +
      "oc-platform:state/oc-platform:type = 'OPTICAL_CHANNEL'"

<error-message xml:lang="en">When condition "/openconfig-platform:components/openconfig-platform:component/openconfig-platform:state/openconfig-platform:type = 'OPTICAL_CHANNEL'" not satisfied.</error-message>

**Comment by michalvasko** [comment]
Hi,
I am not really sure what it is you are asking. It seems a `when` condition is false in your data tree so *libyang* cannot consider it valid. What do you not like about it?

Regards,
Michal

**Comment by zyboy2000** [comment]
but  why libyang consider it invalid ?  i give "type" leaf a value(as blow),  and i can get "type"leaf value through "get" command , i wonder whether   libyang will get the value of "type" leaf ? or how libyang will get the value of"type"leaf ?

    sr_val_set_xpath(&val[0], "/openconfig-platform:components/component[name='optic']/state/type");
    val[0].type = SR_IDENTITYREF_T;
    val[0].data.identityref_val = "openconfig-transport-types:OPTICAL_CHANNEL";

**Comment by zyboy2000** [comment]
you mean yang module is wrong ? shoud as flow 
 when "/oc-platform:components/oc-platform:component/" +
      "oc-platform:state/oc-platform:type = 'oct:OPTICAL_CHANNEL'"

**Comment by michalvasko** [comment]
Yeah, that is what I meant.

Regards,
Michal

**Comment by zyboy2000** [comment]
i try it but it does not work
 <error-message xml:lang="en">When condition "/openconfig-platform:components/openconfig-platform:component/openconfig-platform:state/openconfig-transport-types:type = 'openconfig-transport-types:OPTICAL_CHANNEL'" not satisfied.</error-message>

when "/oc-platform:components/oc-platform:component/oc-platform:state/oc-opt-types:type = 'OPTICAL_CHANNEL'"
oc-opt-types is my prefix for openconfig-transport-types import.

**Comment by zyboy2000** [comment]
i already modify yang module, but it still does not work!
  when "/oc-platform:components/oc-platform:component/oc-platform:state/oc-opt-types:type = 'oc-opt-types:OPTICAL_CHANNEL'"       

 (oc-opt-types is your prefix for openconfig-transport-types import.)

<error-message xml:lang="en">When condition "/openconfig-platform:components/openconfig-platform:component/openconfig-platform:state/openconfig-transport-types:type = 'openconfig-transport-types:OPTICAL_CHANNEL'" not satisfied.</error-message>

**Comment by michalvasko** [comment]
Okay, so what is the configuration in *sysrepo* before your changes and what exactly are the changes you are trying to apply? Also, isn't `/openconfig-platform:components/openconfig-platform:component/openconfig-platform:state` a state node?

Regards,
Michal

**Comment by zyboy2000** [comment]
/openconfig-platform:components/openconfig-platform:component/openconfig-platform:state a state node?   yes 

get command
<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <components xmlns="http://openconfig.net/yang/platform">
    <component>
      <name>optic</name>
      <config>
        <name>optic</name>
      </config>
      <chassis/>
      <port/>
      <state>
        <name>optic</name>
        <description>testboy</description>
        <type xmlns:oc-opt-types="http://openconfig.net/yang/transport-types">oc-opt-types:OPTICAL_CHANNEL</type>
      </state>
    </component>
  </components>
</data>

set command
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <edit-config>
    <target>
      <candidate/>
    </target>
    <config>
      <oc-platform:components xmlns:oc-platform="http://openconfig.net/yang/platform">
        <oc-platform:component>
          <oc-platform:name>optic</oc-platform:name>
          <oc-platform:config>
            <oc-platform:name>optic</oc-platform:name>
          </oc-platform:config>
          <oc-opt-term:optical-channel xmlns:oc-opt-term="http://openconfig.net/yang/terminal-device">
            <oc-opt-term:config>
              <oc-opt-term:frequency>9000</oc-opt-term:frequency>
            </oc-opt-term:config>
          </oc-opt-term:optical-channel>
        </oc-platform:component>
      </oc-platform:components>
    </config>
  </edit-config>
</rpc>

**Comment by michalvasko** [comment]
Right, then the model is referencing a state node in a configuration node `when`. Since the state data are not accessible from configuration data ([RFC](https://tools.ietf.org/html/rfc7950#section-6.4)), it always evaluates to false.

Regards,
Michal

**Comment by zyboy2000** [comment]
is it a bug? can it be fix in furture？

**Comment by michalvasko** [comment]
Hi,
it can be considered a bug of the model with the `when` condition. Openconfig guys are the only ones who could fix it so ask them.

Regards,
Michal

**Comment by zyboy2000** [comment]
Thank you for your patience and explanation！
