### ISSUE TITLE
oper data callback option

### ISSUE THREAD

**Issue by joanlandry** [CESNET/libnetconf2#7]
Is there a way to get a callback for oper data using libnetconf2/netopeer2, so far I only see a way to get a callback from sysrepo when a data store config change occurred. If this currently does not exist - will it eventually be available and if so what is the time frame for it and what mechanism will be available to get a call back?

**Comment by michalvasko** [comment]
Hi,
I don't think I understand what you mean. Let's say a daemon provides some data subtree. It registers this in sysrepo and when, for instance, a NETCONF client sends a get RPC to netopeer2-server, it builds the data by asking them from sysrepo, which delegates this request to the daemon itself. This works, but there are no real daemons supporting this yet. But you can look [here](https://github.com/sysrepo/sysrepo-plugin-ietf-system) for a sysrepo plugin that provides some operational data, it behaves almost like a daemon.

Regards,
Michal

**Comment by joanlandry** [comment]
I am referring to non config data, such as PM counters that reside in the HW on the box and would not be   in the sysrepo tree. My understanding is that sysrepo holds configuration data only - not counters and oper data.  The sample plugin does not show the ability to get a callback on a get for oper data. I would expect there would need to be the ability for netopeer2 to allow for retrieval of counters via a call back api to a non sysrepo function upon a Netconf get request.

**Comment by rkrejci** [comment]
Hi, sysrepo is now adding support also for status (operation) data. The implementation is in progress and with some limitations available in sysrepo devel branch. As Michal wrote, even status data, same as config data, will be retrieved via sysrepo. So, from the aplication daemon perspective, it is supposed to subscribe to sysrepo to a) get and manipulate with configuration data and b) provide status data.
