### ISSUE TITLE
Not able to run editconfig of Python library 

### ISSUE THREAD

**Issue by harshapic** [CESNET/libnetconf2#71]
I am trying to run " libnetconf2/python/examples/editconfig.py" but getting below issue,please help me in this.I am able to run get & serverinfo python examples:

~/libnetconf2/python/examples$ ./editconfig1.py 
hostname: localhost
port    : 830
username: vagrant
vagrant@localhost password : 
libyang[1]: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
Traceback (most recent call last):
  File "./editconfig1.py", line 66, in <module>
    print(data.print_mem(ly.LYD_XML, ly.LYP_FORMAT | ly.LYP_WITHSIBLINGS))
NameError: name 'data' is not defined

**Comment by rkrejci** [comment]
Hi,
you are running modified `editconfig1.py`, not `editconfig.py`. It seems that you have uncommented line that actually is not supposed to be there, it is taken from `get.py` example. Instead of this line, you can take bigger part from get example to get the data after edit-config:

```
# perform <get> and print result
try:
        data = session.rpcGet()
except nc.ReplyError as e:
        reply = {'success':False, 'error': []}
        for err in e.args[0]:
                reply['error'].append(json.loads(str(err)))
        print(json.dumps(reply))
        sys.exit(1)

print(data.print_mem(yang.LYD_XML, yang.LYP_FORMAT | yang.LYP_WITHSIBLINGS))
```

**Comment by harshapic** [comment]
Thanks it worked. Commented last print statement line in editconfig it worked.
