### ISSUE TITLE
cannot save private key to tmp file

### ISSUE THREAD

**Issue by ntadas** [CESNET/libnetconf2#83]
Hi

Its currently not possible to save a private key to a tmp file.
The  problem seems to be in:

https://github.com/CESNET/libnetconf2/blob/master/src/session_server_ssh.c#L56

here the file is open with the "read" option but some lines below the code is trying to write to the file.

Best Regards
Nuno

**Comment by michalvasko** [comment]
Hi,
right, thanks, should be fine now.

Regards,
Michal
