### ISSUE TITLE
subtree filtering on server

### ISSUE THREAD

**Issue by dmcpriv** [CESNET/libnetconf2#9]
Hi there,

Looking through the code it is not obvious if subtree filtering is supported by a feature of the server itself, or if the filter anyxml is simply passed to the callback and the callback is supposed to manage the parsing of the filter and apply it.

Some examples or description would be great, if they are available.

dmc

**Comment by rkrejci** [comment]
Documentation needs to be improved, so thanks for the feedback. libnetconf2 focuses on implementation of NETCONF transport (creating, sending and receiving NETCONF messages over a network). On the server side, it does not process RPC on its own, it just executes the callbacks. So, yes - even the get/get-config filter is just passed as an anyxml data into the callback and it is supposed to do whatever is needed to get result of the RPC. You can check the Netopeer2 [source codes](https://github.com/CESNET/Netopeer2/blob/master/server/op_get_config.c#L662) as an example.

**Comment by davemiedema** [comment]
Thanks!  I will check it out.  Even a link or mention of netopeer2 would be awesome.  If it is there, it is not obvious.
