### ISSUE TITLE
USERAUTH BANNER on login

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libnetconf2#94]
I was trying to get USERAUTH BANNER on login.

The code has an API named **nc_server_ssh_endpt_set_banner** which sets SSH banner for the Netconf server to send to a client when connecting. The API doesn't seems to work in my application.
Attached are client-side logs with debug logging. I set the banner string as **This is a banner!!**

Also, as I searched over the internet for underlying library (libssh) used here, it does not have support for the warning/MOTD/issue banner. This is based on the absence of any code for sending of the SSH_MSG_USERAUTH_BANNER / SSH2_MSG_USERAUTH_BANNER message from the server.
Libssh seems to use “banner” to mean protocol version (i.e. the string initially exchanged by client and server to determine compatibility SSHv1/SSHv2). Though the same has been supported in libssh2.

If this feature not covered in libnetconf2, is there any plan to support the same in near future or upgrade the libssh library to libssh2 to make such small feature work or any workaround that I can use here.
[Client Logs.txt](https://github.com/CESNET/libnetconf2/files/2471844/Client.Logs.txt)

**Comment by michalvasko** [comment]
I see, I just assumed it did what it said it did. Seems to me we best just remove the function as what it changes should not generally be changed.

Anyway, it will not be supported and we certainly will not "upgrade" to *libssh2* as it does not support SSH server at all and we will not use 2 SSH libraries.

Regards,
Michal
